/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateHoldingRequestDto, HoldingFindAllParams, HoldingSummaryParams } from '../model';

export type holdingFindAllResponse200 = {
  data: Blob;
  status: 200;
};

export type holdingFindAllResponseSuccess = holdingFindAllResponse200 & {
  headers: Headers;
};
export type holdingFindAllResponse = holdingFindAllResponseSuccess;

export const getHoldingFindAllUrl = (trackerId: string, params?: HoldingFindAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/holding/${trackerId}?${stringifiedParams}`
    : `/api/holding/${trackerId}`;
};

export const holdingFindAll = async (
  trackerId: string,
  params?: HoldingFindAllParams,
  options?: RequestInit,
): Promise<holdingFindAllResponse> => {
  const res = await fetch(getHoldingFindAllUrl(trackerId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: holdingFindAllResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as holdingFindAllResponse;
};

export const getHoldingFindAllQueryKey = (trackerId: string, params?: HoldingFindAllParams) => {
  return [`/api/holding/${trackerId}`, ...(params ? [params] : [])] as const;
};

export const getHoldingFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof holdingFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: HoldingFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHoldingFindAllQueryKey(trackerId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof holdingFindAll>>> = ({ signal }) =>
    holdingFindAll(trackerId, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof holdingFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HoldingFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof holdingFindAll>>>;
export type HoldingFindAllQueryError = unknown;

export function useHoldingFindAll<
  TData = Awaited<ReturnType<typeof holdingFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params: undefined | HoldingFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof holdingFindAll>>,
          TError,
          Awaited<ReturnType<typeof holdingFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHoldingFindAll<
  TData = Awaited<ReturnType<typeof holdingFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: HoldingFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof holdingFindAll>>,
          TError,
          Awaited<ReturnType<typeof holdingFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHoldingFindAll<
  TData = Awaited<ReturnType<typeof holdingFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: HoldingFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useHoldingFindAll<
  TData = Awaited<ReturnType<typeof holdingFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: HoldingFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHoldingFindAllQueryOptions(trackerId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type holdingCreateResponse200 = {
  data: Blob;
  status: 200;
};

export type holdingCreateResponseSuccess = holdingCreateResponse200 & {
  headers: Headers;
};
export type holdingCreateResponse = holdingCreateResponseSuccess;

export const getHoldingCreateUrl = (trackerId: string) => {
  return `/api/holding/${trackerId}`;
};

export const holdingCreate = async (
  trackerId: string,
  createHoldingRequestDto: CreateHoldingRequestDto,
  options?: RequestInit,
): Promise<holdingCreateResponse> => {
  const res = await fetch(getHoldingCreateUrl(trackerId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createHoldingRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: holdingCreateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as holdingCreateResponse;
};

export const getHoldingCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof holdingCreate>>,
    TError,
    { trackerId: string; data: CreateHoldingRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof holdingCreate>>,
  TError,
  { trackerId: string; data: CreateHoldingRequestDto },
  TContext
> => {
  const mutationKey = ['holdingCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof holdingCreate>>,
    { trackerId: string; data: CreateHoldingRequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return holdingCreate(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type HoldingCreateMutationResult = NonNullable<Awaited<ReturnType<typeof holdingCreate>>>;
export type HoldingCreateMutationBody = CreateHoldingRequestDto;
export type HoldingCreateMutationError = unknown;

export const useHoldingCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof holdingCreate>>,
      TError,
      { trackerId: string; data: CreateHoldingRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof holdingCreate>>,
  TError,
  { trackerId: string; data: CreateHoldingRequestDto },
  TContext
> => {
  return useMutation(getHoldingCreateMutationOptions(options), queryClient);
};
export type holdingFindByIdResponse200 = {
  data: Blob;
  status: 200;
};

export type holdingFindByIdResponseSuccess = holdingFindByIdResponse200 & {
  headers: Headers;
};
export type holdingFindByIdResponse = holdingFindByIdResponseSuccess;

export const getHoldingFindByIdUrl = (trackerId: string, holdingId: string) => {
  return `/api/holding/${trackerId}/${holdingId}`;
};

export const holdingFindById = async (
  trackerId: string,
  holdingId: string,
  options?: RequestInit,
): Promise<holdingFindByIdResponse> => {
  const res = await fetch(getHoldingFindByIdUrl(trackerId, holdingId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: holdingFindByIdResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as holdingFindByIdResponse;
};

export const getHoldingFindByIdQueryKey = (trackerId: string, holdingId: string) => {
  return [`/api/holding/${trackerId}/${holdingId}`] as const;
};

export const getHoldingFindByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof holdingFindById>>,
  TError = unknown,
>(
  trackerId: string,
  holdingId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindById>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHoldingFindByIdQueryKey(trackerId, holdingId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof holdingFindById>>> = ({ signal }) =>
    holdingFindById(trackerId, holdingId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(trackerId && holdingId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof holdingFindById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type HoldingFindByIdQueryResult = NonNullable<Awaited<ReturnType<typeof holdingFindById>>>;
export type HoldingFindByIdQueryError = unknown;

export function useHoldingFindById<
  TData = Awaited<ReturnType<typeof holdingFindById>>,
  TError = unknown,
>(
  trackerId: string,
  holdingId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof holdingFindById>>,
          TError,
          Awaited<ReturnType<typeof holdingFindById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHoldingFindById<
  TData = Awaited<ReturnType<typeof holdingFindById>>,
  TError = unknown,
>(
  trackerId: string,
  holdingId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof holdingFindById>>,
          TError,
          Awaited<ReturnType<typeof holdingFindById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHoldingFindById<
  TData = Awaited<ReturnType<typeof holdingFindById>>,
  TError = unknown,
>(
  trackerId: string,
  holdingId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindById>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useHoldingFindById<
  TData = Awaited<ReturnType<typeof holdingFindById>>,
  TError = unknown,
>(
  trackerId: string,
  holdingId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindById>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHoldingFindByIdQueryOptions(trackerId, holdingId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type holdingDeactivateResponse200 = {
  data: void;
  status: 200;
};

export type holdingDeactivateResponseSuccess = holdingDeactivateResponse200 & {
  headers: Headers;
};
export type holdingDeactivateResponse = holdingDeactivateResponseSuccess;

export const getHoldingDeactivateUrl = (trackerId: string, holdingId: string) => {
  return `/api/holding/${trackerId}/${holdingId}`;
};

export const holdingDeactivate = async (
  trackerId: string,
  holdingId: string,
  options?: RequestInit,
): Promise<holdingDeactivateResponse> => {
  const res = await fetch(getHoldingDeactivateUrl(trackerId, holdingId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: holdingDeactivateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as holdingDeactivateResponse;
};

export const getHoldingDeactivateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof holdingDeactivate>>,
    TError,
    { trackerId: string; holdingId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof holdingDeactivate>>,
  TError,
  { trackerId: string; holdingId: string },
  TContext
> => {
  const mutationKey = ['holdingDeactivate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof holdingDeactivate>>,
    { trackerId: string; holdingId: string }
  > = (props) => {
    const { trackerId, holdingId } = props ?? {};

    return holdingDeactivate(trackerId, holdingId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type HoldingDeactivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof holdingDeactivate>>
>;

export type HoldingDeactivateMutationError = unknown;

export const useHoldingDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof holdingDeactivate>>,
      TError,
      { trackerId: string; holdingId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof holdingDeactivate>>,
  TError,
  { trackerId: string; holdingId: string },
  TContext
> => {
  return useMutation(getHoldingDeactivateMutationOptions(options), queryClient);
};
export type holdingSummaryResponse200 = {
  data: Blob;
  status: 200;
};

export type holdingSummaryResponseSuccess = holdingSummaryResponse200 & {
  headers: Headers;
};
export type holdingSummaryResponse = holdingSummaryResponseSuccess;

export const getHoldingSummaryUrl = (
  trackerId: string,
  holdingId: string,
  params?: HoldingSummaryParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/holding/${trackerId}/${holdingId}/summary?${stringifiedParams}`
    : `/api/holding/${trackerId}/${holdingId}/summary`;
};

export const holdingSummary = async (
  trackerId: string,
  holdingId: string,
  params?: HoldingSummaryParams,
  options?: RequestInit,
): Promise<holdingSummaryResponse> => {
  const res = await fetch(getHoldingSummaryUrl(trackerId, holdingId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: holdingSummaryResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as holdingSummaryResponse;
};

export const getHoldingSummaryQueryKey = (
  trackerId: string,
  holdingId: string,
  params?: HoldingSummaryParams,
) => {
  return [`/api/holding/${trackerId}/${holdingId}/summary`, ...(params ? [params] : [])] as const;
};

export const getHoldingSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof holdingSummary>>,
  TError = unknown,
>(
  trackerId: string,
  holdingId: string,
  params?: HoldingSummaryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingSummary>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getHoldingSummaryQueryKey(trackerId, holdingId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof holdingSummary>>> = ({ signal }) =>
    holdingSummary(trackerId, holdingId, params, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(trackerId && holdingId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof holdingSummary>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type HoldingSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof holdingSummary>>>;
export type HoldingSummaryQueryError = unknown;

export function useHoldingSummary<
  TData = Awaited<ReturnType<typeof holdingSummary>>,
  TError = unknown,
>(
  trackerId: string,
  holdingId: string,
  params: undefined | HoldingSummaryParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingSummary>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof holdingSummary>>,
          TError,
          Awaited<ReturnType<typeof holdingSummary>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHoldingSummary<
  TData = Awaited<ReturnType<typeof holdingSummary>>,
  TError = unknown,
>(
  trackerId: string,
  holdingId: string,
  params?: HoldingSummaryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingSummary>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof holdingSummary>>,
          TError,
          Awaited<ReturnType<typeof holdingSummary>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHoldingSummary<
  TData = Awaited<ReturnType<typeof holdingSummary>>,
  TError = unknown,
>(
  trackerId: string,
  holdingId: string,
  params?: HoldingSummaryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingSummary>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useHoldingSummary<
  TData = Awaited<ReturnType<typeof holdingSummary>>,
  TError = unknown,
>(
  trackerId: string,
  holdingId: string,
  params?: HoldingSummaryParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingSummary>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHoldingSummaryQueryOptions(trackerId, holdingId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type holdingFindAllLiteResponse200 = {
  data: Blob;
  status: 200;
};

export type holdingFindAllLiteResponseSuccess = holdingFindAllLiteResponse200 & {
  headers: Headers;
};
export type holdingFindAllLiteResponse = holdingFindAllLiteResponseSuccess;

export const getHoldingFindAllLiteUrl = (trackerId: string) => {
  return `/api/holding/${trackerId}/lite`;
};

export const holdingFindAllLite = async (
  trackerId: string,
  options?: RequestInit,
): Promise<holdingFindAllLiteResponse> => {
  const res = await fetch(getHoldingFindAllLiteUrl(trackerId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: holdingFindAllLiteResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as holdingFindAllLiteResponse;
};

export const getHoldingFindAllLiteQueryKey = (trackerId: string) => {
  return [`/api/holding/${trackerId}/lite`] as const;
};

export const getHoldingFindAllLiteQueryOptions = <
  TData = Awaited<ReturnType<typeof holdingFindAllLite>>,
  TError = unknown,
>(
  trackerId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindAllLite>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHoldingFindAllLiteQueryKey(trackerId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof holdingFindAllLite>>> = ({ signal }) =>
    holdingFindAllLite(trackerId, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof holdingFindAllLite>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HoldingFindAllLiteQueryResult = NonNullable<
  Awaited<ReturnType<typeof holdingFindAllLite>>
>;
export type HoldingFindAllLiteQueryError = unknown;

export function useHoldingFindAllLite<
  TData = Awaited<ReturnType<typeof holdingFindAllLite>>,
  TError = unknown,
>(
  trackerId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindAllLite>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof holdingFindAllLite>>,
          TError,
          Awaited<ReturnType<typeof holdingFindAllLite>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHoldingFindAllLite<
  TData = Awaited<ReturnType<typeof holdingFindAllLite>>,
  TError = unknown,
>(
  trackerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof holdingFindAllLite>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof holdingFindAllLite>>,
          TError,
          Awaited<ReturnType<typeof holdingFindAllLite>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHoldingFindAllLite<
  TData = Awaited<ReturnType<typeof holdingFindAllLite>>,
  TError = unknown,
>(
  trackerId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindAllLite>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useHoldingFindAllLite<
  TData = Awaited<ReturnType<typeof holdingFindAllLite>>,
  TError = unknown,
>(
  trackerId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof holdingFindAllLite>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHoldingFindAllLiteQueryOptions(trackerId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
