/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateRecurringTransactionRequestDto,
  RecurringTransactionFindAllActiveParams,
  RecurringTransactionFindAllParams,
  UpdateRecurringTransactionRequestDto,
} from '../model';

export type recurringTransactionFindAllResponse200 = {
  data: Blob;
  status: 200;
};

export type recurringTransactionFindAllResponseSuccess = recurringTransactionFindAllResponse200 & {
  headers: Headers;
};
export type recurringTransactionFindAllResponse = recurringTransactionFindAllResponseSuccess;

export const getRecurringTransactionFindAllUrl = (
  trackerId: string,
  params?: RecurringTransactionFindAllParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/recurring-transaction/${trackerId}?${stringifiedParams}`
    : `/api/recurring-transaction/${trackerId}`;
};

export const recurringTransactionFindAll = async (
  trackerId: string,
  params?: RecurringTransactionFindAllParams,
  options?: RequestInit,
): Promise<recurringTransactionFindAllResponse> => {
  const res = await fetch(getRecurringTransactionFindAllUrl(trackerId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: recurringTransactionFindAllResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as recurringTransactionFindAllResponse;
};

export const getRecurringTransactionFindAllQueryKey = (
  trackerId: string,
  params?: RecurringTransactionFindAllParams,
) => {
  return [`/api/recurring-transaction/${trackerId}`, ...(params ? [params] : [])] as const;
};

export const getRecurringTransactionFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof recurringTransactionFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: RecurringTransactionFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRecurringTransactionFindAllQueryKey(trackerId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof recurringTransactionFindAll>>> = ({
    signal,
  }) => recurringTransactionFindAll(trackerId, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof recurringTransactionFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RecurringTransactionFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof recurringTransactionFindAll>>
>;
export type RecurringTransactionFindAllQueryError = unknown;

export function useRecurringTransactionFindAll<
  TData = Awaited<ReturnType<typeof recurringTransactionFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params: undefined | RecurringTransactionFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof recurringTransactionFindAll>>,
          TError,
          Awaited<ReturnType<typeof recurringTransactionFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRecurringTransactionFindAll<
  TData = Awaited<ReturnType<typeof recurringTransactionFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: RecurringTransactionFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof recurringTransactionFindAll>>,
          TError,
          Awaited<ReturnType<typeof recurringTransactionFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRecurringTransactionFindAll<
  TData = Awaited<ReturnType<typeof recurringTransactionFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: RecurringTransactionFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useRecurringTransactionFindAll<
  TData = Awaited<ReturnType<typeof recurringTransactionFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: RecurringTransactionFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRecurringTransactionFindAllQueryOptions(trackerId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type recurringTransactionCreateResponse200 = {
  data: Blob;
  status: 200;
};

export type recurringTransactionCreateResponseSuccess = recurringTransactionCreateResponse200 & {
  headers: Headers;
};
export type recurringTransactionCreateResponse = recurringTransactionCreateResponseSuccess;

export const getRecurringTransactionCreateUrl = (trackerId: string) => {
  return `/api/recurring-transaction/${trackerId}`;
};

export const recurringTransactionCreate = async (
  trackerId: string,
  createRecurringTransactionRequestDto: CreateRecurringTransactionRequestDto,
  options?: RequestInit,
): Promise<recurringTransactionCreateResponse> => {
  const res = await fetch(getRecurringTransactionCreateUrl(trackerId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRecurringTransactionRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: recurringTransactionCreateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as recurringTransactionCreateResponse;
};

export const getRecurringTransactionCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recurringTransactionCreate>>,
    TError,
    { trackerId: string; data: CreateRecurringTransactionRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recurringTransactionCreate>>,
  TError,
  { trackerId: string; data: CreateRecurringTransactionRequestDto },
  TContext
> => {
  const mutationKey = ['recurringTransactionCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recurringTransactionCreate>>,
    { trackerId: string; data: CreateRecurringTransactionRequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return recurringTransactionCreate(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecurringTransactionCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof recurringTransactionCreate>>
>;
export type RecurringTransactionCreateMutationBody = CreateRecurringTransactionRequestDto;
export type RecurringTransactionCreateMutationError = unknown;

export const useRecurringTransactionCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recurringTransactionCreate>>,
      TError,
      { trackerId: string; data: CreateRecurringTransactionRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recurringTransactionCreate>>,
  TError,
  { trackerId: string; data: CreateRecurringTransactionRequestDto },
  TContext
> => {
  return useMutation(getRecurringTransactionCreateMutationOptions(options), queryClient);
};
export type recurringTransactionFindByIdResponse200 = {
  data: Blob;
  status: 200;
};

export type recurringTransactionFindByIdResponseSuccess =
  recurringTransactionFindByIdResponse200 & {
    headers: Headers;
  };
export type recurringTransactionFindByIdResponse = recurringTransactionFindByIdResponseSuccess;

export const getRecurringTransactionFindByIdUrl = (trackerId: string, templateId: string) => {
  return `/api/recurring-transaction/${trackerId}/${templateId}`;
};

export const recurringTransactionFindById = async (
  trackerId: string,
  templateId: string,
  options?: RequestInit,
): Promise<recurringTransactionFindByIdResponse> => {
  const res = await fetch(getRecurringTransactionFindByIdUrl(trackerId, templateId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: recurringTransactionFindByIdResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as recurringTransactionFindByIdResponse;
};

export const getRecurringTransactionFindByIdQueryKey = (trackerId: string, templateId: string) => {
  return [`/api/recurring-transaction/${trackerId}/${templateId}`] as const;
};

export const getRecurringTransactionFindByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof recurringTransactionFindById>>,
  TError = unknown,
>(
  trackerId: string,
  templateId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindById>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRecurringTransactionFindByIdQueryKey(trackerId, templateId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof recurringTransactionFindById>>> = ({
    signal,
  }) => recurringTransactionFindById(trackerId, templateId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(trackerId && templateId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type RecurringTransactionFindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof recurringTransactionFindById>>
>;
export type RecurringTransactionFindByIdQueryError = unknown;

export function useRecurringTransactionFindById<
  TData = Awaited<ReturnType<typeof recurringTransactionFindById>>,
  TError = unknown,
>(
  trackerId: string,
  templateId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof recurringTransactionFindById>>,
          TError,
          Awaited<ReturnType<typeof recurringTransactionFindById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRecurringTransactionFindById<
  TData = Awaited<ReturnType<typeof recurringTransactionFindById>>,
  TError = unknown,
>(
  trackerId: string,
  templateId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof recurringTransactionFindById>>,
          TError,
          Awaited<ReturnType<typeof recurringTransactionFindById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRecurringTransactionFindById<
  TData = Awaited<ReturnType<typeof recurringTransactionFindById>>,
  TError = unknown,
>(
  trackerId: string,
  templateId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindById>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useRecurringTransactionFindById<
  TData = Awaited<ReturnType<typeof recurringTransactionFindById>>,
  TError = unknown,
>(
  trackerId: string,
  templateId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindById>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRecurringTransactionFindByIdQueryOptions(trackerId, templateId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type recurringTransactionDeactivateResponse200 = {
  data: void;
  status: 200;
};

export type recurringTransactionDeactivateResponseSuccess =
  recurringTransactionDeactivateResponse200 & {
    headers: Headers;
  };
export type recurringTransactionDeactivateResponse = recurringTransactionDeactivateResponseSuccess;

export const getRecurringTransactionDeactivateUrl = (trackerId: string, templateId: string) => {
  return `/api/recurring-transaction/${trackerId}/${templateId}`;
};

export const recurringTransactionDeactivate = async (
  trackerId: string,
  templateId: string,
  options?: RequestInit,
): Promise<recurringTransactionDeactivateResponse> => {
  const res = await fetch(getRecurringTransactionDeactivateUrl(trackerId, templateId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: recurringTransactionDeactivateResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as recurringTransactionDeactivateResponse;
};

export const getRecurringTransactionDeactivateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recurringTransactionDeactivate>>,
    TError,
    { trackerId: string; templateId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recurringTransactionDeactivate>>,
  TError,
  { trackerId: string; templateId: string },
  TContext
> => {
  const mutationKey = ['recurringTransactionDeactivate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recurringTransactionDeactivate>>,
    { trackerId: string; templateId: string }
  > = (props) => {
    const { trackerId, templateId } = props ?? {};

    return recurringTransactionDeactivate(trackerId, templateId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecurringTransactionDeactivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof recurringTransactionDeactivate>>
>;

export type RecurringTransactionDeactivateMutationError = unknown;

export const useRecurringTransactionDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recurringTransactionDeactivate>>,
      TError,
      { trackerId: string; templateId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recurringTransactionDeactivate>>,
  TError,
  { trackerId: string; templateId: string },
  TContext
> => {
  return useMutation(getRecurringTransactionDeactivateMutationOptions(options), queryClient);
};
export type recurringTransactionUpdateResponse200 = {
  data: Blob;
  status: 200;
};

export type recurringTransactionUpdateResponseSuccess = recurringTransactionUpdateResponse200 & {
  headers: Headers;
};
export type recurringTransactionUpdateResponse = recurringTransactionUpdateResponseSuccess;

export const getRecurringTransactionUpdateUrl = (trackerId: string, templateId: string) => {
  return `/api/recurring-transaction/${trackerId}/${templateId}`;
};

export const recurringTransactionUpdate = async (
  trackerId: string,
  templateId: string,
  updateRecurringTransactionRequestDto: UpdateRecurringTransactionRequestDto,
  options?: RequestInit,
): Promise<recurringTransactionUpdateResponse> => {
  const res = await fetch(getRecurringTransactionUpdateUrl(trackerId, templateId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateRecurringTransactionRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: recurringTransactionUpdateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as recurringTransactionUpdateResponse;
};

export const getRecurringTransactionUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof recurringTransactionUpdate>>,
    TError,
    { trackerId: string; templateId: string; data: UpdateRecurringTransactionRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof recurringTransactionUpdate>>,
  TError,
  { trackerId: string; templateId: string; data: UpdateRecurringTransactionRequestDto },
  TContext
> => {
  const mutationKey = ['recurringTransactionUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof recurringTransactionUpdate>>,
    { trackerId: string; templateId: string; data: UpdateRecurringTransactionRequestDto }
  > = (props) => {
    const { trackerId, templateId, data } = props ?? {};

    return recurringTransactionUpdate(trackerId, templateId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RecurringTransactionUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof recurringTransactionUpdate>>
>;
export type RecurringTransactionUpdateMutationBody = UpdateRecurringTransactionRequestDto;
export type RecurringTransactionUpdateMutationError = unknown;

export const useRecurringTransactionUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof recurringTransactionUpdate>>,
      TError,
      { trackerId: string; templateId: string; data: UpdateRecurringTransactionRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof recurringTransactionUpdate>>,
  TError,
  { trackerId: string; templateId: string; data: UpdateRecurringTransactionRequestDto },
  TContext
> => {
  return useMutation(getRecurringTransactionUpdateMutationOptions(options), queryClient);
};
export type recurringTransactionFindAllActiveResponse200 = {
  data: Blob;
  status: 200;
};

export type recurringTransactionFindAllActiveResponseSuccess =
  recurringTransactionFindAllActiveResponse200 & {
    headers: Headers;
  };
export type recurringTransactionFindAllActiveResponse =
  recurringTransactionFindAllActiveResponseSuccess;

export const getRecurringTransactionFindAllActiveUrl = (
  trackerId: string,
  params?: RecurringTransactionFindAllActiveParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/recurring-transaction/${trackerId}/active?${stringifiedParams}`
    : `/api/recurring-transaction/${trackerId}/active`;
};

export const recurringTransactionFindAllActive = async (
  trackerId: string,
  params?: RecurringTransactionFindAllActiveParams,
  options?: RequestInit,
): Promise<recurringTransactionFindAllActiveResponse> => {
  const res = await fetch(getRecurringTransactionFindAllActiveUrl(trackerId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: recurringTransactionFindAllActiveResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as recurringTransactionFindAllActiveResponse;
};

export const getRecurringTransactionFindAllActiveQueryKey = (
  trackerId: string,
  params?: RecurringTransactionFindAllActiveParams,
) => {
  return [`/api/recurring-transaction/${trackerId}/active`, ...(params ? [params] : [])] as const;
};

export const getRecurringTransactionFindAllActiveQueryOptions = <
  TData = Awaited<ReturnType<typeof recurringTransactionFindAllActive>>,
  TError = unknown,
>(
  trackerId: string,
  params?: RecurringTransactionFindAllActiveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindAllActive>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getRecurringTransactionFindAllActiveQueryKey(trackerId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof recurringTransactionFindAllActive>>> = ({
    signal,
  }) => recurringTransactionFindAllActive(trackerId, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof recurringTransactionFindAllActive>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RecurringTransactionFindAllActiveQueryResult = NonNullable<
  Awaited<ReturnType<typeof recurringTransactionFindAllActive>>
>;
export type RecurringTransactionFindAllActiveQueryError = unknown;

export function useRecurringTransactionFindAllActive<
  TData = Awaited<ReturnType<typeof recurringTransactionFindAllActive>>,
  TError = unknown,
>(
  trackerId: string,
  params: undefined | RecurringTransactionFindAllActiveParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindAllActive>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof recurringTransactionFindAllActive>>,
          TError,
          Awaited<ReturnType<typeof recurringTransactionFindAllActive>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRecurringTransactionFindAllActive<
  TData = Awaited<ReturnType<typeof recurringTransactionFindAllActive>>,
  TError = unknown,
>(
  trackerId: string,
  params?: RecurringTransactionFindAllActiveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindAllActive>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof recurringTransactionFindAllActive>>,
          TError,
          Awaited<ReturnType<typeof recurringTransactionFindAllActive>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useRecurringTransactionFindAllActive<
  TData = Awaited<ReturnType<typeof recurringTransactionFindAllActive>>,
  TError = unknown,
>(
  trackerId: string,
  params?: RecurringTransactionFindAllActiveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindAllActive>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useRecurringTransactionFindAllActive<
  TData = Awaited<ReturnType<typeof recurringTransactionFindAllActive>>,
  TError = unknown,
>(
  trackerId: string,
  params?: RecurringTransactionFindAllActiveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof recurringTransactionFindAllActive>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getRecurringTransactionFindAllActiveQueryOptions(trackerId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
