/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { TodoTagUpsertRequestDto } from '../model';

export type todoTagFindAllResponse200 = {
  data: Blob;
  status: 200;
};

export type todoTagFindAllResponseSuccess = todoTagFindAllResponse200 & {
  headers: Headers;
};
export type todoTagFindAllResponse = todoTagFindAllResponseSuccess;

export const getTodoTagFindAllUrl = (trackerId: string) => {
  return `/api/todo-tag/${trackerId}`;
};

export const todoTagFindAll = async (
  trackerId: string,
  options?: RequestInit,
): Promise<todoTagFindAllResponse> => {
  const res = await fetch(getTodoTagFindAllUrl(trackerId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: todoTagFindAllResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as todoTagFindAllResponse;
};

export const getTodoTagFindAllQueryKey = (trackerId: string) => {
  return [`/api/todo-tag/${trackerId}`] as const;
};

export const getTodoTagFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof todoTagFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof todoTagFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTodoTagFindAllQueryKey(trackerId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof todoTagFindAll>>> = ({ signal }) =>
    todoTagFindAll(trackerId, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof todoTagFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TodoTagFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof todoTagFindAll>>>;
export type TodoTagFindAllQueryError = unknown;

export function useTodoTagFindAll<
  TData = Awaited<ReturnType<typeof todoTagFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof todoTagFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof todoTagFindAll>>,
          TError,
          Awaited<ReturnType<typeof todoTagFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTodoTagFindAll<
  TData = Awaited<ReturnType<typeof todoTagFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof todoTagFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof todoTagFindAll>>,
          TError,
          Awaited<ReturnType<typeof todoTagFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTodoTagFindAll<
  TData = Awaited<ReturnType<typeof todoTagFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof todoTagFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useTodoTagFindAll<
  TData = Awaited<ReturnType<typeof todoTagFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof todoTagFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTodoTagFindAllQueryOptions(trackerId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type todoTagCreateResponse200 = {
  data: Blob;
  status: 200;
};

export type todoTagCreateResponseSuccess = todoTagCreateResponse200 & {
  headers: Headers;
};
export type todoTagCreateResponse = todoTagCreateResponseSuccess;

export const getTodoTagCreateUrl = (trackerId: string) => {
  return `/api/todo-tag/${trackerId}`;
};

export const todoTagCreate = async (
  trackerId: string,
  todoTagUpsertRequestDto: TodoTagUpsertRequestDto,
  options?: RequestInit,
): Promise<todoTagCreateResponse> => {
  const res = await fetch(getTodoTagCreateUrl(trackerId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(todoTagUpsertRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: todoTagCreateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as todoTagCreateResponse;
};

export const getTodoTagCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof todoTagCreate>>,
    TError,
    { trackerId: string; data: TodoTagUpsertRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof todoTagCreate>>,
  TError,
  { trackerId: string; data: TodoTagUpsertRequestDto },
  TContext
> => {
  const mutationKey = ['todoTagCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof todoTagCreate>>,
    { trackerId: string; data: TodoTagUpsertRequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return todoTagCreate(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TodoTagCreateMutationResult = NonNullable<Awaited<ReturnType<typeof todoTagCreate>>>;
export type TodoTagCreateMutationBody = TodoTagUpsertRequestDto;
export type TodoTagCreateMutationError = unknown;

export const useTodoTagCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof todoTagCreate>>,
      TError,
      { trackerId: string; data: TodoTagUpsertRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof todoTagCreate>>,
  TError,
  { trackerId: string; data: TodoTagUpsertRequestDto },
  TContext
> => {
  return useMutation(getTodoTagCreateMutationOptions(options), queryClient);
};
export type todoTagDeleteResponse200 = {
  data: void;
  status: 200;
};

export type todoTagDeleteResponseSuccess = todoTagDeleteResponse200 & {
  headers: Headers;
};
export type todoTagDeleteResponse = todoTagDeleteResponseSuccess;

export const getTodoTagDeleteUrl = (trackerId: string, tagId: string) => {
  return `/api/todo-tag/${trackerId}/${tagId}`;
};

export const todoTagDelete = async (
  trackerId: string,
  tagId: string,
  options?: RequestInit,
): Promise<todoTagDeleteResponse> => {
  const res = await fetch(getTodoTagDeleteUrl(trackerId, tagId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: todoTagDeleteResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as todoTagDeleteResponse;
};

export const getTodoTagDeleteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof todoTagDelete>>,
    TError,
    { trackerId: string; tagId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof todoTagDelete>>,
  TError,
  { trackerId: string; tagId: string },
  TContext
> => {
  const mutationKey = ['todoTagDelete'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof todoTagDelete>>,
    { trackerId: string; tagId: string }
  > = (props) => {
    const { trackerId, tagId } = props ?? {};

    return todoTagDelete(trackerId, tagId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TodoTagDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof todoTagDelete>>>;

export type TodoTagDeleteMutationError = unknown;

export const useTodoTagDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof todoTagDelete>>,
      TError,
      { trackerId: string; tagId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof todoTagDelete>>,
  TError,
  { trackerId: string; tagId: string },
  TContext
> => {
  return useMutation(getTodoTagDeleteMutationOptions(options), queryClient);
};
export type todoTagUpdateResponse200 = {
  data: Blob;
  status: 200;
};

export type todoTagUpdateResponseSuccess = todoTagUpdateResponse200 & {
  headers: Headers;
};
export type todoTagUpdateResponse = todoTagUpdateResponseSuccess;

export const getTodoTagUpdateUrl = (trackerId: string, tagId: string) => {
  return `/api/todo-tag/${trackerId}/${tagId}`;
};

export const todoTagUpdate = async (
  trackerId: string,
  tagId: string,
  todoTagUpsertRequestDto: TodoTagUpsertRequestDto,
  options?: RequestInit,
): Promise<todoTagUpdateResponse> => {
  const res = await fetch(getTodoTagUpdateUrl(trackerId, tagId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(todoTagUpsertRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: todoTagUpdateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as todoTagUpdateResponse;
};

export const getTodoTagUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof todoTagUpdate>>,
    TError,
    { trackerId: string; tagId: string; data: TodoTagUpsertRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof todoTagUpdate>>,
  TError,
  { trackerId: string; tagId: string; data: TodoTagUpsertRequestDto },
  TContext
> => {
  const mutationKey = ['todoTagUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof todoTagUpdate>>,
    { trackerId: string; tagId: string; data: TodoTagUpsertRequestDto }
  > = (props) => {
    const { trackerId, tagId, data } = props ?? {};

    return todoTagUpdate(trackerId, tagId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TodoTagUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof todoTagUpdate>>>;
export type TodoTagUpdateMutationBody = TodoTagUpsertRequestDto;
export type TodoTagUpdateMutationError = unknown;

export const useTodoTagUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof todoTagUpdate>>,
      TError,
      { trackerId: string; tagId: string; data: TodoTagUpsertRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof todoTagUpdate>>,
  TError,
  { trackerId: string; tagId: string; data: TodoTagUpsertRequestDto },
  TContext
> => {
  return useMutation(getTodoTagUpdateMutationOptions(options), queryClient);
};
