/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { WeeklyCheckinFindAllParams, WeeklyCheckinGenerateForDateParams } from '../model';

export type weeklyCheckinFindByWeekIndexResponse200 = {
  data: Blob;
  status: 200;
};

export type weeklyCheckinFindByWeekIndexResponseSuccess =
  weeklyCheckinFindByWeekIndexResponse200 & {
    headers: Headers;
  };
export type weeklyCheckinFindByWeekIndexResponse = weeklyCheckinFindByWeekIndexResponseSuccess;

export const getWeeklyCheckinFindByWeekIndexUrl = (
  trackerId: string,
  goalPlanId: string,
  weekIndex: number,
) => {
  return `/api/weekly-checkin/${trackerId}/${goalPlanId}/${weekIndex}`;
};

export const weeklyCheckinFindByWeekIndex = async (
  trackerId: string,
  goalPlanId: string,
  weekIndex: number,
  options?: RequestInit,
): Promise<weeklyCheckinFindByWeekIndexResponse> => {
  const res = await fetch(getWeeklyCheckinFindByWeekIndexUrl(trackerId, goalPlanId, weekIndex), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: weeklyCheckinFindByWeekIndexResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as weeklyCheckinFindByWeekIndexResponse;
};

export const getWeeklyCheckinFindByWeekIndexQueryKey = (
  trackerId: string,
  goalPlanId: string,
  weekIndex: number,
) => {
  return [`/api/weekly-checkin/${trackerId}/${goalPlanId}/${weekIndex}`] as const;
};

export const getWeeklyCheckinFindByWeekIndexQueryOptions = <
  TData = Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  weekIndex: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getWeeklyCheckinFindByWeekIndexQueryKey(trackerId, goalPlanId, weekIndex);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>> = ({
    signal,
  }) => weeklyCheckinFindByWeekIndex(trackerId, goalPlanId, weekIndex, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(trackerId && goalPlanId && weekIndex),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type WeeklyCheckinFindByWeekIndexQueryResult = NonNullable<
  Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>
>;
export type WeeklyCheckinFindByWeekIndexQueryError = unknown;

export function useWeeklyCheckinFindByWeekIndex<
  TData = Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  weekIndex: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>,
          TError,
          Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useWeeklyCheckinFindByWeekIndex<
  TData = Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  weekIndex: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>,
          TError,
          Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useWeeklyCheckinFindByWeekIndex<
  TData = Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  weekIndex: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useWeeklyCheckinFindByWeekIndex<
  TData = Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  weekIndex: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof weeklyCheckinFindByWeekIndex>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getWeeklyCheckinFindByWeekIndexQueryOptions(
    trackerId,
    goalPlanId,
    weekIndex,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type weeklyCheckinGenerateResponse200 = {
  data: Blob;
  status: 200;
};

export type weeklyCheckinGenerateResponseSuccess = weeklyCheckinGenerateResponse200 & {
  headers: Headers;
};
export type weeklyCheckinGenerateResponse = weeklyCheckinGenerateResponseSuccess;

export const getWeeklyCheckinGenerateUrl = (
  trackerId: string,
  goalPlanId: string,
  weekIndex: number,
) => {
  return `/api/weekly-checkin/${trackerId}/${goalPlanId}/${weekIndex}`;
};

export const weeklyCheckinGenerate = async (
  trackerId: string,
  goalPlanId: string,
  weekIndex: number,
  options?: RequestInit,
): Promise<weeklyCheckinGenerateResponse> => {
  const res = await fetch(getWeeklyCheckinGenerateUrl(trackerId, goalPlanId, weekIndex), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: weeklyCheckinGenerateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as weeklyCheckinGenerateResponse;
};

export const getWeeklyCheckinGenerateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof weeklyCheckinGenerate>>,
    TError,
    { trackerId: string; goalPlanId: string; weekIndex: number },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof weeklyCheckinGenerate>>,
  TError,
  { trackerId: string; goalPlanId: string; weekIndex: number },
  TContext
> => {
  const mutationKey = ['weeklyCheckinGenerate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof weeklyCheckinGenerate>>,
    { trackerId: string; goalPlanId: string; weekIndex: number }
  > = (props) => {
    const { trackerId, goalPlanId, weekIndex } = props ?? {};

    return weeklyCheckinGenerate(trackerId, goalPlanId, weekIndex, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type WeeklyCheckinGenerateMutationResult = NonNullable<
  Awaited<ReturnType<typeof weeklyCheckinGenerate>>
>;

export type WeeklyCheckinGenerateMutationError = unknown;

export const useWeeklyCheckinGenerate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof weeklyCheckinGenerate>>,
      TError,
      { trackerId: string; goalPlanId: string; weekIndex: number },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof weeklyCheckinGenerate>>,
  TError,
  { trackerId: string; goalPlanId: string; weekIndex: number },
  TContext
> => {
  return useMutation(getWeeklyCheckinGenerateMutationOptions(options), queryClient);
};
export type weeklyCheckinGenerateForDateResponse200 = {
  data: Blob;
  status: 200;
};

export type weeklyCheckinGenerateForDateResponseSuccess =
  weeklyCheckinGenerateForDateResponse200 & {
    headers: Headers;
  };
export type weeklyCheckinGenerateForDateResponse = weeklyCheckinGenerateForDateResponseSuccess;

export const getWeeklyCheckinGenerateForDateUrl = (
  trackerId: string,
  goalPlanId: string,
  params?: WeeklyCheckinGenerateForDateParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/weekly-checkin/${trackerId}/${goalPlanId}/current?${stringifiedParams}`
    : `/api/weekly-checkin/${trackerId}/${goalPlanId}/current`;
};

export const weeklyCheckinGenerateForDate = async (
  trackerId: string,
  goalPlanId: string,
  params?: WeeklyCheckinGenerateForDateParams,
  options?: RequestInit,
): Promise<weeklyCheckinGenerateForDateResponse> => {
  const res = await fetch(getWeeklyCheckinGenerateForDateUrl(trackerId, goalPlanId, params), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: weeklyCheckinGenerateForDateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as weeklyCheckinGenerateForDateResponse;
};

export const getWeeklyCheckinGenerateForDateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof weeklyCheckinGenerateForDate>>,
    TError,
    { trackerId: string; goalPlanId: string; params?: WeeklyCheckinGenerateForDateParams },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof weeklyCheckinGenerateForDate>>,
  TError,
  { trackerId: string; goalPlanId: string; params?: WeeklyCheckinGenerateForDateParams },
  TContext
> => {
  const mutationKey = ['weeklyCheckinGenerateForDate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof weeklyCheckinGenerateForDate>>,
    { trackerId: string; goalPlanId: string; params?: WeeklyCheckinGenerateForDateParams }
  > = (props) => {
    const { trackerId, goalPlanId, params } = props ?? {};

    return weeklyCheckinGenerateForDate(trackerId, goalPlanId, params, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type WeeklyCheckinGenerateForDateMutationResult = NonNullable<
  Awaited<ReturnType<typeof weeklyCheckinGenerateForDate>>
>;

export type WeeklyCheckinGenerateForDateMutationError = unknown;

export const useWeeklyCheckinGenerateForDate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof weeklyCheckinGenerateForDate>>,
      TError,
      { trackerId: string; goalPlanId: string; params?: WeeklyCheckinGenerateForDateParams },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof weeklyCheckinGenerateForDate>>,
  TError,
  { trackerId: string; goalPlanId: string; params?: WeeklyCheckinGenerateForDateParams },
  TContext
> => {
  return useMutation(getWeeklyCheckinGenerateForDateMutationOptions(options), queryClient);
};
export type weeklyCheckinFindAllResponse200 = {
  data: Blob;
  status: 200;
};

export type weeklyCheckinFindAllResponseSuccess = weeklyCheckinFindAllResponse200 & {
  headers: Headers;
};
export type weeklyCheckinFindAllResponse = weeklyCheckinFindAllResponseSuccess;

export const getWeeklyCheckinFindAllUrl = (
  trackerId: string,
  goalPlanId: string,
  params?: WeeklyCheckinFindAllParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/weekly-checkin/${trackerId}/${goalPlanId}?${stringifiedParams}`
    : `/api/weekly-checkin/${trackerId}/${goalPlanId}`;
};

export const weeklyCheckinFindAll = async (
  trackerId: string,
  goalPlanId: string,
  params?: WeeklyCheckinFindAllParams,
  options?: RequestInit,
): Promise<weeklyCheckinFindAllResponse> => {
  const res = await fetch(getWeeklyCheckinFindAllUrl(trackerId, goalPlanId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: weeklyCheckinFindAllResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as weeklyCheckinFindAllResponse;
};

export const getWeeklyCheckinFindAllQueryKey = (
  trackerId: string,
  goalPlanId: string,
  params?: WeeklyCheckinFindAllParams,
) => {
  return [`/api/weekly-checkin/${trackerId}/${goalPlanId}`, ...(params ? [params] : [])] as const;
};

export const getWeeklyCheckinFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof weeklyCheckinFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  params?: WeeklyCheckinFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof weeklyCheckinFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getWeeklyCheckinFindAllQueryKey(trackerId, goalPlanId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof weeklyCheckinFindAll>>> = ({ signal }) =>
    weeklyCheckinFindAll(trackerId, goalPlanId, params, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(trackerId && goalPlanId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof weeklyCheckinFindAll>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type WeeklyCheckinFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof weeklyCheckinFindAll>>
>;
export type WeeklyCheckinFindAllQueryError = unknown;

export function useWeeklyCheckinFindAll<
  TData = Awaited<ReturnType<typeof weeklyCheckinFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  params: undefined | WeeklyCheckinFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof weeklyCheckinFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof weeklyCheckinFindAll>>,
          TError,
          Awaited<ReturnType<typeof weeklyCheckinFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useWeeklyCheckinFindAll<
  TData = Awaited<ReturnType<typeof weeklyCheckinFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  params?: WeeklyCheckinFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof weeklyCheckinFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof weeklyCheckinFindAll>>,
          TError,
          Awaited<ReturnType<typeof weeklyCheckinFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useWeeklyCheckinFindAll<
  TData = Awaited<ReturnType<typeof weeklyCheckinFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  params?: WeeklyCheckinFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof weeklyCheckinFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useWeeklyCheckinFindAll<
  TData = Awaited<ReturnType<typeof weeklyCheckinFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  params?: WeeklyCheckinFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof weeklyCheckinFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getWeeklyCheckinFindAllQueryOptions(trackerId, goalPlanId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
