/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { UpsertNutritionProfileRequestDto } from '../model';

export type nutritionProfileFindResponse200 = {
  data: Blob;
  status: 200;
};

export type nutritionProfileFindResponseSuccess = nutritionProfileFindResponse200 & {
  headers: Headers;
};
export type nutritionProfileFindResponse = nutritionProfileFindResponseSuccess;

export const getNutritionProfileFindUrl = (trackerId: string) => {
  return `/api/nutrition-profile/${trackerId}`;
};

export const nutritionProfileFind = async (
  trackerId: string,
  options?: RequestInit,
): Promise<nutritionProfileFindResponse> => {
  const res = await fetch(getNutritionProfileFindUrl(trackerId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: nutritionProfileFindResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as nutritionProfileFindResponse;
};

export const getNutritionProfileFindQueryKey = (trackerId: string) => {
  return [`/api/nutrition-profile/${trackerId}`] as const;
};

export const getNutritionProfileFindQueryOptions = <
  TData = Awaited<ReturnType<typeof nutritionProfileFind>>,
  TError = unknown,
>(
  trackerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof nutritionProfileFind>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getNutritionProfileFindQueryKey(trackerId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof nutritionProfileFind>>> = ({ signal }) =>
    nutritionProfileFind(trackerId, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof nutritionProfileFind>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type NutritionProfileFindQueryResult = NonNullable<
  Awaited<ReturnType<typeof nutritionProfileFind>>
>;
export type NutritionProfileFindQueryError = unknown;

export function useNutritionProfileFind<
  TData = Awaited<ReturnType<typeof nutritionProfileFind>>,
  TError = unknown,
>(
  trackerId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof nutritionProfileFind>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof nutritionProfileFind>>,
          TError,
          Awaited<ReturnType<typeof nutritionProfileFind>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useNutritionProfileFind<
  TData = Awaited<ReturnType<typeof nutritionProfileFind>>,
  TError = unknown,
>(
  trackerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof nutritionProfileFind>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof nutritionProfileFind>>,
          TError,
          Awaited<ReturnType<typeof nutritionProfileFind>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useNutritionProfileFind<
  TData = Awaited<ReturnType<typeof nutritionProfileFind>>,
  TError = unknown,
>(
  trackerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof nutritionProfileFind>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useNutritionProfileFind<
  TData = Awaited<ReturnType<typeof nutritionProfileFind>>,
  TError = unknown,
>(
  trackerId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof nutritionProfileFind>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getNutritionProfileFindQueryOptions(trackerId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type nutritionProfileUpsertResponse200 = {
  data: Blob;
  status: 200;
};

export type nutritionProfileUpsertResponseSuccess = nutritionProfileUpsertResponse200 & {
  headers: Headers;
};
export type nutritionProfileUpsertResponse = nutritionProfileUpsertResponseSuccess;

export const getNutritionProfileUpsertUrl = (trackerId: string) => {
  return `/api/nutrition-profile/${trackerId}`;
};

export const nutritionProfileUpsert = async (
  trackerId: string,
  upsertNutritionProfileRequestDto: UpsertNutritionProfileRequestDto,
  options?: RequestInit,
): Promise<nutritionProfileUpsertResponse> => {
  const res = await fetch(getNutritionProfileUpsertUrl(trackerId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(upsertNutritionProfileRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: nutritionProfileUpsertResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as nutritionProfileUpsertResponse;
};

export const getNutritionProfileUpsertMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof nutritionProfileUpsert>>,
    TError,
    { trackerId: string; data: UpsertNutritionProfileRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof nutritionProfileUpsert>>,
  TError,
  { trackerId: string; data: UpsertNutritionProfileRequestDto },
  TContext
> => {
  const mutationKey = ['nutritionProfileUpsert'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof nutritionProfileUpsert>>,
    { trackerId: string; data: UpsertNutritionProfileRequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return nutritionProfileUpsert(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type NutritionProfileUpsertMutationResult = NonNullable<
  Awaited<ReturnType<typeof nutritionProfileUpsert>>
>;
export type NutritionProfileUpsertMutationBody = UpsertNutritionProfileRequestDto;
export type NutritionProfileUpsertMutationError = unknown;

export const useNutritionProfileUpsert = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof nutritionProfileUpsert>>,
      TError,
      { trackerId: string; data: UpsertNutritionProfileRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof nutritionProfileUpsert>>,
  TError,
  { trackerId: string; data: UpsertNutritionProfileRequestDto },
  TContext
> => {
  return useMutation(getNutritionProfileUpsertMutationOptions(options), queryClient);
};
