/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { NavbarFavouriteAddBody, NavbarFavouriteRemoveParams } from '../model';

export type navbarFavouriteGetResponse200 = {
  data: Blob;
  status: 200;
};

export type navbarFavouriteGetResponseSuccess = navbarFavouriteGetResponse200 & {
  headers: Headers;
};
export type navbarFavouriteGetResponse = navbarFavouriteGetResponseSuccess;

export const getNavbarFavouriteGetUrl = () => {
  return `/api/users/favourites`;
};

export const navbarFavouriteGet = async (
  options?: RequestInit,
): Promise<navbarFavouriteGetResponse> => {
  const res = await fetch(getNavbarFavouriteGetUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: navbarFavouriteGetResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as navbarFavouriteGetResponse;
};

export const getNavbarFavouriteGetQueryKey = () => {
  return [`/api/users/favourites`] as const;
};

export const getNavbarFavouriteGetQueryOptions = <
  TData = Awaited<ReturnType<typeof navbarFavouriteGet>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof navbarFavouriteGet>>, TError, TData>>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getNavbarFavouriteGetQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof navbarFavouriteGet>>> = ({ signal }) =>
    navbarFavouriteGet({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof navbarFavouriteGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type NavbarFavouriteGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof navbarFavouriteGet>>
>;
export type NavbarFavouriteGetQueryError = unknown;

export function useNavbarFavouriteGet<
  TData = Awaited<ReturnType<typeof navbarFavouriteGet>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof navbarFavouriteGet>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof navbarFavouriteGet>>,
          TError,
          Awaited<ReturnType<typeof navbarFavouriteGet>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useNavbarFavouriteGet<
  TData = Awaited<ReturnType<typeof navbarFavouriteGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof navbarFavouriteGet>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof navbarFavouriteGet>>,
          TError,
          Awaited<ReturnType<typeof navbarFavouriteGet>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useNavbarFavouriteGet<
  TData = Awaited<ReturnType<typeof navbarFavouriteGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof navbarFavouriteGet>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useNavbarFavouriteGet<
  TData = Awaited<ReturnType<typeof navbarFavouriteGet>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof navbarFavouriteGet>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getNavbarFavouriteGetQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type navbarFavouriteReplaceResponse200 = {
  data: void;
  status: 200;
};

export type navbarFavouriteReplaceResponseSuccess = navbarFavouriteReplaceResponse200 & {
  headers: Headers;
};
export type navbarFavouriteReplaceResponse = navbarFavouriteReplaceResponseSuccess;

export const getNavbarFavouriteReplaceUrl = () => {
  return `/api/users/favourites`;
};

export const navbarFavouriteReplace = async (
  navbarFavouriteReplaceBody: string[],
  options?: RequestInit,
): Promise<navbarFavouriteReplaceResponse> => {
  const res = await fetch(getNavbarFavouriteReplaceUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(navbarFavouriteReplaceBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: navbarFavouriteReplaceResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as navbarFavouriteReplaceResponse;
};

export const getNavbarFavouriteReplaceMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof navbarFavouriteReplace>>,
    TError,
    { data: string[] },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof navbarFavouriteReplace>>,
  TError,
  { data: string[] },
  TContext
> => {
  const mutationKey = ['navbarFavouriteReplace'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof navbarFavouriteReplace>>,
    { data: string[] }
  > = (props) => {
    const { data } = props ?? {};

    return navbarFavouriteReplace(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type NavbarFavouriteReplaceMutationResult = NonNullable<
  Awaited<ReturnType<typeof navbarFavouriteReplace>>
>;
export type NavbarFavouriteReplaceMutationBody = string[];
export type NavbarFavouriteReplaceMutationError = unknown;

export const useNavbarFavouriteReplace = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof navbarFavouriteReplace>>,
      TError,
      { data: string[] },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof navbarFavouriteReplace>>,
  TError,
  { data: string[] },
  TContext
> => {
  return useMutation(getNavbarFavouriteReplaceMutationOptions(options), queryClient);
};
export type navbarFavouriteAddResponse200 = {
  data: void;
  status: 200;
};

export type navbarFavouriteAddResponseSuccess = navbarFavouriteAddResponse200 & {
  headers: Headers;
};
export type navbarFavouriteAddResponse = navbarFavouriteAddResponseSuccess;

export const getNavbarFavouriteAddUrl = () => {
  return `/api/users/favourites`;
};

export const navbarFavouriteAdd = async (
  navbarFavouriteAddBody: NavbarFavouriteAddBody,
  options?: RequestInit,
): Promise<navbarFavouriteAddResponse> => {
  const res = await fetch(getNavbarFavouriteAddUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(navbarFavouriteAddBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: navbarFavouriteAddResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as navbarFavouriteAddResponse;
};

export const getNavbarFavouriteAddMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof navbarFavouriteAdd>>,
    TError,
    { data: NavbarFavouriteAddBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof navbarFavouriteAdd>>,
  TError,
  { data: NavbarFavouriteAddBody },
  TContext
> => {
  const mutationKey = ['navbarFavouriteAdd'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof navbarFavouriteAdd>>,
    { data: NavbarFavouriteAddBody }
  > = (props) => {
    const { data } = props ?? {};

    return navbarFavouriteAdd(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type NavbarFavouriteAddMutationResult = NonNullable<
  Awaited<ReturnType<typeof navbarFavouriteAdd>>
>;
export type NavbarFavouriteAddMutationBody = NavbarFavouriteAddBody;
export type NavbarFavouriteAddMutationError = unknown;

export const useNavbarFavouriteAdd = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof navbarFavouriteAdd>>,
      TError,
      { data: NavbarFavouriteAddBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof navbarFavouriteAdd>>,
  TError,
  { data: NavbarFavouriteAddBody },
  TContext
> => {
  return useMutation(getNavbarFavouriteAddMutationOptions(options), queryClient);
};
export type navbarFavouriteRemoveResponse200 = {
  data: void;
  status: 200;
};

export type navbarFavouriteRemoveResponseSuccess = navbarFavouriteRemoveResponse200 & {
  headers: Headers;
};
export type navbarFavouriteRemoveResponse = navbarFavouriteRemoveResponseSuccess;

export const getNavbarFavouriteRemoveUrl = (params: NavbarFavouriteRemoveParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/users/favourites?${stringifiedParams}`
    : `/api/users/favourites`;
};

export const navbarFavouriteRemove = async (
  params: NavbarFavouriteRemoveParams,
  options?: RequestInit,
): Promise<navbarFavouriteRemoveResponse> => {
  const res = await fetch(getNavbarFavouriteRemoveUrl(params), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: navbarFavouriteRemoveResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as navbarFavouriteRemoveResponse;
};

export const getNavbarFavouriteRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof navbarFavouriteRemove>>,
    TError,
    { params: NavbarFavouriteRemoveParams },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof navbarFavouriteRemove>>,
  TError,
  { params: NavbarFavouriteRemoveParams },
  TContext
> => {
  const mutationKey = ['navbarFavouriteRemove'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof navbarFavouriteRemove>>,
    { params: NavbarFavouriteRemoveParams }
  > = (props) => {
    const { params } = props ?? {};

    return navbarFavouriteRemove(params, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type NavbarFavouriteRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof navbarFavouriteRemove>>
>;

export type NavbarFavouriteRemoveMutationError = unknown;

export const useNavbarFavouriteRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof navbarFavouriteRemove>>,
      TError,
      { params: NavbarFavouriteRemoveParams },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof navbarFavouriteRemove>>,
  TError,
  { params: NavbarFavouriteRemoveParams },
  TContext
> => {
  return useMutation(getNavbarFavouriteRemoveMutationOptions(options), queryClient);
};
