/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  KanbanCardFindBoardSnapshotParams,
  KanbanCardMoveStageRequestDto,
  KanbanCardReorderRequestDto,
  KanbanCardUploadImageBody,
  KanbanCardUpsertRequestDto,
  KanbanChecklistItemReorderRequestDto,
  KanbanChecklistItemToggleRequestDto,
  KanbanChecklistItemUpsertRequestDto,
} from '../model';

export type kanbanCardFindBoardSnapshotResponse200 = {
  data: Blob;
  status: 200;
};

export type kanbanCardFindBoardSnapshotResponseSuccess = kanbanCardFindBoardSnapshotResponse200 & {
  headers: Headers;
};
export type kanbanCardFindBoardSnapshotResponse = kanbanCardFindBoardSnapshotResponseSuccess;

export const getKanbanCardFindBoardSnapshotUrl = (
  trackerId: string,
  boardId: string,
  params?: KanbanCardFindBoardSnapshotParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/kanban-card/${trackerId}/${boardId}?${stringifiedParams}`
    : `/api/kanban-card/${trackerId}/${boardId}`;
};

export const kanbanCardFindBoardSnapshot = async (
  trackerId: string,
  boardId: string,
  params?: KanbanCardFindBoardSnapshotParams,
  options?: RequestInit,
): Promise<kanbanCardFindBoardSnapshotResponse> => {
  const res = await fetch(getKanbanCardFindBoardSnapshotUrl(trackerId, boardId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanCardFindBoardSnapshotResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanCardFindBoardSnapshotResponse;
};

export const getKanbanCardFindBoardSnapshotQueryKey = (
  trackerId: string,
  boardId: string,
  params?: KanbanCardFindBoardSnapshotParams,
) => {
  return [`/api/kanban-card/${trackerId}/${boardId}`, ...(params ? [params] : [])] as const;
};

export const getKanbanCardFindBoardSnapshotQueryOptions = <
  TData = Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>,
  TError = unknown,
>(
  trackerId: string,
  boardId: string,
  params?: KanbanCardFindBoardSnapshotParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getKanbanCardFindBoardSnapshotQueryKey(trackerId, boardId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>> = ({
    signal,
  }) => kanbanCardFindBoardSnapshot(trackerId, boardId, params, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(trackerId && boardId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type KanbanCardFindBoardSnapshotQueryResult = NonNullable<
  Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>
>;
export type KanbanCardFindBoardSnapshotQueryError = unknown;

export function useKanbanCardFindBoardSnapshot<
  TData = Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>,
  TError = unknown,
>(
  trackerId: string,
  boardId: string,
  params: undefined | KanbanCardFindBoardSnapshotParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>,
          TError,
          Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useKanbanCardFindBoardSnapshot<
  TData = Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>,
  TError = unknown,
>(
  trackerId: string,
  boardId: string,
  params?: KanbanCardFindBoardSnapshotParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>,
          TError,
          Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useKanbanCardFindBoardSnapshot<
  TData = Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>,
  TError = unknown,
>(
  trackerId: string,
  boardId: string,
  params?: KanbanCardFindBoardSnapshotParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useKanbanCardFindBoardSnapshot<
  TData = Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>,
  TError = unknown,
>(
  trackerId: string,
  boardId: string,
  params?: KanbanCardFindBoardSnapshotParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof kanbanCardFindBoardSnapshot>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getKanbanCardFindBoardSnapshotQueryOptions(
    trackerId,
    boardId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type kanbanCardCreateResponse200 = {
  data: Blob;
  status: 200;
};

export type kanbanCardCreateResponseSuccess = kanbanCardCreateResponse200 & {
  headers: Headers;
};
export type kanbanCardCreateResponse = kanbanCardCreateResponseSuccess;

export const getKanbanCardCreateUrl = (trackerId: string, boardId: string) => {
  return `/api/kanban-card/${trackerId}/${boardId}`;
};

export const kanbanCardCreate = async (
  trackerId: string,
  boardId: string,
  kanbanCardUpsertRequestDto: KanbanCardUpsertRequestDto,
  options?: RequestInit,
): Promise<kanbanCardCreateResponse> => {
  const res = await fetch(getKanbanCardCreateUrl(trackerId, boardId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(kanbanCardUpsertRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanCardCreateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanCardCreateResponse;
};

export const getKanbanCardCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof kanbanCardCreate>>,
    TError,
    { trackerId: string; boardId: string; data: KanbanCardUpsertRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof kanbanCardCreate>>,
  TError,
  { trackerId: string; boardId: string; data: KanbanCardUpsertRequestDto },
  TContext
> => {
  const mutationKey = ['kanbanCardCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof kanbanCardCreate>>,
    { trackerId: string; boardId: string; data: KanbanCardUpsertRequestDto }
  > = (props) => {
    const { trackerId, boardId, data } = props ?? {};

    return kanbanCardCreate(trackerId, boardId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type KanbanCardCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof kanbanCardCreate>>
>;
export type KanbanCardCreateMutationBody = KanbanCardUpsertRequestDto;
export type KanbanCardCreateMutationError = unknown;

export const useKanbanCardCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof kanbanCardCreate>>,
      TError,
      { trackerId: string; boardId: string; data: KanbanCardUpsertRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof kanbanCardCreate>>,
  TError,
  { trackerId: string; boardId: string; data: KanbanCardUpsertRequestDto },
  TContext
> => {
  return useMutation(getKanbanCardCreateMutationOptions(options), queryClient);
};
export type kanbanCardUploadImageResponse200 = {
  data: Blob;
  status: 200;
};

export type kanbanCardUploadImageResponseSuccess = kanbanCardUploadImageResponse200 & {
  headers: Headers;
};
export type kanbanCardUploadImageResponse = kanbanCardUploadImageResponseSuccess;

export const getKanbanCardUploadImageUrl = (trackerId: string, boardId: string, cardId: string) => {
  return `/api/kanban-card/${trackerId}/${boardId}/${cardId}/image`;
};

export const kanbanCardUploadImage = async (
  trackerId: string,
  boardId: string,
  cardId: string,
  kanbanCardUploadImageBody: KanbanCardUploadImageBody,
  options?: RequestInit,
): Promise<kanbanCardUploadImageResponse> => {
  const res = await fetch(getKanbanCardUploadImageUrl(trackerId, boardId, cardId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(kanbanCardUploadImageBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanCardUploadImageResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanCardUploadImageResponse;
};

export const getKanbanCardUploadImageMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof kanbanCardUploadImage>>,
    TError,
    { trackerId: string; boardId: string; cardId: string; data: KanbanCardUploadImageBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof kanbanCardUploadImage>>,
  TError,
  { trackerId: string; boardId: string; cardId: string; data: KanbanCardUploadImageBody },
  TContext
> => {
  const mutationKey = ['kanbanCardUploadImage'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof kanbanCardUploadImage>>,
    { trackerId: string; boardId: string; cardId: string; data: KanbanCardUploadImageBody }
  > = (props) => {
    const { trackerId, boardId, cardId, data } = props ?? {};

    return kanbanCardUploadImage(trackerId, boardId, cardId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type KanbanCardUploadImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof kanbanCardUploadImage>>
>;
export type KanbanCardUploadImageMutationBody = KanbanCardUploadImageBody;
export type KanbanCardUploadImageMutationError = unknown;

export const useKanbanCardUploadImage = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof kanbanCardUploadImage>>,
      TError,
      { trackerId: string; boardId: string; cardId: string; data: KanbanCardUploadImageBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof kanbanCardUploadImage>>,
  TError,
  { trackerId: string; boardId: string; cardId: string; data: KanbanCardUploadImageBody },
  TContext
> => {
  return useMutation(getKanbanCardUploadImageMutationOptions(options), queryClient);
};
export type kanbanCardDeleteImageResponse200 = {
  data: void;
  status: 200;
};

export type kanbanCardDeleteImageResponseSuccess = kanbanCardDeleteImageResponse200 & {
  headers: Headers;
};
export type kanbanCardDeleteImageResponse = kanbanCardDeleteImageResponseSuccess;

export const getKanbanCardDeleteImageUrl = (trackerId: string, boardId: string, cardId: string) => {
  return `/api/kanban-card/${trackerId}/${boardId}/${cardId}/image`;
};

export const kanbanCardDeleteImage = async (
  trackerId: string,
  boardId: string,
  cardId: string,
  options?: RequestInit,
): Promise<kanbanCardDeleteImageResponse> => {
  const res = await fetch(getKanbanCardDeleteImageUrl(trackerId, boardId, cardId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanCardDeleteImageResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanCardDeleteImageResponse;
};

export const getKanbanCardDeleteImageMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof kanbanCardDeleteImage>>,
    TError,
    { trackerId: string; boardId: string; cardId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof kanbanCardDeleteImage>>,
  TError,
  { trackerId: string; boardId: string; cardId: string },
  TContext
> => {
  const mutationKey = ['kanbanCardDeleteImage'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof kanbanCardDeleteImage>>,
    { trackerId: string; boardId: string; cardId: string }
  > = (props) => {
    const { trackerId, boardId, cardId } = props ?? {};

    return kanbanCardDeleteImage(trackerId, boardId, cardId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type KanbanCardDeleteImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof kanbanCardDeleteImage>>
>;

export type KanbanCardDeleteImageMutationError = unknown;

export const useKanbanCardDeleteImage = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof kanbanCardDeleteImage>>,
      TError,
      { trackerId: string; boardId: string; cardId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof kanbanCardDeleteImage>>,
  TError,
  { trackerId: string; boardId: string; cardId: string },
  TContext
> => {
  return useMutation(getKanbanCardDeleteImageMutationOptions(options), queryClient);
};
export type kanbanChecklistItemCreateResponse200 = {
  data: Blob;
  status: 200;
};

export type kanbanChecklistItemCreateResponseSuccess = kanbanChecklistItemCreateResponse200 & {
  headers: Headers;
};
export type kanbanChecklistItemCreateResponse = kanbanChecklistItemCreateResponseSuccess;

export const getKanbanChecklistItemCreateUrl = (
  trackerId: string,
  boardId: string,
  cardId: string,
) => {
  return `/api/kanban-card/${trackerId}/${boardId}/${cardId}/checklist`;
};

export const kanbanChecklistItemCreate = async (
  trackerId: string,
  boardId: string,
  cardId: string,
  kanbanChecklistItemUpsertRequestDto: KanbanChecklistItemUpsertRequestDto,
  options?: RequestInit,
): Promise<kanbanChecklistItemCreateResponse> => {
  const res = await fetch(getKanbanChecklistItemCreateUrl(trackerId, boardId, cardId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(kanbanChecklistItemUpsertRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanChecklistItemCreateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanChecklistItemCreateResponse;
};

export const getKanbanChecklistItemCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof kanbanChecklistItemCreate>>,
    TError,
    {
      trackerId: string;
      boardId: string;
      cardId: string;
      data: KanbanChecklistItemUpsertRequestDto;
    },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof kanbanChecklistItemCreate>>,
  TError,
  { trackerId: string; boardId: string; cardId: string; data: KanbanChecklistItemUpsertRequestDto },
  TContext
> => {
  const mutationKey = ['kanbanChecklistItemCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof kanbanChecklistItemCreate>>,
    {
      trackerId: string;
      boardId: string;
      cardId: string;
      data: KanbanChecklistItemUpsertRequestDto;
    }
  > = (props) => {
    const { trackerId, boardId, cardId, data } = props ?? {};

    return kanbanChecklistItemCreate(trackerId, boardId, cardId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type KanbanChecklistItemCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof kanbanChecklistItemCreate>>
>;
export type KanbanChecklistItemCreateMutationBody = KanbanChecklistItemUpsertRequestDto;
export type KanbanChecklistItemCreateMutationError = unknown;

export const useKanbanChecklistItemCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof kanbanChecklistItemCreate>>,
      TError,
      {
        trackerId: string;
        boardId: string;
        cardId: string;
        data: KanbanChecklistItemUpsertRequestDto;
      },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof kanbanChecklistItemCreate>>,
  TError,
  { trackerId: string; boardId: string; cardId: string; data: KanbanChecklistItemUpsertRequestDto },
  TContext
> => {
  return useMutation(getKanbanChecklistItemCreateMutationOptions(options), queryClient);
};
export type kanbanCardMoveResponse200 = {
  data: Blob;
  status: 200;
};

export type kanbanCardMoveResponseSuccess = kanbanCardMoveResponse200 & {
  headers: Headers;
};
export type kanbanCardMoveResponse = kanbanCardMoveResponseSuccess;

export const getKanbanCardMoveUrl = (trackerId: string, cardId: string) => {
  return `/api/kanban-card/${trackerId}/${cardId}/move`;
};

export const kanbanCardMove = async (
  trackerId: string,
  cardId: string,
  kanbanCardMoveStageRequestDto: KanbanCardMoveStageRequestDto,
  options?: RequestInit,
): Promise<kanbanCardMoveResponse> => {
  const res = await fetch(getKanbanCardMoveUrl(trackerId, cardId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(kanbanCardMoveStageRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanCardMoveResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanCardMoveResponse;
};

export const getKanbanCardMoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof kanbanCardMove>>,
    TError,
    { trackerId: string; cardId: string; data: KanbanCardMoveStageRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof kanbanCardMove>>,
  TError,
  { trackerId: string; cardId: string; data: KanbanCardMoveStageRequestDto },
  TContext
> => {
  const mutationKey = ['kanbanCardMove'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof kanbanCardMove>>,
    { trackerId: string; cardId: string; data: KanbanCardMoveStageRequestDto }
  > = (props) => {
    const { trackerId, cardId, data } = props ?? {};

    return kanbanCardMove(trackerId, cardId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type KanbanCardMoveMutationResult = NonNullable<Awaited<ReturnType<typeof kanbanCardMove>>>;
export type KanbanCardMoveMutationBody = KanbanCardMoveStageRequestDto;
export type KanbanCardMoveMutationError = unknown;

export const useKanbanCardMove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof kanbanCardMove>>,
      TError,
      { trackerId: string; cardId: string; data: KanbanCardMoveStageRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof kanbanCardMove>>,
  TError,
  { trackerId: string; cardId: string; data: KanbanCardMoveStageRequestDto },
  TContext
> => {
  return useMutation(getKanbanCardMoveMutationOptions(options), queryClient);
};
export type kanbanCardFindByIdResponse200 = {
  data: Blob;
  status: 200;
};

export type kanbanCardFindByIdResponseSuccess = kanbanCardFindByIdResponse200 & {
  headers: Headers;
};
export type kanbanCardFindByIdResponse = kanbanCardFindByIdResponseSuccess;

export const getKanbanCardFindByIdUrl = (trackerId: string, boardId: string, cardId: string) => {
  return `/api/kanban-card/${trackerId}/${boardId}/${cardId}`;
};

export const kanbanCardFindById = async (
  trackerId: string,
  boardId: string,
  cardId: string,
  options?: RequestInit,
): Promise<kanbanCardFindByIdResponse> => {
  const res = await fetch(getKanbanCardFindByIdUrl(trackerId, boardId, cardId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanCardFindByIdResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanCardFindByIdResponse;
};

export const getKanbanCardFindByIdQueryKey = (
  trackerId: string,
  boardId: string,
  cardId: string,
) => {
  return [`/api/kanban-card/${trackerId}/${boardId}/${cardId}`] as const;
};

export const getKanbanCardFindByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof kanbanCardFindById>>,
  TError = unknown,
>(
  trackerId: string,
  boardId: string,
  cardId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof kanbanCardFindById>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getKanbanCardFindByIdQueryKey(trackerId, boardId, cardId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof kanbanCardFindById>>> = ({ signal }) =>
    kanbanCardFindById(trackerId, boardId, cardId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(trackerId && boardId && cardId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof kanbanCardFindById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type KanbanCardFindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof kanbanCardFindById>>
>;
export type KanbanCardFindByIdQueryError = unknown;

export function useKanbanCardFindById<
  TData = Awaited<ReturnType<typeof kanbanCardFindById>>,
  TError = unknown,
>(
  trackerId: string,
  boardId: string,
  cardId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof kanbanCardFindById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof kanbanCardFindById>>,
          TError,
          Awaited<ReturnType<typeof kanbanCardFindById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useKanbanCardFindById<
  TData = Awaited<ReturnType<typeof kanbanCardFindById>>,
  TError = unknown,
>(
  trackerId: string,
  boardId: string,
  cardId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof kanbanCardFindById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof kanbanCardFindById>>,
          TError,
          Awaited<ReturnType<typeof kanbanCardFindById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useKanbanCardFindById<
  TData = Awaited<ReturnType<typeof kanbanCardFindById>>,
  TError = unknown,
>(
  trackerId: string,
  boardId: string,
  cardId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof kanbanCardFindById>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useKanbanCardFindById<
  TData = Awaited<ReturnType<typeof kanbanCardFindById>>,
  TError = unknown,
>(
  trackerId: string,
  boardId: string,
  cardId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof kanbanCardFindById>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getKanbanCardFindByIdQueryOptions(trackerId, boardId, cardId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type kanbanCardDeleteResponse200 = {
  data: void;
  status: 200;
};

export type kanbanCardDeleteResponseSuccess = kanbanCardDeleteResponse200 & {
  headers: Headers;
};
export type kanbanCardDeleteResponse = kanbanCardDeleteResponseSuccess;

export const getKanbanCardDeleteUrl = (trackerId: string, boardId: string, cardId: string) => {
  return `/api/kanban-card/${trackerId}/${boardId}/${cardId}`;
};

export const kanbanCardDelete = async (
  trackerId: string,
  boardId: string,
  cardId: string,
  options?: RequestInit,
): Promise<kanbanCardDeleteResponse> => {
  const res = await fetch(getKanbanCardDeleteUrl(trackerId, boardId, cardId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanCardDeleteResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanCardDeleteResponse;
};

export const getKanbanCardDeleteMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof kanbanCardDelete>>,
    TError,
    { trackerId: string; boardId: string; cardId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof kanbanCardDelete>>,
  TError,
  { trackerId: string; boardId: string; cardId: string },
  TContext
> => {
  const mutationKey = ['kanbanCardDelete'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof kanbanCardDelete>>,
    { trackerId: string; boardId: string; cardId: string }
  > = (props) => {
    const { trackerId, boardId, cardId } = props ?? {};

    return kanbanCardDelete(trackerId, boardId, cardId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type KanbanCardDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof kanbanCardDelete>>
>;

export type KanbanCardDeleteMutationError = unknown;

export const useKanbanCardDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof kanbanCardDelete>>,
      TError,
      { trackerId: string; boardId: string; cardId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof kanbanCardDelete>>,
  TError,
  { trackerId: string; boardId: string; cardId: string },
  TContext
> => {
  return useMutation(getKanbanCardDeleteMutationOptions(options), queryClient);
};
export type kanbanCardUpdateResponse200 = {
  data: Blob;
  status: 200;
};

export type kanbanCardUpdateResponseSuccess = kanbanCardUpdateResponse200 & {
  headers: Headers;
};
export type kanbanCardUpdateResponse = kanbanCardUpdateResponseSuccess;

export const getKanbanCardUpdateUrl = (trackerId: string, boardId: string, cardId: string) => {
  return `/api/kanban-card/${trackerId}/${boardId}/${cardId}`;
};

export const kanbanCardUpdate = async (
  trackerId: string,
  boardId: string,
  cardId: string,
  kanbanCardUpsertRequestDto: KanbanCardUpsertRequestDto,
  options?: RequestInit,
): Promise<kanbanCardUpdateResponse> => {
  const res = await fetch(getKanbanCardUpdateUrl(trackerId, boardId, cardId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(kanbanCardUpsertRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanCardUpdateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanCardUpdateResponse;
};

export const getKanbanCardUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof kanbanCardUpdate>>,
    TError,
    { trackerId: string; boardId: string; cardId: string; data: KanbanCardUpsertRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof kanbanCardUpdate>>,
  TError,
  { trackerId: string; boardId: string; cardId: string; data: KanbanCardUpsertRequestDto },
  TContext
> => {
  const mutationKey = ['kanbanCardUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof kanbanCardUpdate>>,
    { trackerId: string; boardId: string; cardId: string; data: KanbanCardUpsertRequestDto }
  > = (props) => {
    const { trackerId, boardId, cardId, data } = props ?? {};

    return kanbanCardUpdate(trackerId, boardId, cardId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type KanbanCardUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof kanbanCardUpdate>>
>;
export type KanbanCardUpdateMutationBody = KanbanCardUpsertRequestDto;
export type KanbanCardUpdateMutationError = unknown;

export const useKanbanCardUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof kanbanCardUpdate>>,
      TError,
      { trackerId: string; boardId: string; cardId: string; data: KanbanCardUpsertRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof kanbanCardUpdate>>,
  TError,
  { trackerId: string; boardId: string; cardId: string; data: KanbanCardUpsertRequestDto },
  TContext
> => {
  return useMutation(getKanbanCardUpdateMutationOptions(options), queryClient);
};
export type kanbanChecklistItemDeleteResponse200 = {
  data: void;
  status: 200;
};

export type kanbanChecklistItemDeleteResponseSuccess = kanbanChecklistItemDeleteResponse200 & {
  headers: Headers;
};
export type kanbanChecklistItemDeleteResponse = kanbanChecklistItemDeleteResponseSuccess;

export const getKanbanChecklistItemDeleteUrl = (
  trackerId: string,
  boardId: string,
  cardId: string,
  itemId: string,
) => {
  return `/api/kanban-card/${trackerId}/${boardId}/${cardId}/checklist/${itemId}`;
};

export const kanbanChecklistItemDelete = async (
  trackerId: string,
  boardId: string,
  cardId: string,
  itemId: string,
  options?: RequestInit,
): Promise<kanbanChecklistItemDeleteResponse> => {
  const res = await fetch(getKanbanChecklistItemDeleteUrl(trackerId, boardId, cardId, itemId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanChecklistItemDeleteResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanChecklistItemDeleteResponse;
};

export const getKanbanChecklistItemDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof kanbanChecklistItemDelete>>,
    TError,
    { trackerId: string; boardId: string; cardId: string; itemId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof kanbanChecklistItemDelete>>,
  TError,
  { trackerId: string; boardId: string; cardId: string; itemId: string },
  TContext
> => {
  const mutationKey = ['kanbanChecklistItemDelete'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof kanbanChecklistItemDelete>>,
    { trackerId: string; boardId: string; cardId: string; itemId: string }
  > = (props) => {
    const { trackerId, boardId, cardId, itemId } = props ?? {};

    return kanbanChecklistItemDelete(trackerId, boardId, cardId, itemId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type KanbanChecklistItemDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof kanbanChecklistItemDelete>>
>;

export type KanbanChecklistItemDeleteMutationError = unknown;

export const useKanbanChecklistItemDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof kanbanChecklistItemDelete>>,
      TError,
      { trackerId: string; boardId: string; cardId: string; itemId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof kanbanChecklistItemDelete>>,
  TError,
  { trackerId: string; boardId: string; cardId: string; itemId: string },
  TContext
> => {
  return useMutation(getKanbanChecklistItemDeleteMutationOptions(options), queryClient);
};
export type kanbanChecklistItemUpdateResponse200 = {
  data: Blob;
  status: 200;
};

export type kanbanChecklistItemUpdateResponseSuccess = kanbanChecklistItemUpdateResponse200 & {
  headers: Headers;
};
export type kanbanChecklistItemUpdateResponse = kanbanChecklistItemUpdateResponseSuccess;

export const getKanbanChecklistItemUpdateUrl = (
  trackerId: string,
  boardId: string,
  cardId: string,
  itemId: string,
) => {
  return `/api/kanban-card/${trackerId}/${boardId}/${cardId}/checklist/${itemId}`;
};

export const kanbanChecklistItemUpdate = async (
  trackerId: string,
  boardId: string,
  cardId: string,
  itemId: string,
  kanbanChecklistItemUpsertRequestDto: KanbanChecklistItemUpsertRequestDto,
  options?: RequestInit,
): Promise<kanbanChecklistItemUpdateResponse> => {
  const res = await fetch(getKanbanChecklistItemUpdateUrl(trackerId, boardId, cardId, itemId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(kanbanChecklistItemUpsertRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanChecklistItemUpdateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanChecklistItemUpdateResponse;
};

export const getKanbanChecklistItemUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof kanbanChecklistItemUpdate>>,
    TError,
    {
      trackerId: string;
      boardId: string;
      cardId: string;
      itemId: string;
      data: KanbanChecklistItemUpsertRequestDto;
    },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof kanbanChecklistItemUpdate>>,
  TError,
  {
    trackerId: string;
    boardId: string;
    cardId: string;
    itemId: string;
    data: KanbanChecklistItemUpsertRequestDto;
  },
  TContext
> => {
  const mutationKey = ['kanbanChecklistItemUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof kanbanChecklistItemUpdate>>,
    {
      trackerId: string;
      boardId: string;
      cardId: string;
      itemId: string;
      data: KanbanChecklistItemUpsertRequestDto;
    }
  > = (props) => {
    const { trackerId, boardId, cardId, itemId, data } = props ?? {};

    return kanbanChecklistItemUpdate(trackerId, boardId, cardId, itemId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type KanbanChecklistItemUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof kanbanChecklistItemUpdate>>
>;
export type KanbanChecklistItemUpdateMutationBody = KanbanChecklistItemUpsertRequestDto;
export type KanbanChecklistItemUpdateMutationError = unknown;

export const useKanbanChecklistItemUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof kanbanChecklistItemUpdate>>,
      TError,
      {
        trackerId: string;
        boardId: string;
        cardId: string;
        itemId: string;
        data: KanbanChecklistItemUpsertRequestDto;
      },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof kanbanChecklistItemUpdate>>,
  TError,
  {
    trackerId: string;
    boardId: string;
    cardId: string;
    itemId: string;
    data: KanbanChecklistItemUpsertRequestDto;
  },
  TContext
> => {
  return useMutation(getKanbanChecklistItemUpdateMutationOptions(options), queryClient);
};
export type kanbanChecklistItemToggleResponse200 = {
  data: Blob;
  status: 200;
};

export type kanbanChecklistItemToggleResponseSuccess = kanbanChecklistItemToggleResponse200 & {
  headers: Headers;
};
export type kanbanChecklistItemToggleResponse = kanbanChecklistItemToggleResponseSuccess;

export const getKanbanChecklistItemToggleUrl = (
  trackerId: string,
  boardId: string,
  cardId: string,
  itemId: string,
) => {
  return `/api/kanban-card/${trackerId}/${boardId}/${cardId}/checklist/${itemId}/toggle`;
};

export const kanbanChecklistItemToggle = async (
  trackerId: string,
  boardId: string,
  cardId: string,
  itemId: string,
  kanbanChecklistItemToggleRequestDto: KanbanChecklistItemToggleRequestDto,
  options?: RequestInit,
): Promise<kanbanChecklistItemToggleResponse> => {
  const res = await fetch(getKanbanChecklistItemToggleUrl(trackerId, boardId, cardId, itemId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(kanbanChecklistItemToggleRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanChecklistItemToggleResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanChecklistItemToggleResponse;
};

export const getKanbanChecklistItemToggleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof kanbanChecklistItemToggle>>,
    TError,
    {
      trackerId: string;
      boardId: string;
      cardId: string;
      itemId: string;
      data: KanbanChecklistItemToggleRequestDto;
    },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof kanbanChecklistItemToggle>>,
  TError,
  {
    trackerId: string;
    boardId: string;
    cardId: string;
    itemId: string;
    data: KanbanChecklistItemToggleRequestDto;
  },
  TContext
> => {
  const mutationKey = ['kanbanChecklistItemToggle'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof kanbanChecklistItemToggle>>,
    {
      trackerId: string;
      boardId: string;
      cardId: string;
      itemId: string;
      data: KanbanChecklistItemToggleRequestDto;
    }
  > = (props) => {
    const { trackerId, boardId, cardId, itemId, data } = props ?? {};

    return kanbanChecklistItemToggle(trackerId, boardId, cardId, itemId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type KanbanChecklistItemToggleMutationResult = NonNullable<
  Awaited<ReturnType<typeof kanbanChecklistItemToggle>>
>;
export type KanbanChecklistItemToggleMutationBody = KanbanChecklistItemToggleRequestDto;
export type KanbanChecklistItemToggleMutationError = unknown;

export const useKanbanChecklistItemToggle = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof kanbanChecklistItemToggle>>,
      TError,
      {
        trackerId: string;
        boardId: string;
        cardId: string;
        itemId: string;
        data: KanbanChecklistItemToggleRequestDto;
      },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof kanbanChecklistItemToggle>>,
  TError,
  {
    trackerId: string;
    boardId: string;
    cardId: string;
    itemId: string;
    data: KanbanChecklistItemToggleRequestDto;
  },
  TContext
> => {
  return useMutation(getKanbanChecklistItemToggleMutationOptions(options), queryClient);
};
export type kanbanChecklistItemReorderResponse200 = {
  data: Blob;
  status: 200;
};

export type kanbanChecklistItemReorderResponseSuccess = kanbanChecklistItemReorderResponse200 & {
  headers: Headers;
};
export type kanbanChecklistItemReorderResponse = kanbanChecklistItemReorderResponseSuccess;

export const getKanbanChecklistItemReorderUrl = (
  trackerId: string,
  boardId: string,
  cardId: string,
) => {
  return `/api/kanban-card/${trackerId}/${boardId}/${cardId}/checklist/reorder`;
};

export const kanbanChecklistItemReorder = async (
  trackerId: string,
  boardId: string,
  cardId: string,
  kanbanChecklistItemReorderRequestDto: KanbanChecklistItemReorderRequestDto,
  options?: RequestInit,
): Promise<kanbanChecklistItemReorderResponse> => {
  const res = await fetch(getKanbanChecklistItemReorderUrl(trackerId, boardId, cardId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(kanbanChecklistItemReorderRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanChecklistItemReorderResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanChecklistItemReorderResponse;
};

export const getKanbanChecklistItemReorderMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof kanbanChecklistItemReorder>>,
    TError,
    {
      trackerId: string;
      boardId: string;
      cardId: string;
      data: KanbanChecklistItemReorderRequestDto;
    },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof kanbanChecklistItemReorder>>,
  TError,
  {
    trackerId: string;
    boardId: string;
    cardId: string;
    data: KanbanChecklistItemReorderRequestDto;
  },
  TContext
> => {
  const mutationKey = ['kanbanChecklistItemReorder'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof kanbanChecklistItemReorder>>,
    {
      trackerId: string;
      boardId: string;
      cardId: string;
      data: KanbanChecklistItemReorderRequestDto;
    }
  > = (props) => {
    const { trackerId, boardId, cardId, data } = props ?? {};

    return kanbanChecklistItemReorder(trackerId, boardId, cardId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type KanbanChecklistItemReorderMutationResult = NonNullable<
  Awaited<ReturnType<typeof kanbanChecklistItemReorder>>
>;
export type KanbanChecklistItemReorderMutationBody = KanbanChecklistItemReorderRequestDto;
export type KanbanChecklistItemReorderMutationError = unknown;

export const useKanbanChecklistItemReorder = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof kanbanChecklistItemReorder>>,
      TError,
      {
        trackerId: string;
        boardId: string;
        cardId: string;
        data: KanbanChecklistItemReorderRequestDto;
      },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof kanbanChecklistItemReorder>>,
  TError,
  {
    trackerId: string;
    boardId: string;
    cardId: string;
    data: KanbanChecklistItemReorderRequestDto;
  },
  TContext
> => {
  return useMutation(getKanbanChecklistItemReorderMutationOptions(options), queryClient);
};
export type kanbanCardReorderResponse200 = {
  data: void;
  status: 200;
};

export type kanbanCardReorderResponseSuccess = kanbanCardReorderResponse200 & {
  headers: Headers;
};
export type kanbanCardReorderResponse = kanbanCardReorderResponseSuccess;

export const getKanbanCardReorderUrl = (trackerId: string, boardId: string) => {
  return `/api/kanban-card/${trackerId}/${boardId}/reorder`;
};

export const kanbanCardReorder = async (
  trackerId: string,
  boardId: string,
  kanbanCardReorderRequestDto: KanbanCardReorderRequestDto,
  options?: RequestInit,
): Promise<kanbanCardReorderResponse> => {
  const res = await fetch(getKanbanCardReorderUrl(trackerId, boardId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(kanbanCardReorderRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: kanbanCardReorderResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as kanbanCardReorderResponse;
};

export const getKanbanCardReorderMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof kanbanCardReorder>>,
    TError,
    { trackerId: string; boardId: string; data: KanbanCardReorderRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof kanbanCardReorder>>,
  TError,
  { trackerId: string; boardId: string; data: KanbanCardReorderRequestDto },
  TContext
> => {
  const mutationKey = ['kanbanCardReorder'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof kanbanCardReorder>>,
    { trackerId: string; boardId: string; data: KanbanCardReorderRequestDto }
  > = (props) => {
    const { trackerId, boardId, data } = props ?? {};

    return kanbanCardReorder(trackerId, boardId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type KanbanCardReorderMutationResult = NonNullable<
  Awaited<ReturnType<typeof kanbanCardReorder>>
>;
export type KanbanCardReorderMutationBody = KanbanCardReorderRequestDto;
export type KanbanCardReorderMutationError = unknown;

export const useKanbanCardReorder = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof kanbanCardReorder>>,
      TError,
      { trackerId: string; boardId: string; data: KanbanCardReorderRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof kanbanCardReorder>>,
  TError,
  { trackerId: string; boardId: string; data: KanbanCardReorderRequestDto },
  TContext
> => {
  return useMutation(getKanbanCardReorderMutationOptions(options), queryClient);
};
