/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

export type widgetItemFindAllResponse200 = {
  data: Blob;
  status: 200;
};

export type widgetItemFindAllResponseSuccess = widgetItemFindAllResponse200 & {
  headers: Headers;
};
export type widgetItemFindAllResponse = widgetItemFindAllResponseSuccess;

export const getWidgetItemFindAllUrl = (widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER') => {
  return `/api/widget-items/${widgetType}`;
};

export const widgetItemFindAll = async (
  widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER',
  options?: RequestInit,
): Promise<widgetItemFindAllResponse> => {
  const res = await fetch(getWidgetItemFindAllUrl(widgetType), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: widgetItemFindAllResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as widgetItemFindAllResponse;
};

export const getWidgetItemFindAllQueryKey = (widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER') => {
  return [`/api/widget-items/${widgetType}`] as const;
};

export const getWidgetItemFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof widgetItemFindAll>>,
  TError = unknown,
>(
  widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER',
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof widgetItemFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getWidgetItemFindAllQueryKey(widgetType);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof widgetItemFindAll>>> = ({ signal }) =>
    widgetItemFindAll(widgetType, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!widgetType, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof widgetItemFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WidgetItemFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof widgetItemFindAll>>
>;
export type WidgetItemFindAllQueryError = unknown;

export function useWidgetItemFindAll<
  TData = Awaited<ReturnType<typeof widgetItemFindAll>>,
  TError = unknown,
>(
  widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER',
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof widgetItemFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof widgetItemFindAll>>,
          TError,
          Awaited<ReturnType<typeof widgetItemFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useWidgetItemFindAll<
  TData = Awaited<ReturnType<typeof widgetItemFindAll>>,
  TError = unknown,
>(
  widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER',
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof widgetItemFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof widgetItemFindAll>>,
          TError,
          Awaited<ReturnType<typeof widgetItemFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useWidgetItemFindAll<
  TData = Awaited<ReturnType<typeof widgetItemFindAll>>,
  TError = unknown,
>(
  widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER',
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof widgetItemFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useWidgetItemFindAll<
  TData = Awaited<ReturnType<typeof widgetItemFindAll>>,
  TError = unknown,
>(
  widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER',
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof widgetItemFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getWidgetItemFindAllQueryOptions(widgetType, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type widgetItemReplaceResponse200 = {
  data: Blob;
  status: 200;
};

export type widgetItemReplaceResponseSuccess = widgetItemReplaceResponse200 & {
  headers: Headers;
};
export type widgetItemReplaceResponse = widgetItemReplaceResponseSuccess;

export const getWidgetItemReplaceUrl = (widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER') => {
  return `/api/widget-items/${widgetType}`;
};

export const widgetItemReplace = async (
  widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER',
  widgetItemReplaceBody: string[],
  options?: RequestInit,
): Promise<widgetItemReplaceResponse> => {
  const res = await fetch(getWidgetItemReplaceUrl(widgetType), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(widgetItemReplaceBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: widgetItemReplaceResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as widgetItemReplaceResponse;
};

export const getWidgetItemReplaceMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof widgetItemReplace>>,
    TError,
    { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; data: string[] },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof widgetItemReplace>>,
  TError,
  { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; data: string[] },
  TContext
> => {
  const mutationKey = ['widgetItemReplace'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof widgetItemReplace>>,
    { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; data: string[] }
  > = (props) => {
    const { widgetType, data } = props ?? {};

    return widgetItemReplace(widgetType, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type WidgetItemReplaceMutationResult = NonNullable<
  Awaited<ReturnType<typeof widgetItemReplace>>
>;
export type WidgetItemReplaceMutationBody = string[];
export type WidgetItemReplaceMutationError = unknown;

export const useWidgetItemReplace = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof widgetItemReplace>>,
      TError,
      { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; data: string[] },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof widgetItemReplace>>,
  TError,
  { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; data: string[] },
  TContext
> => {
  return useMutation(getWidgetItemReplaceMutationOptions(options), queryClient);
};
export type widgetItemAddResponse200 = {
  data: void;
  status: 200;
};

export type widgetItemAddResponseSuccess = widgetItemAddResponse200 & {
  headers: Headers;
};
export type widgetItemAddResponse = widgetItemAddResponseSuccess;

export const getWidgetItemAddUrl = (
  widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER',
  entityId: string,
) => {
  return `/api/widget-items/${widgetType}/${entityId}`;
};

export const widgetItemAdd = async (
  widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER',
  entityId: string,
  options?: RequestInit,
): Promise<widgetItemAddResponse> => {
  const res = await fetch(getWidgetItemAddUrl(widgetType, entityId), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: widgetItemAddResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as widgetItemAddResponse;
};

export const getWidgetItemAddMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof widgetItemAdd>>,
    TError,
    { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; entityId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof widgetItemAdd>>,
  TError,
  { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; entityId: string },
  TContext
> => {
  const mutationKey = ['widgetItemAdd'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof widgetItemAdd>>,
    { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; entityId: string }
  > = (props) => {
    const { widgetType, entityId } = props ?? {};

    return widgetItemAdd(widgetType, entityId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type WidgetItemAddMutationResult = NonNullable<Awaited<ReturnType<typeof widgetItemAdd>>>;

export type WidgetItemAddMutationError = unknown;

export const useWidgetItemAdd = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof widgetItemAdd>>,
      TError,
      { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; entityId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof widgetItemAdd>>,
  TError,
  { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; entityId: string },
  TContext
> => {
  return useMutation(getWidgetItemAddMutationOptions(options), queryClient);
};
export type widgetItemRemoveResponse200 = {
  data: void;
  status: 200;
};

export type widgetItemRemoveResponseSuccess = widgetItemRemoveResponse200 & {
  headers: Headers;
};
export type widgetItemRemoveResponse = widgetItemRemoveResponseSuccess;

export const getWidgetItemRemoveUrl = (
  widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER',
  entityId: string,
) => {
  return `/api/widget-items/${widgetType}/${entityId}`;
};

export const widgetItemRemove = async (
  widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER',
  entityId: string,
  options?: RequestInit,
): Promise<widgetItemRemoveResponse> => {
  const res = await fetch(getWidgetItemRemoveUrl(widgetType, entityId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: widgetItemRemoveResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as widgetItemRemoveResponse;
};

export const getWidgetItemRemoveMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof widgetItemRemove>>,
    TError,
    { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; entityId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof widgetItemRemove>>,
  TError,
  { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; entityId: string },
  TContext
> => {
  const mutationKey = ['widgetItemRemove'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof widgetItemRemove>>,
    { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; entityId: string }
  > = (props) => {
    const { widgetType, entityId } = props ?? {};

    return widgetItemRemove(widgetType, entityId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type WidgetItemRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof widgetItemRemove>>
>;

export type WidgetItemRemoveMutationError = unknown;

export const useWidgetItemRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof widgetItemRemove>>,
      TError,
      { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; entityId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof widgetItemRemove>>,
  TError,
  { widgetType: 'INSTITUTION' | 'EXPENSE_TRACKER'; entityId: string },
  TContext
> => {
  return useMutation(getWidgetItemRemoveMutationOptions(options), queryClient);
};
