/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ExpenseTrackerAccessRequestFindAllByTrackerParams,
  ExpenseTrackerAccessRequestFindAllMineParams,
  InviteUserRequestDto,
} from '../model';

export type expenseTrackerAccessRequestFindAllByTrackerResponse200 = {
  data: Blob;
  status: 200;
};

export type expenseTrackerAccessRequestFindAllByTrackerResponseSuccess =
  expenseTrackerAccessRequestFindAllByTrackerResponse200 & {
    headers: Headers;
  };
export type expenseTrackerAccessRequestFindAllByTrackerResponse =
  expenseTrackerAccessRequestFindAllByTrackerResponseSuccess;

export const getExpenseTrackerAccessRequestFindAllByTrackerUrl = (
  trackerId: string,
  params?: ExpenseTrackerAccessRequestFindAllByTrackerParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/expense-trackers/${trackerId}/access-requests?${stringifiedParams}`
    : `/api/expense-trackers/${trackerId}/access-requests`;
};

export const expenseTrackerAccessRequestFindAllByTracker = async (
  trackerId: string,
  params?: ExpenseTrackerAccessRequestFindAllByTrackerParams,
  options?: RequestInit,
): Promise<expenseTrackerAccessRequestFindAllByTrackerResponse> => {
  const res = await fetch(getExpenseTrackerAccessRequestFindAllByTrackerUrl(trackerId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: expenseTrackerAccessRequestFindAllByTrackerResponse['data'] = body
    ? JSON.parse(body)
    : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as expenseTrackerAccessRequestFindAllByTrackerResponse;
};

export const getExpenseTrackerAccessRequestFindAllByTrackerQueryKey = (
  trackerId: string,
  params?: ExpenseTrackerAccessRequestFindAllByTrackerParams,
) => {
  return [
    `/api/expense-trackers/${trackerId}/access-requests`,
    ...(params ? [params] : []),
  ] as const;
};

export const getExpenseTrackerAccessRequestFindAllByTrackerQueryOptions = <
  TData = Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>,
  TError = unknown,
>(
  trackerId: string,
  params?: ExpenseTrackerAccessRequestFindAllByTrackerParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getExpenseTrackerAccessRequestFindAllByTrackerQueryKey(trackerId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>
  > = ({ signal }) =>
    expenseTrackerAccessRequestFindAllByTracker(trackerId, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExpenseTrackerAccessRequestFindAllByTrackerQueryResult = NonNullable<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>
>;
export type ExpenseTrackerAccessRequestFindAllByTrackerQueryError = unknown;

export function useExpenseTrackerAccessRequestFindAllByTracker<
  TData = Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>,
  TError = unknown,
>(
  trackerId: string,
  params: undefined | ExpenseTrackerAccessRequestFindAllByTrackerParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>,
          TError,
          Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useExpenseTrackerAccessRequestFindAllByTracker<
  TData = Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>,
  TError = unknown,
>(
  trackerId: string,
  params?: ExpenseTrackerAccessRequestFindAllByTrackerParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>,
          TError,
          Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useExpenseTrackerAccessRequestFindAllByTracker<
  TData = Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>,
  TError = unknown,
>(
  trackerId: string,
  params?: ExpenseTrackerAccessRequestFindAllByTrackerParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useExpenseTrackerAccessRequestFindAllByTracker<
  TData = Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>,
  TError = unknown,
>(
  trackerId: string,
  params?: ExpenseTrackerAccessRequestFindAllByTrackerParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllByTracker>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getExpenseTrackerAccessRequestFindAllByTrackerQueryOptions(
    trackerId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type expenseTrackerAccessRequestCreateResponse200 = {
  data: Blob;
  status: 200;
};

export type expenseTrackerAccessRequestCreateResponseSuccess =
  expenseTrackerAccessRequestCreateResponse200 & {
    headers: Headers;
  };
export type expenseTrackerAccessRequestCreateResponse =
  expenseTrackerAccessRequestCreateResponseSuccess;

export const getExpenseTrackerAccessRequestCreateUrl = (trackerId: string) => {
  return `/api/expense-trackers/${trackerId}/access-requests`;
};

export const expenseTrackerAccessRequestCreate = async (
  trackerId: string,
  options?: RequestInit,
): Promise<expenseTrackerAccessRequestCreateResponse> => {
  const res = await fetch(getExpenseTrackerAccessRequestCreateUrl(trackerId), {
    ...options,
    method: 'POST',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: expenseTrackerAccessRequestCreateResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as expenseTrackerAccessRequestCreateResponse;
};

export const getExpenseTrackerAccessRequestCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestCreate>>,
    TError,
    { trackerId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestCreate>>,
  TError,
  { trackerId: string },
  TContext
> => {
  const mutationKey = ['expenseTrackerAccessRequestCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestCreate>>,
    { trackerId: string }
  > = (props) => {
    const { trackerId } = props ?? {};

    return expenseTrackerAccessRequestCreate(trackerId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExpenseTrackerAccessRequestCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestCreate>>
>;

export type ExpenseTrackerAccessRequestCreateMutationError = unknown;

export const useExpenseTrackerAccessRequestCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof expenseTrackerAccessRequestCreate>>,
      TError,
      { trackerId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestCreate>>,
  TError,
  { trackerId: string },
  TContext
> => {
  return useMutation(getExpenseTrackerAccessRequestCreateMutationOptions(options), queryClient);
};
export type expenseTrackerAccessRequestInviteResponse200 = {
  data: Blob;
  status: 200;
};

export type expenseTrackerAccessRequestInviteResponseSuccess =
  expenseTrackerAccessRequestInviteResponse200 & {
    headers: Headers;
  };
export type expenseTrackerAccessRequestInviteResponse =
  expenseTrackerAccessRequestInviteResponseSuccess;

export const getExpenseTrackerAccessRequestInviteUrl = (trackerId: string) => {
  return `/api/expense-trackers/${trackerId}/access-requests/invite`;
};

export const expenseTrackerAccessRequestInvite = async (
  trackerId: string,
  inviteUserRequestDto: InviteUserRequestDto,
  options?: RequestInit,
): Promise<expenseTrackerAccessRequestInviteResponse> => {
  const res = await fetch(getExpenseTrackerAccessRequestInviteUrl(trackerId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(inviteUserRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: expenseTrackerAccessRequestInviteResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as expenseTrackerAccessRequestInviteResponse;
};

export const getExpenseTrackerAccessRequestInviteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestInvite>>,
    TError,
    { trackerId: string; data: InviteUserRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestInvite>>,
  TError,
  { trackerId: string; data: InviteUserRequestDto },
  TContext
> => {
  const mutationKey = ['expenseTrackerAccessRequestInvite'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestInvite>>,
    { trackerId: string; data: InviteUserRequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return expenseTrackerAccessRequestInvite(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExpenseTrackerAccessRequestInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestInvite>>
>;
export type ExpenseTrackerAccessRequestInviteMutationBody = InviteUserRequestDto;
export type ExpenseTrackerAccessRequestInviteMutationError = unknown;

export const useExpenseTrackerAccessRequestInvite = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof expenseTrackerAccessRequestInvite>>,
      TError,
      { trackerId: string; data: InviteUserRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestInvite>>,
  TError,
  { trackerId: string; data: InviteUserRequestDto },
  TContext
> => {
  return useMutation(getExpenseTrackerAccessRequestInviteMutationOptions(options), queryClient);
};
export type expenseTrackerAccessRequestRejectResponse200 = {
  data: Blob;
  status: 200;
};

export type expenseTrackerAccessRequestRejectResponseSuccess =
  expenseTrackerAccessRequestRejectResponse200 & {
    headers: Headers;
  };
export type expenseTrackerAccessRequestRejectResponse =
  expenseTrackerAccessRequestRejectResponseSuccess;

export const getExpenseTrackerAccessRequestRejectUrl = (requestId: string) => {
  return `/api/expense-trackers/access-requests/${requestId}/reject`;
};

export const expenseTrackerAccessRequestReject = async (
  requestId: string,
  options?: RequestInit,
): Promise<expenseTrackerAccessRequestRejectResponse> => {
  const res = await fetch(getExpenseTrackerAccessRequestRejectUrl(requestId), {
    ...options,
    method: 'PATCH',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: expenseTrackerAccessRequestRejectResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as expenseTrackerAccessRequestRejectResponse;
};

export const getExpenseTrackerAccessRequestRejectMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestReject>>,
    TError,
    { requestId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestReject>>,
  TError,
  { requestId: string },
  TContext
> => {
  const mutationKey = ['expenseTrackerAccessRequestReject'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestReject>>,
    { requestId: string }
  > = (props) => {
    const { requestId } = props ?? {};

    return expenseTrackerAccessRequestReject(requestId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExpenseTrackerAccessRequestRejectMutationResult = NonNullable<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestReject>>
>;

export type ExpenseTrackerAccessRequestRejectMutationError = unknown;

export const useExpenseTrackerAccessRequestReject = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof expenseTrackerAccessRequestReject>>,
      TError,
      { requestId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestReject>>,
  TError,
  { requestId: string },
  TContext
> => {
  return useMutation(getExpenseTrackerAccessRequestRejectMutationOptions(options), queryClient);
};
export type expenseTrackerAccessRequestCancelResponse200 = {
  data: void;
  status: 200;
};

export type expenseTrackerAccessRequestCancelResponseSuccess =
  expenseTrackerAccessRequestCancelResponse200 & {
    headers: Headers;
  };
export type expenseTrackerAccessRequestCancelResponse =
  expenseTrackerAccessRequestCancelResponseSuccess;

export const getExpenseTrackerAccessRequestCancelUrl = (requestId: string) => {
  return `/api/expense-trackers/access-requests/${requestId}/cancel`;
};

export const expenseTrackerAccessRequestCancel = async (
  requestId: string,
  options?: RequestInit,
): Promise<expenseTrackerAccessRequestCancelResponse> => {
  const res = await fetch(getExpenseTrackerAccessRequestCancelUrl(requestId), {
    ...options,
    method: 'PATCH',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: expenseTrackerAccessRequestCancelResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as expenseTrackerAccessRequestCancelResponse;
};

export const getExpenseTrackerAccessRequestCancelMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestCancel>>,
    TError,
    { requestId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestCancel>>,
  TError,
  { requestId: string },
  TContext
> => {
  const mutationKey = ['expenseTrackerAccessRequestCancel'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestCancel>>,
    { requestId: string }
  > = (props) => {
    const { requestId } = props ?? {};

    return expenseTrackerAccessRequestCancel(requestId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExpenseTrackerAccessRequestCancelMutationResult = NonNullable<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestCancel>>
>;

export type ExpenseTrackerAccessRequestCancelMutationError = unknown;

export const useExpenseTrackerAccessRequestCancel = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof expenseTrackerAccessRequestCancel>>,
      TError,
      { requestId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestCancel>>,
  TError,
  { requestId: string },
  TContext
> => {
  return useMutation(getExpenseTrackerAccessRequestCancelMutationOptions(options), queryClient);
};
export type expenseTrackerAccessRequestApproveResponse200 = {
  data: Blob;
  status: 200;
};

export type expenseTrackerAccessRequestApproveResponseSuccess =
  expenseTrackerAccessRequestApproveResponse200 & {
    headers: Headers;
  };
export type expenseTrackerAccessRequestApproveResponse =
  expenseTrackerAccessRequestApproveResponseSuccess;

export const getExpenseTrackerAccessRequestApproveUrl = (requestId: string) => {
  return `/api/expense-trackers/access-requests/${requestId}/approve`;
};

export const expenseTrackerAccessRequestApprove = async (
  requestId: string,
  options?: RequestInit,
): Promise<expenseTrackerAccessRequestApproveResponse> => {
  const res = await fetch(getExpenseTrackerAccessRequestApproveUrl(requestId), {
    ...options,
    method: 'PATCH',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: expenseTrackerAccessRequestApproveResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as expenseTrackerAccessRequestApproveResponse;
};

export const getExpenseTrackerAccessRequestApproveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestApprove>>,
    TError,
    { requestId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestApprove>>,
  TError,
  { requestId: string },
  TContext
> => {
  const mutationKey = ['expenseTrackerAccessRequestApprove'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestApprove>>,
    { requestId: string }
  > = (props) => {
    const { requestId } = props ?? {};

    return expenseTrackerAccessRequestApprove(requestId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExpenseTrackerAccessRequestApproveMutationResult = NonNullable<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestApprove>>
>;

export type ExpenseTrackerAccessRequestApproveMutationError = unknown;

export const useExpenseTrackerAccessRequestApprove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof expenseTrackerAccessRequestApprove>>,
      TError,
      { requestId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestApprove>>,
  TError,
  { requestId: string },
  TContext
> => {
  return useMutation(getExpenseTrackerAccessRequestApproveMutationOptions(options), queryClient);
};
export type expenseTrackerAccessRequestAcceptResponse200 = {
  data: Blob;
  status: 200;
};

export type expenseTrackerAccessRequestAcceptResponseSuccess =
  expenseTrackerAccessRequestAcceptResponse200 & {
    headers: Headers;
  };
export type expenseTrackerAccessRequestAcceptResponse =
  expenseTrackerAccessRequestAcceptResponseSuccess;

export const getExpenseTrackerAccessRequestAcceptUrl = (requestId: string) => {
  return `/api/expense-trackers/access-requests/${requestId}/accept`;
};

export const expenseTrackerAccessRequestAccept = async (
  requestId: string,
  options?: RequestInit,
): Promise<expenseTrackerAccessRequestAcceptResponse> => {
  const res = await fetch(getExpenseTrackerAccessRequestAcceptUrl(requestId), {
    ...options,
    method: 'PATCH',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: expenseTrackerAccessRequestAcceptResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as expenseTrackerAccessRequestAcceptResponse;
};

export const getExpenseTrackerAccessRequestAcceptMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestAccept>>,
    TError,
    { requestId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestAccept>>,
  TError,
  { requestId: string },
  TContext
> => {
  const mutationKey = ['expenseTrackerAccessRequestAccept'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestAccept>>,
    { requestId: string }
  > = (props) => {
    const { requestId } = props ?? {};

    return expenseTrackerAccessRequestAccept(requestId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExpenseTrackerAccessRequestAcceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestAccept>>
>;

export type ExpenseTrackerAccessRequestAcceptMutationError = unknown;

export const useExpenseTrackerAccessRequestAccept = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof expenseTrackerAccessRequestAccept>>,
      TError,
      { requestId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestAccept>>,
  TError,
  { requestId: string },
  TContext
> => {
  return useMutation(getExpenseTrackerAccessRequestAcceptMutationOptions(options), queryClient);
};
export type expenseTrackerAccessRequestFindAllMineResponse200 = {
  data: Blob;
  status: 200;
};

export type expenseTrackerAccessRequestFindAllMineResponseSuccess =
  expenseTrackerAccessRequestFindAllMineResponse200 & {
    headers: Headers;
  };
export type expenseTrackerAccessRequestFindAllMineResponse =
  expenseTrackerAccessRequestFindAllMineResponseSuccess;

export const getExpenseTrackerAccessRequestFindAllMineUrl = (
  params?: ExpenseTrackerAccessRequestFindAllMineParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/expense-trackers/access-requests/mine?${stringifiedParams}`
    : `/api/expense-trackers/access-requests/mine`;
};

export const expenseTrackerAccessRequestFindAllMine = async (
  params?: ExpenseTrackerAccessRequestFindAllMineParams,
  options?: RequestInit,
): Promise<expenseTrackerAccessRequestFindAllMineResponse> => {
  const res = await fetch(getExpenseTrackerAccessRequestFindAllMineUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: expenseTrackerAccessRequestFindAllMineResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as expenseTrackerAccessRequestFindAllMineResponse;
};

export const getExpenseTrackerAccessRequestFindAllMineQueryKey = (
  params?: ExpenseTrackerAccessRequestFindAllMineParams,
) => {
  return [`/api/expense-trackers/access-requests/mine`, ...(params ? [params] : [])] as const;
};

export const getExpenseTrackerAccessRequestFindAllMineQueryOptions = <
  TData = Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>,
  TError = unknown,
>(
  params?: ExpenseTrackerAccessRequestFindAllMineParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getExpenseTrackerAccessRequestFindAllMineQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>
  > = ({ signal }) => expenseTrackerAccessRequestFindAllMine(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ExpenseTrackerAccessRequestFindAllMineQueryResult = NonNullable<
  Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>
>;
export type ExpenseTrackerAccessRequestFindAllMineQueryError = unknown;

export function useExpenseTrackerAccessRequestFindAllMine<
  TData = Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>,
  TError = unknown,
>(
  params: undefined | ExpenseTrackerAccessRequestFindAllMineParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>,
          TError,
          Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useExpenseTrackerAccessRequestFindAllMine<
  TData = Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>,
  TError = unknown,
>(
  params?: ExpenseTrackerAccessRequestFindAllMineParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>,
          TError,
          Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useExpenseTrackerAccessRequestFindAllMine<
  TData = Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>,
  TError = unknown,
>(
  params?: ExpenseTrackerAccessRequestFindAllMineParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useExpenseTrackerAccessRequestFindAllMine<
  TData = Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>,
  TError = unknown,
>(
  params?: ExpenseTrackerAccessRequestFindAllMineParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof expenseTrackerAccessRequestFindAllMine>>,
        TError,
        TData
      >
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getExpenseTrackerAccessRequestFindAllMineQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
