/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { NutritionDashboardParams } from '../model';

export type nutritionDashboardResponse200 = {
  data: Blob;
  status: 200;
};

export type nutritionDashboardResponseSuccess = nutritionDashboardResponse200 & {
  headers: Headers;
};
export type nutritionDashboardResponse = nutritionDashboardResponseSuccess;

export const getNutritionDashboardUrl = (trackerId: string, params?: NutritionDashboardParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/nutrition-dashboard/${trackerId}?${stringifiedParams}`
    : `/api/nutrition-dashboard/${trackerId}`;
};

export const nutritionDashboard = async (
  trackerId: string,
  params?: NutritionDashboardParams,
  options?: RequestInit,
): Promise<nutritionDashboardResponse> => {
  const res = await fetch(getNutritionDashboardUrl(trackerId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: nutritionDashboardResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as nutritionDashboardResponse;
};

export const getNutritionDashboardQueryKey = (
  trackerId: string,
  params?: NutritionDashboardParams,
) => {
  return [`/api/nutrition-dashboard/${trackerId}`, ...(params ? [params] : [])] as const;
};

export const getNutritionDashboardQueryOptions = <
  TData = Awaited<ReturnType<typeof nutritionDashboard>>,
  TError = unknown,
>(
  trackerId: string,
  params?: NutritionDashboardParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof nutritionDashboard>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getNutritionDashboardQueryKey(trackerId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof nutritionDashboard>>> = ({ signal }) =>
    nutritionDashboard(trackerId, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof nutritionDashboard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type NutritionDashboardQueryResult = NonNullable<
  Awaited<ReturnType<typeof nutritionDashboard>>
>;
export type NutritionDashboardQueryError = unknown;

export function useNutritionDashboard<
  TData = Awaited<ReturnType<typeof nutritionDashboard>>,
  TError = unknown,
>(
  trackerId: string,
  params: undefined | NutritionDashboardParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof nutritionDashboard>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof nutritionDashboard>>,
          TError,
          Awaited<ReturnType<typeof nutritionDashboard>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useNutritionDashboard<
  TData = Awaited<ReturnType<typeof nutritionDashboard>>,
  TError = unknown,
>(
  trackerId: string,
  params?: NutritionDashboardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof nutritionDashboard>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof nutritionDashboard>>,
          TError,
          Awaited<ReturnType<typeof nutritionDashboard>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useNutritionDashboard<
  TData = Awaited<ReturnType<typeof nutritionDashboard>>,
  TError = unknown,
>(
  trackerId: string,
  params?: NutritionDashboardParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof nutritionDashboard>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useNutritionDashboard<
  TData = Awaited<ReturnType<typeof nutritionDashboard>>,
  TError = unknown,
>(
  trackerId: string,
  params?: NutritionDashboardParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof nutritionDashboard>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getNutritionDashboardQueryOptions(trackerId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type nutritionSummaryResponse200 = {
  data: Blob;
  status: 200;
};

export type nutritionSummaryResponseSuccess = nutritionSummaryResponse200 & {
  headers: Headers;
};
export type nutritionSummaryResponse = nutritionSummaryResponseSuccess;

export const getNutritionSummaryUrl = (trackerId: string, goalPlanId: string) => {
  return `/api/nutrition-dashboard/${trackerId}/${goalPlanId}/summary`;
};

export const nutritionSummary = async (
  trackerId: string,
  goalPlanId: string,
  options?: RequestInit,
): Promise<nutritionSummaryResponse> => {
  const res = await fetch(getNutritionSummaryUrl(trackerId, goalPlanId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: nutritionSummaryResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as nutritionSummaryResponse;
};

export const getNutritionSummaryQueryKey = (trackerId: string, goalPlanId: string) => {
  return [`/api/nutrition-dashboard/${trackerId}/${goalPlanId}/summary`] as const;
};

export const getNutritionSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof nutritionSummary>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof nutritionSummary>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getNutritionSummaryQueryKey(trackerId, goalPlanId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof nutritionSummary>>> = ({ signal }) =>
    nutritionSummary(trackerId, goalPlanId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(trackerId && goalPlanId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof nutritionSummary>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type NutritionSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof nutritionSummary>>>;
export type NutritionSummaryQueryError = unknown;

export function useNutritionSummary<
  TData = Awaited<ReturnType<typeof nutritionSummary>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof nutritionSummary>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof nutritionSummary>>,
          TError,
          Awaited<ReturnType<typeof nutritionSummary>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useNutritionSummary<
  TData = Awaited<ReturnType<typeof nutritionSummary>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof nutritionSummary>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof nutritionSummary>>,
          TError,
          Awaited<ReturnType<typeof nutritionSummary>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useNutritionSummary<
  TData = Awaited<ReturnType<typeof nutritionSummary>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof nutritionSummary>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useNutritionSummary<
  TData = Awaited<ReturnType<typeof nutritionSummary>>,
  TError = unknown,
>(
  trackerId: string,
  goalPlanId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof nutritionSummary>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getNutritionSummaryQueryOptions(trackerId, goalPlanId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
