/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  ProfileFindAllPageableParams,
  UserPasswordChangeDto,
  UserProfileUpdateDto,
} from '../model';

export type profileUpdateResponse200 = {
  data: Blob;
  status: 200;
};

export type profileUpdateResponseSuccess = profileUpdateResponse200 & {
  headers: Headers;
};
export type profileUpdateResponse = profileUpdateResponseSuccess;

export const getProfileUpdateUrl = () => {
  return `/profile/update`;
};

export const profileUpdate = async (
  userProfileUpdateDto: UserProfileUpdateDto,
  options?: RequestInit,
): Promise<profileUpdateResponse> => {
  const res = await fetch(getProfileUpdateUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userProfileUpdateDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: profileUpdateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as profileUpdateResponse;
};

export const getProfileUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileUpdate>>,
    TError,
    { data: UserProfileUpdateDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileUpdate>>,
  TError,
  { data: UserProfileUpdateDto },
  TContext
> => {
  const mutationKey = ['profileUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileUpdate>>,
    { data: UserProfileUpdateDto }
  > = (props) => {
    const { data } = props ?? {};

    return profileUpdate(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof profileUpdate>>>;
export type ProfileUpdateMutationBody = UserProfileUpdateDto;
export type ProfileUpdateMutationError = unknown;

export const useProfileUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileUpdate>>,
      TError,
      { data: UserProfileUpdateDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileUpdate>>,
  TError,
  { data: UserProfileUpdateDto },
  TContext
> => {
  return useMutation(getProfileUpdateMutationOptions(options), queryClient);
};
export type profileChangePasswordResponse200 = {
  data: void;
  status: 200;
};

export type profileChangePasswordResponseSuccess = profileChangePasswordResponse200 & {
  headers: Headers;
};
export type profileChangePasswordResponse = profileChangePasswordResponseSuccess;

export const getProfileChangePasswordUrl = () => {
  return `/profile/change-password`;
};

export const profileChangePassword = async (
  userPasswordChangeDto: UserPasswordChangeDto,
  options?: RequestInit,
): Promise<profileChangePasswordResponse> => {
  const res = await fetch(getProfileChangePasswordUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userPasswordChangeDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: profileChangePasswordResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as profileChangePasswordResponse;
};

export const getProfileChangePasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileChangePassword>>,
    TError,
    { data: UserPasswordChangeDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileChangePassword>>,
  TError,
  { data: UserPasswordChangeDto },
  TContext
> => {
  const mutationKey = ['profileChangePassword'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileChangePassword>>,
    { data: UserPasswordChangeDto }
  > = (props) => {
    const { data } = props ?? {};

    return profileChangePassword(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileChangePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileChangePassword>>
>;
export type ProfileChangePasswordMutationBody = UserPasswordChangeDto;
export type ProfileChangePasswordMutationError = unknown;

export const useProfileChangePassword = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileChangePassword>>,
      TError,
      { data: UserPasswordChangeDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileChangePassword>>,
  TError,
  { data: UserPasswordChangeDto },
  TContext
> => {
  return useMutation(getProfileChangePasswordMutationOptions(options), queryClient);
};
export type profileFindAllPageableResponse200 = {
  data: Blob;
  status: 200;
};

export type profileFindAllPageableResponseSuccess = profileFindAllPageableResponse200 & {
  headers: Headers;
};
export type profileFindAllPageableResponse = profileFindAllPageableResponseSuccess;

export const getProfileFindAllPageableUrl = (params?: ProfileFindAllPageableParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/profile?${stringifiedParams}` : `/profile`;
};

export const profileFindAllPageable = async (
  params?: ProfileFindAllPageableParams,
  options?: RequestInit,
): Promise<profileFindAllPageableResponse> => {
  const res = await fetch(getProfileFindAllPageableUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: profileFindAllPageableResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as profileFindAllPageableResponse;
};

export const getProfileFindAllPageableQueryKey = (params?: ProfileFindAllPageableParams) => {
  return [`/profile`, ...(params ? [params] : [])] as const;
};

export const getProfileFindAllPageableQueryOptions = <
  TData = Awaited<ReturnType<typeof profileFindAllPageable>>,
  TError = unknown,
>(
  params?: ProfileFindAllPageableParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof profileFindAllPageable>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileFindAllPageableQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileFindAllPageable>>> = ({ signal }) =>
    profileFindAllPageable(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof profileFindAllPageable>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileFindAllPageableQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileFindAllPageable>>
>;
export type ProfileFindAllPageableQueryError = unknown;

export function useProfileFindAllPageable<
  TData = Awaited<ReturnType<typeof profileFindAllPageable>>,
  TError = unknown,
>(
  params: undefined | ProfileFindAllPageableParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof profileFindAllPageable>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileFindAllPageable>>,
          TError,
          Awaited<ReturnType<typeof profileFindAllPageable>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileFindAllPageable<
  TData = Awaited<ReturnType<typeof profileFindAllPageable>>,
  TError = unknown,
>(
  params?: ProfileFindAllPageableParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof profileFindAllPageable>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileFindAllPageable>>,
          TError,
          Awaited<ReturnType<typeof profileFindAllPageable>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileFindAllPageable<
  TData = Awaited<ReturnType<typeof profileFindAllPageable>>,
  TError = unknown,
>(
  params?: ProfileFindAllPageableParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof profileFindAllPageable>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileFindAllPageable<
  TData = Awaited<ReturnType<typeof profileFindAllPageable>>,
  TError = unknown,
>(
  params?: ProfileFindAllPageableParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof profileFindAllPageable>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileFindAllPageableQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type profileMeResponse200 = {
  data: Blob;
  status: 200;
};

export type profileMeResponseSuccess = profileMeResponse200 & {
  headers: Headers;
};
export type profileMeResponse = profileMeResponseSuccess;

export const getProfileMeUrl = () => {
  return `/profile/me`;
};

export const profileMe = async (options?: RequestInit): Promise<profileMeResponse> => {
  const res = await fetch(getProfileMeUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: profileMeResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as profileMeResponse;
};

export const getProfileMeQueryKey = () => {
  return [`/profile/me`] as const;
};

export const getProfileMeQueryOptions = <
  TData = Awaited<ReturnType<typeof profileMe>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileMe>>, TError, TData>>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getProfileMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof profileMe>>> = ({ signal }) =>
    profileMe({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof profileMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileMeQueryResult = NonNullable<Awaited<ReturnType<typeof profileMe>>>;
export type ProfileMeQueryError = unknown;

export function useProfileMe<TData = Awaited<ReturnType<typeof profileMe>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileMe>>,
          TError,
          Awaited<ReturnType<typeof profileMe>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileMe<TData = Awaited<ReturnType<typeof profileMe>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileMe>>,
          TError,
          Awaited<ReturnType<typeof profileMe>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useProfileMe<TData = Awaited<ReturnType<typeof profileMe>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileMe>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useProfileMe<TData = Awaited<ReturnType<typeof profileMe>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof profileMe>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getProfileMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type profileDeleteMeResponse200 = {
  data: void;
  status: 200;
};

export type profileDeleteMeResponseSuccess = profileDeleteMeResponse200 & {
  headers: Headers;
};
export type profileDeleteMeResponse = profileDeleteMeResponseSuccess;

export const getProfileDeleteMeUrl = () => {
  return `/profile/me`;
};

export const profileDeleteMe = async (options?: RequestInit): Promise<profileDeleteMeResponse> => {
  const res = await fetch(getProfileDeleteMeUrl(), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: profileDeleteMeResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as profileDeleteMeResponse;
};

export const getProfileDeleteMeMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileDeleteMe>>,
    TError,
    void,
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<Awaited<ReturnType<typeof profileDeleteMe>>, TError, void, TContext> => {
  const mutationKey = ['profileDeleteMe'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof profileDeleteMe>>, void> = () => {
    return profileDeleteMe(fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileDeleteMeMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileDeleteMe>>
>;

export type ProfileDeleteMeMutationError = unknown;

export const useProfileDeleteMe = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileDeleteMe>>,
      TError,
      void,
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof profileDeleteMe>>, TError, void, TContext> => {
  return useMutation(getProfileDeleteMeMutationOptions(options), queryClient);
};
