/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { UpsertDailyCheckinRequestDto } from '../model';

export type dailyCheckinUpsertResponse200 = {
  data: Blob;
  status: 200;
};

export type dailyCheckinUpsertResponseSuccess = dailyCheckinUpsertResponse200 & {
  headers: Headers;
};
export type dailyCheckinUpsertResponse = dailyCheckinUpsertResponseSuccess;

export const getDailyCheckinUpsertUrl = (trackerId: string) => {
  return `/api/daily-checkin/${trackerId}`;
};

export const dailyCheckinUpsert = async (
  trackerId: string,
  upsertDailyCheckinRequestDto: UpsertDailyCheckinRequestDto,
  options?: RequestInit,
): Promise<dailyCheckinUpsertResponse> => {
  const res = await fetch(getDailyCheckinUpsertUrl(trackerId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(upsertDailyCheckinRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: dailyCheckinUpsertResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as dailyCheckinUpsertResponse;
};

export const getDailyCheckinUpsertMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof dailyCheckinUpsert>>,
    TError,
    { trackerId: string; data: UpsertDailyCheckinRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof dailyCheckinUpsert>>,
  TError,
  { trackerId: string; data: UpsertDailyCheckinRequestDto },
  TContext
> => {
  const mutationKey = ['dailyCheckinUpsert'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dailyCheckinUpsert>>,
    { trackerId: string; data: UpsertDailyCheckinRequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return dailyCheckinUpsert(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DailyCheckinUpsertMutationResult = NonNullable<
  Awaited<ReturnType<typeof dailyCheckinUpsert>>
>;
export type DailyCheckinUpsertMutationBody = UpsertDailyCheckinRequestDto;
export type DailyCheckinUpsertMutationError = unknown;

export const useDailyCheckinUpsert = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof dailyCheckinUpsert>>,
      TError,
      { trackerId: string; data: UpsertDailyCheckinRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof dailyCheckinUpsert>>,
  TError,
  { trackerId: string; data: UpsertDailyCheckinRequestDto },
  TContext
> => {
  return useMutation(getDailyCheckinUpsertMutationOptions(options), queryClient);
};
