/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { DailyNutritionLogFindAllParams, UpsertDailyNutritionLogRequestDto } from '../model';

export type dailyNutritionLogFindAllResponse200 = {
  data: Blob;
  status: 200;
};

export type dailyNutritionLogFindAllResponseSuccess = dailyNutritionLogFindAllResponse200 & {
  headers: Headers;
};
export type dailyNutritionLogFindAllResponse = dailyNutritionLogFindAllResponseSuccess;

export const getDailyNutritionLogFindAllUrl = (
  trackerId: string,
  params?: DailyNutritionLogFindAllParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/daily-nutrition-log/${trackerId}?${stringifiedParams}`
    : `/api/daily-nutrition-log/${trackerId}`;
};

export const dailyNutritionLogFindAll = async (
  trackerId: string,
  params?: DailyNutritionLogFindAllParams,
  options?: RequestInit,
): Promise<dailyNutritionLogFindAllResponse> => {
  const res = await fetch(getDailyNutritionLogFindAllUrl(trackerId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: dailyNutritionLogFindAllResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as dailyNutritionLogFindAllResponse;
};

export const getDailyNutritionLogFindAllQueryKey = (
  trackerId: string,
  params?: DailyNutritionLogFindAllParams,
) => {
  return [`/api/daily-nutrition-log/${trackerId}`, ...(params ? [params] : [])] as const;
};

export const getDailyNutritionLogFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof dailyNutritionLogFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: DailyNutritionLogFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dailyNutritionLogFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDailyNutritionLogFindAllQueryKey(trackerId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dailyNutritionLogFindAll>>> = ({
    signal,
  }) => dailyNutritionLogFindAll(trackerId, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dailyNutritionLogFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DailyNutritionLogFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof dailyNutritionLogFindAll>>
>;
export type DailyNutritionLogFindAllQueryError = unknown;

export function useDailyNutritionLogFindAll<
  TData = Awaited<ReturnType<typeof dailyNutritionLogFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params: undefined | DailyNutritionLogFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dailyNutritionLogFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dailyNutritionLogFindAll>>,
          TError,
          Awaited<ReturnType<typeof dailyNutritionLogFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDailyNutritionLogFindAll<
  TData = Awaited<ReturnType<typeof dailyNutritionLogFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: DailyNutritionLogFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dailyNutritionLogFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dailyNutritionLogFindAll>>,
          TError,
          Awaited<ReturnType<typeof dailyNutritionLogFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDailyNutritionLogFindAll<
  TData = Awaited<ReturnType<typeof dailyNutritionLogFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: DailyNutritionLogFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dailyNutritionLogFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useDailyNutritionLogFindAll<
  TData = Awaited<ReturnType<typeof dailyNutritionLogFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: DailyNutritionLogFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dailyNutritionLogFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDailyNutritionLogFindAllQueryOptions(trackerId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type dailyNutritionLogUpsertResponse200 = {
  data: Blob;
  status: 200;
};

export type dailyNutritionLogUpsertResponseSuccess = dailyNutritionLogUpsertResponse200 & {
  headers: Headers;
};
export type dailyNutritionLogUpsertResponse = dailyNutritionLogUpsertResponseSuccess;

export const getDailyNutritionLogUpsertUrl = (trackerId: string) => {
  return `/api/daily-nutrition-log/${trackerId}`;
};

export const dailyNutritionLogUpsert = async (
  trackerId: string,
  upsertDailyNutritionLogRequestDto: UpsertDailyNutritionLogRequestDto,
  options?: RequestInit,
): Promise<dailyNutritionLogUpsertResponse> => {
  const res = await fetch(getDailyNutritionLogUpsertUrl(trackerId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(upsertDailyNutritionLogRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: dailyNutritionLogUpsertResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as dailyNutritionLogUpsertResponse;
};

export const getDailyNutritionLogUpsertMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof dailyNutritionLogUpsert>>,
    TError,
    { trackerId: string; data: UpsertDailyNutritionLogRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof dailyNutritionLogUpsert>>,
  TError,
  { trackerId: string; data: UpsertDailyNutritionLogRequestDto },
  TContext
> => {
  const mutationKey = ['dailyNutritionLogUpsert'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dailyNutritionLogUpsert>>,
    { trackerId: string; data: UpsertDailyNutritionLogRequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return dailyNutritionLogUpsert(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DailyNutritionLogUpsertMutationResult = NonNullable<
  Awaited<ReturnType<typeof dailyNutritionLogUpsert>>
>;
export type DailyNutritionLogUpsertMutationBody = UpsertDailyNutritionLogRequestDto;
export type DailyNutritionLogUpsertMutationError = unknown;

export const useDailyNutritionLogUpsert = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof dailyNutritionLogUpsert>>,
      TError,
      { trackerId: string; data: UpsertDailyNutritionLogRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof dailyNutritionLogUpsert>>,
  TError,
  { trackerId: string; data: UpsertDailyNutritionLogRequestDto },
  TContext
> => {
  return useMutation(getDailyNutritionLogUpsertMutationOptions(options), queryClient);
};
export type dailyNutritionLogFindByDateResponse200 = {
  data: Blob;
  status: 200;
};

export type dailyNutritionLogFindByDateResponseSuccess = dailyNutritionLogFindByDateResponse200 & {
  headers: Headers;
};
export type dailyNutritionLogFindByDateResponse = dailyNutritionLogFindByDateResponseSuccess;

export const getDailyNutritionLogFindByDateUrl = (trackerId: string, logDate: string) => {
  return `/api/daily-nutrition-log/${trackerId}/${logDate}`;
};

export const dailyNutritionLogFindByDate = async (
  trackerId: string,
  logDate: string,
  options?: RequestInit,
): Promise<dailyNutritionLogFindByDateResponse> => {
  const res = await fetch(getDailyNutritionLogFindByDateUrl(trackerId, logDate), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: dailyNutritionLogFindByDateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as dailyNutritionLogFindByDateResponse;
};

export const getDailyNutritionLogFindByDateQueryKey = (trackerId: string, logDate: string) => {
  return [`/api/daily-nutrition-log/${trackerId}/${logDate}`] as const;
};

export const getDailyNutritionLogFindByDateQueryOptions = <
  TData = Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>,
  TError = unknown,
>(
  trackerId: string,
  logDate: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDailyNutritionLogFindByDateQueryKey(trackerId, logDate);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>> = ({
    signal,
  }) => dailyNutritionLogFindByDate(trackerId, logDate, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(trackerId && logDate),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type DailyNutritionLogFindByDateQueryResult = NonNullable<
  Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>
>;
export type DailyNutritionLogFindByDateQueryError = unknown;

export function useDailyNutritionLogFindByDate<
  TData = Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>,
  TError = unknown,
>(
  trackerId: string,
  logDate: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>,
          TError,
          Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDailyNutritionLogFindByDate<
  TData = Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>,
  TError = unknown,
>(
  trackerId: string,
  logDate: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>,
          TError,
          Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDailyNutritionLogFindByDate<
  TData = Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>,
  TError = unknown,
>(
  trackerId: string,
  logDate: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useDailyNutritionLogFindByDate<
  TData = Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>,
  TError = unknown,
>(
  trackerId: string,
  logDate: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dailyNutritionLogFindByDate>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDailyNutritionLogFindByDateQueryOptions(trackerId, logDate, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type dailyNutritionLogDeleteByDateResponse200 = {
  data: void;
  status: 200;
};

export type dailyNutritionLogDeleteByDateResponseSuccess =
  dailyNutritionLogDeleteByDateResponse200 & {
    headers: Headers;
  };
export type dailyNutritionLogDeleteByDateResponse = dailyNutritionLogDeleteByDateResponseSuccess;

export const getDailyNutritionLogDeleteByDateUrl = (trackerId: string, logDate: string) => {
  return `/api/daily-nutrition-log/${trackerId}/${logDate}`;
};

export const dailyNutritionLogDeleteByDate = async (
  trackerId: string,
  logDate: string,
  options?: RequestInit,
): Promise<dailyNutritionLogDeleteByDateResponse> => {
  const res = await fetch(getDailyNutritionLogDeleteByDateUrl(trackerId, logDate), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: dailyNutritionLogDeleteByDateResponse['data'] = body ? JSON.parse(body) : {};
  return {
    data,
    status: res.status,
    headers: res.headers,
  } as dailyNutritionLogDeleteByDateResponse;
};

export const getDailyNutritionLogDeleteByDateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof dailyNutritionLogDeleteByDate>>,
    TError,
    { trackerId: string; logDate: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof dailyNutritionLogDeleteByDate>>,
  TError,
  { trackerId: string; logDate: string },
  TContext
> => {
  const mutationKey = ['dailyNutritionLogDeleteByDate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dailyNutritionLogDeleteByDate>>,
    { trackerId: string; logDate: string }
  > = (props) => {
    const { trackerId, logDate } = props ?? {};

    return dailyNutritionLogDeleteByDate(trackerId, logDate, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DailyNutritionLogDeleteByDateMutationResult = NonNullable<
  Awaited<ReturnType<typeof dailyNutritionLogDeleteByDate>>
>;

export type DailyNutritionLogDeleteByDateMutationError = unknown;

export const useDailyNutritionLogDeleteByDate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof dailyNutritionLogDeleteByDate>>,
      TError,
      { trackerId: string; logDate: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof dailyNutritionLogDeleteByDate>>,
  TError,
  { trackerId: string; logDate: string },
  TContext
> => {
  return useMutation(getDailyNutritionLogDeleteByDateMutationOptions(options), queryClient);
};
