/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { AdminPasswordResetDto } from '../model';

export type resetPasswordResponse200 = {
  data: void;
  status: 200;
};

export type resetPasswordResponseSuccess = resetPasswordResponse200 & {
  headers: Headers;
};
export type resetPasswordResponse = resetPasswordResponseSuccess;

export const getResetPasswordUrl = () => {
  return `/admin/users/reset-password`;
};

export const resetPassword = async (
  adminPasswordResetDto: AdminPasswordResetDto,
  options?: RequestInit,
): Promise<resetPasswordResponse> => {
  const res = await fetch(getResetPasswordUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(adminPasswordResetDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: resetPasswordResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as resetPasswordResponse;
};

export const getResetPasswordMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof resetPassword>>,
    TError,
    { data: AdminPasswordResetDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof resetPassword>>,
  TError,
  { data: AdminPasswordResetDto },
  TContext
> => {
  const mutationKey = ['resetPassword'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof resetPassword>>,
    { data: AdminPasswordResetDto }
  > = (props) => {
    const { data } = props ?? {};

    return resetPassword(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>;
export type ResetPasswordMutationBody = AdminPasswordResetDto;
export type ResetPasswordMutationError = unknown;

export const useResetPassword = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof resetPassword>>,
      TError,
      { data: AdminPasswordResetDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof resetPassword>>,
  TError,
  { data: AdminPasswordResetDto },
  TContext
> => {
  return useMutation(getResetPasswordMutationOptions(options), queryClient);
};
