/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { HabitCompletionUpsertRequestDto } from '../model';

export type habitCompletionUpsertResponse200 = {
  data: Blob;
  status: 200;
};

export type habitCompletionUpsertResponseSuccess = habitCompletionUpsertResponse200 & {
  headers: Headers;
};
export type habitCompletionUpsertResponse = habitCompletionUpsertResponseSuccess;

export const getHabitCompletionUpsertUrl = (trackerId: string) => {
  return `/api/habit-completion/${trackerId}`;
};

export const habitCompletionUpsert = async (
  trackerId: string,
  habitCompletionUpsertRequestDto: HabitCompletionUpsertRequestDto,
  options?: RequestInit,
): Promise<habitCompletionUpsertResponse> => {
  const res = await fetch(getHabitCompletionUpsertUrl(trackerId), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(habitCompletionUpsertRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: habitCompletionUpsertResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as habitCompletionUpsertResponse;
};

export const getHabitCompletionUpsertMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof habitCompletionUpsert>>,
    TError,
    { trackerId: string; data: HabitCompletionUpsertRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof habitCompletionUpsert>>,
  TError,
  { trackerId: string; data: HabitCompletionUpsertRequestDto },
  TContext
> => {
  const mutationKey = ['habitCompletionUpsert'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof habitCompletionUpsert>>,
    { trackerId: string; data: HabitCompletionUpsertRequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return habitCompletionUpsert(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type HabitCompletionUpsertMutationResult = NonNullable<
  Awaited<ReturnType<typeof habitCompletionUpsert>>
>;
export type HabitCompletionUpsertMutationBody = HabitCompletionUpsertRequestDto;
export type HabitCompletionUpsertMutationError = unknown;

export const useHabitCompletionUpsert = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof habitCompletionUpsert>>,
      TError,
      { trackerId: string; data: HabitCompletionUpsertRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof habitCompletionUpsert>>,
  TError,
  { trackerId: string; data: HabitCompletionUpsertRequestDto },
  TContext
> => {
  return useMutation(getHabitCompletionUpsertMutationOptions(options), queryClient);
};
