/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AccountFindAllParams,
  AccountUploadIconBody,
  AccountUploadIconParams,
  CreateAccountRequestDto,
  UpdateAccountRequestDto,
} from '../model';

export type accountFindAllResponse200 = {
  data: Blob;
  status: 200;
};

export type accountFindAllResponseSuccess = accountFindAllResponse200 & {
  headers: Headers;
};
export type accountFindAllResponse = accountFindAllResponseSuccess;

export const getAccountFindAllUrl = (trackerId: string, params?: AccountFindAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/account/${trackerId}?${stringifiedParams}`
    : `/api/account/${trackerId}`;
};

export const accountFindAll = async (
  trackerId: string,
  params?: AccountFindAllParams,
  options?: RequestInit,
): Promise<accountFindAllResponse> => {
  const res = await fetch(getAccountFindAllUrl(trackerId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: accountFindAllResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as accountFindAllResponse;
};

export const getAccountFindAllQueryKey = (trackerId: string, params?: AccountFindAllParams) => {
  return [`/api/account/${trackerId}`, ...(params ? [params] : [])] as const;
};

export const getAccountFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof accountFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: AccountFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof accountFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAccountFindAllQueryKey(trackerId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof accountFindAll>>> = ({ signal }) =>
    accountFindAll(trackerId, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof accountFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AccountFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof accountFindAll>>>;
export type AccountFindAllQueryError = unknown;

export function useAccountFindAll<
  TData = Awaited<ReturnType<typeof accountFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params: undefined | AccountFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof accountFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountFindAll>>,
          TError,
          Awaited<ReturnType<typeof accountFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAccountFindAll<
  TData = Awaited<ReturnType<typeof accountFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: AccountFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof accountFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountFindAll>>,
          TError,
          Awaited<ReturnType<typeof accountFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAccountFindAll<
  TData = Awaited<ReturnType<typeof accountFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: AccountFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof accountFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAccountFindAll<
  TData = Awaited<ReturnType<typeof accountFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: AccountFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof accountFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAccountFindAllQueryOptions(trackerId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type accountCreateResponse200 = {
  data: Blob;
  status: 200;
};

export type accountCreateResponseSuccess = accountCreateResponse200 & {
  headers: Headers;
};
export type accountCreateResponse = accountCreateResponseSuccess;

export const getAccountCreateUrl = (trackerId: string) => {
  return `/api/account/${trackerId}`;
};

export const accountCreate = async (
  trackerId: string,
  createAccountRequestDto: CreateAccountRequestDto,
  options?: RequestInit,
): Promise<accountCreateResponse> => {
  const res = await fetch(getAccountCreateUrl(trackerId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createAccountRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: accountCreateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as accountCreateResponse;
};

export const getAccountCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountCreate>>,
    TError,
    { trackerId: string; data: CreateAccountRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountCreate>>,
  TError,
  { trackerId: string; data: CreateAccountRequestDto },
  TContext
> => {
  const mutationKey = ['accountCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountCreate>>,
    { trackerId: string; data: CreateAccountRequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return accountCreate(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountCreateMutationResult = NonNullable<Awaited<ReturnType<typeof accountCreate>>>;
export type AccountCreateMutationBody = CreateAccountRequestDto;
export type AccountCreateMutationError = unknown;

export const useAccountCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof accountCreate>>,
      TError,
      { trackerId: string; data: CreateAccountRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof accountCreate>>,
  TError,
  { trackerId: string; data: CreateAccountRequestDto },
  TContext
> => {
  return useMutation(getAccountCreateMutationOptions(options), queryClient);
};
export type accountUploadIconResponse200 = {
  data: Blob;
  status: 200;
};

export type accountUploadIconResponseSuccess = accountUploadIconResponse200 & {
  headers: Headers;
};
export type accountUploadIconResponse = accountUploadIconResponseSuccess;

export const getAccountUploadIconUrl = (
  trackerId: string,
  accountId: string,
  params?: AccountUploadIconParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/account/${trackerId}/${accountId}/icon?${stringifiedParams}`
    : `/api/account/${trackerId}/${accountId}/icon`;
};

export const accountUploadIcon = async (
  trackerId: string,
  accountId: string,
  accountUploadIconBody: AccountUploadIconBody,
  params?: AccountUploadIconParams,
  options?: RequestInit,
): Promise<accountUploadIconResponse> => {
  const res = await fetch(getAccountUploadIconUrl(trackerId, accountId, params), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(accountUploadIconBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: accountUploadIconResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as accountUploadIconResponse;
};

export const getAccountUploadIconMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountUploadIcon>>,
    TError,
    {
      trackerId: string;
      accountId: string;
      data: AccountUploadIconBody;
      params?: AccountUploadIconParams;
    },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountUploadIcon>>,
  TError,
  {
    trackerId: string;
    accountId: string;
    data: AccountUploadIconBody;
    params?: AccountUploadIconParams;
  },
  TContext
> => {
  const mutationKey = ['accountUploadIcon'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountUploadIcon>>,
    {
      trackerId: string;
      accountId: string;
      data: AccountUploadIconBody;
      params?: AccountUploadIconParams;
    }
  > = (props) => {
    const { trackerId, accountId, data, params } = props ?? {};

    return accountUploadIcon(trackerId, accountId, data, params, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountUploadIconMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountUploadIcon>>
>;
export type AccountUploadIconMutationBody = AccountUploadIconBody;
export type AccountUploadIconMutationError = unknown;

export const useAccountUploadIcon = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof accountUploadIcon>>,
      TError,
      {
        trackerId: string;
        accountId: string;
        data: AccountUploadIconBody;
        params?: AccountUploadIconParams;
      },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof accountUploadIcon>>,
  TError,
  {
    trackerId: string;
    accountId: string;
    data: AccountUploadIconBody;
    params?: AccountUploadIconParams;
  },
  TContext
> => {
  return useMutation(getAccountUploadIconMutationOptions(options), queryClient);
};
export type accountDeleteIconResponse200 = {
  data: Blob;
  status: 200;
};

export type accountDeleteIconResponseSuccess = accountDeleteIconResponse200 & {
  headers: Headers;
};
export type accountDeleteIconResponse = accountDeleteIconResponseSuccess;

export const getAccountDeleteIconUrl = (trackerId: string, accountId: string) => {
  return `/api/account/${trackerId}/${accountId}/icon`;
};

export const accountDeleteIcon = async (
  trackerId: string,
  accountId: string,
  options?: RequestInit,
): Promise<accountDeleteIconResponse> => {
  const res = await fetch(getAccountDeleteIconUrl(trackerId, accountId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: accountDeleteIconResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as accountDeleteIconResponse;
};

export const getAccountDeleteIconMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountDeleteIcon>>,
    TError,
    { trackerId: string; accountId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountDeleteIcon>>,
  TError,
  { trackerId: string; accountId: string },
  TContext
> => {
  const mutationKey = ['accountDeleteIcon'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountDeleteIcon>>,
    { trackerId: string; accountId: string }
  > = (props) => {
    const { trackerId, accountId } = props ?? {};

    return accountDeleteIcon(trackerId, accountId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountDeleteIconMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountDeleteIcon>>
>;

export type AccountDeleteIconMutationError = unknown;

export const useAccountDeleteIcon = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof accountDeleteIcon>>,
      TError,
      { trackerId: string; accountId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof accountDeleteIcon>>,
  TError,
  { trackerId: string; accountId: string },
  TContext
> => {
  return useMutation(getAccountDeleteIconMutationOptions(options), queryClient);
};
export type accountFindByIdResponse200 = {
  data: Blob;
  status: 200;
};

export type accountFindByIdResponseSuccess = accountFindByIdResponse200 & {
  headers: Headers;
};
export type accountFindByIdResponse = accountFindByIdResponseSuccess;

export const getAccountFindByIdUrl = (trackerId: string, accountId: string) => {
  return `/api/account/${trackerId}/${accountId}`;
};

export const accountFindById = async (
  trackerId: string,
  accountId: string,
  options?: RequestInit,
): Promise<accountFindByIdResponse> => {
  const res = await fetch(getAccountFindByIdUrl(trackerId, accountId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: accountFindByIdResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as accountFindByIdResponse;
};

export const getAccountFindByIdQueryKey = (trackerId: string, accountId: string) => {
  return [`/api/account/${trackerId}/${accountId}`] as const;
};

export const getAccountFindByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof accountFindById>>,
  TError = unknown,
>(
  trackerId: string,
  accountId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof accountFindById>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getAccountFindByIdQueryKey(trackerId, accountId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof accountFindById>>> = ({ signal }) =>
    accountFindById(trackerId, accountId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(trackerId && accountId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof accountFindById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type AccountFindByIdQueryResult = NonNullable<Awaited<ReturnType<typeof accountFindById>>>;
export type AccountFindByIdQueryError = unknown;

export function useAccountFindById<
  TData = Awaited<ReturnType<typeof accountFindById>>,
  TError = unknown,
>(
  trackerId: string,
  accountId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof accountFindById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountFindById>>,
          TError,
          Awaited<ReturnType<typeof accountFindById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAccountFindById<
  TData = Awaited<ReturnType<typeof accountFindById>>,
  TError = unknown,
>(
  trackerId: string,
  accountId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof accountFindById>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountFindById>>,
          TError,
          Awaited<ReturnType<typeof accountFindById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useAccountFindById<
  TData = Awaited<ReturnType<typeof accountFindById>>,
  TError = unknown,
>(
  trackerId: string,
  accountId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof accountFindById>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useAccountFindById<
  TData = Awaited<ReturnType<typeof accountFindById>>,
  TError = unknown,
>(
  trackerId: string,
  accountId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof accountFindById>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getAccountFindByIdQueryOptions(trackerId, accountId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type accountDeactivateResponse200 = {
  data: void;
  status: 200;
};

export type accountDeactivateResponseSuccess = accountDeactivateResponse200 & {
  headers: Headers;
};
export type accountDeactivateResponse = accountDeactivateResponseSuccess;

export const getAccountDeactivateUrl = (trackerId: string, accountId: string) => {
  return `/api/account/${trackerId}/${accountId}`;
};

export const accountDeactivate = async (
  trackerId: string,
  accountId: string,
  options?: RequestInit,
): Promise<accountDeactivateResponse> => {
  const res = await fetch(getAccountDeactivateUrl(trackerId, accountId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: accountDeactivateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as accountDeactivateResponse;
};

export const getAccountDeactivateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountDeactivate>>,
    TError,
    { trackerId: string; accountId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountDeactivate>>,
  TError,
  { trackerId: string; accountId: string },
  TContext
> => {
  const mutationKey = ['accountDeactivate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountDeactivate>>,
    { trackerId: string; accountId: string }
  > = (props) => {
    const { trackerId, accountId } = props ?? {};

    return accountDeactivate(trackerId, accountId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountDeactivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountDeactivate>>
>;

export type AccountDeactivateMutationError = unknown;

export const useAccountDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof accountDeactivate>>,
      TError,
      { trackerId: string; accountId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof accountDeactivate>>,
  TError,
  { trackerId: string; accountId: string },
  TContext
> => {
  return useMutation(getAccountDeactivateMutationOptions(options), queryClient);
};
export type accountUpdateResponse200 = {
  data: Blob;
  status: 200;
};

export type accountUpdateResponseSuccess = accountUpdateResponse200 & {
  headers: Headers;
};
export type accountUpdateResponse = accountUpdateResponseSuccess;

export const getAccountUpdateUrl = (trackerId: string, accountId: string) => {
  return `/api/account/${trackerId}/${accountId}`;
};

export const accountUpdate = async (
  trackerId: string,
  accountId: string,
  updateAccountRequestDto: UpdateAccountRequestDto,
  options?: RequestInit,
): Promise<accountUpdateResponse> => {
  const res = await fetch(getAccountUpdateUrl(trackerId, accountId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateAccountRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: accountUpdateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as accountUpdateResponse;
};

export const getAccountUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountUpdate>>,
    TError,
    { trackerId: string; accountId: string; data: UpdateAccountRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountUpdate>>,
  TError,
  { trackerId: string; accountId: string; data: UpdateAccountRequestDto },
  TContext
> => {
  const mutationKey = ['accountUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountUpdate>>,
    { trackerId: string; accountId: string; data: UpdateAccountRequestDto }
  > = (props) => {
    const { trackerId, accountId, data } = props ?? {};

    return accountUpdate(trackerId, accountId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof accountUpdate>>>;
export type AccountUpdateMutationBody = UpdateAccountRequestDto;
export type AccountUpdateMutationError = unknown;

export const useAccountUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof accountUpdate>>,
      TError,
      { trackerId: string; accountId: string; data: UpdateAccountRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof accountUpdate>>,
  TError,
  { trackerId: string; accountId: string; data: UpdateAccountRequestDto },
  TContext
> => {
  return useMutation(getAccountUpdateMutationOptions(options), queryClient);
};
