/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  BudgetPlanFindAllActiveParams,
  BudgetPlanFindAllParams,
  CreateBudgetPlanRequestDto,
  UpdateBudgetPlanRequestDto,
} from '../model';

export type budgetPlanFindAllResponse200 = {
  data: Blob;
  status: 200;
};

export type budgetPlanFindAllResponseSuccess = budgetPlanFindAllResponse200 & {
  headers: Headers;
};
export type budgetPlanFindAllResponse = budgetPlanFindAllResponseSuccess;

export const getBudgetPlanFindAllUrl = (trackerId: string, params?: BudgetPlanFindAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/budget-plan/${trackerId}?${stringifiedParams}`
    : `/api/budget-plan/${trackerId}`;
};

export const budgetPlanFindAll = async (
  trackerId: string,
  params?: BudgetPlanFindAllParams,
  options?: RequestInit,
): Promise<budgetPlanFindAllResponse> => {
  const res = await fetch(getBudgetPlanFindAllUrl(trackerId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: budgetPlanFindAllResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as budgetPlanFindAllResponse;
};

export const getBudgetPlanFindAllQueryKey = (
  trackerId: string,
  params?: BudgetPlanFindAllParams,
) => {
  return [`/api/budget-plan/${trackerId}`, ...(params ? [params] : [])] as const;
};

export const getBudgetPlanFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof budgetPlanFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: BudgetPlanFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBudgetPlanFindAllQueryKey(trackerId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof budgetPlanFindAll>>> = ({ signal }) =>
    budgetPlanFindAll(trackerId, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof budgetPlanFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BudgetPlanFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof budgetPlanFindAll>>
>;
export type BudgetPlanFindAllQueryError = unknown;

export function useBudgetPlanFindAll<
  TData = Awaited<ReturnType<typeof budgetPlanFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params: undefined | BudgetPlanFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof budgetPlanFindAll>>,
          TError,
          Awaited<ReturnType<typeof budgetPlanFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBudgetPlanFindAll<
  TData = Awaited<ReturnType<typeof budgetPlanFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: BudgetPlanFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindAll>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof budgetPlanFindAll>>,
          TError,
          Awaited<ReturnType<typeof budgetPlanFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBudgetPlanFindAll<
  TData = Awaited<ReturnType<typeof budgetPlanFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: BudgetPlanFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBudgetPlanFindAll<
  TData = Awaited<ReturnType<typeof budgetPlanFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: BudgetPlanFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBudgetPlanFindAllQueryOptions(trackerId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type budgetPlanCreateResponse200 = {
  data: Blob;
  status: 200;
};

export type budgetPlanCreateResponseSuccess = budgetPlanCreateResponse200 & {
  headers: Headers;
};
export type budgetPlanCreateResponse = budgetPlanCreateResponseSuccess;

export const getBudgetPlanCreateUrl = (trackerId: string) => {
  return `/api/budget-plan/${trackerId}`;
};

export const budgetPlanCreate = async (
  trackerId: string,
  createBudgetPlanRequestDto: CreateBudgetPlanRequestDto,
  options?: RequestInit,
): Promise<budgetPlanCreateResponse> => {
  const res = await fetch(getBudgetPlanCreateUrl(trackerId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createBudgetPlanRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: budgetPlanCreateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as budgetPlanCreateResponse;
};

export const getBudgetPlanCreateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof budgetPlanCreate>>,
    TError,
    { trackerId: string; data: CreateBudgetPlanRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof budgetPlanCreate>>,
  TError,
  { trackerId: string; data: CreateBudgetPlanRequestDto },
  TContext
> => {
  const mutationKey = ['budgetPlanCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof budgetPlanCreate>>,
    { trackerId: string; data: CreateBudgetPlanRequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return budgetPlanCreate(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BudgetPlanCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof budgetPlanCreate>>
>;
export type BudgetPlanCreateMutationBody = CreateBudgetPlanRequestDto;
export type BudgetPlanCreateMutationError = unknown;

export const useBudgetPlanCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof budgetPlanCreate>>,
      TError,
      { trackerId: string; data: CreateBudgetPlanRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof budgetPlanCreate>>,
  TError,
  { trackerId: string; data: CreateBudgetPlanRequestDto },
  TContext
> => {
  return useMutation(getBudgetPlanCreateMutationOptions(options), queryClient);
};
export type budgetPlanFindByIdResponse200 = {
  data: Blob;
  status: 200;
};

export type budgetPlanFindByIdResponseSuccess = budgetPlanFindByIdResponse200 & {
  headers: Headers;
};
export type budgetPlanFindByIdResponse = budgetPlanFindByIdResponseSuccess;

export const getBudgetPlanFindByIdUrl = (trackerId: string, budgetPlanId: string) => {
  return `/api/budget-plan/${trackerId}/${budgetPlanId}`;
};

export const budgetPlanFindById = async (
  trackerId: string,
  budgetPlanId: string,
  options?: RequestInit,
): Promise<budgetPlanFindByIdResponse> => {
  const res = await fetch(getBudgetPlanFindByIdUrl(trackerId, budgetPlanId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: budgetPlanFindByIdResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as budgetPlanFindByIdResponse;
};

export const getBudgetPlanFindByIdQueryKey = (trackerId: string, budgetPlanId: string) => {
  return [`/api/budget-plan/${trackerId}/${budgetPlanId}`] as const;
};

export const getBudgetPlanFindByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof budgetPlanFindById>>,
  TError = unknown,
>(
  trackerId: string,
  budgetPlanId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindById>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBudgetPlanFindByIdQueryKey(trackerId, budgetPlanId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof budgetPlanFindById>>> = ({ signal }) =>
    budgetPlanFindById(trackerId, budgetPlanId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(trackerId && budgetPlanId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type BudgetPlanFindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof budgetPlanFindById>>
>;
export type BudgetPlanFindByIdQueryError = unknown;

export function useBudgetPlanFindById<
  TData = Awaited<ReturnType<typeof budgetPlanFindById>>,
  TError = unknown,
>(
  trackerId: string,
  budgetPlanId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindById>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof budgetPlanFindById>>,
          TError,
          Awaited<ReturnType<typeof budgetPlanFindById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBudgetPlanFindById<
  TData = Awaited<ReturnType<typeof budgetPlanFindById>>,
  TError = unknown,
>(
  trackerId: string,
  budgetPlanId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof budgetPlanFindById>>,
          TError,
          Awaited<ReturnType<typeof budgetPlanFindById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBudgetPlanFindById<
  TData = Awaited<ReturnType<typeof budgetPlanFindById>>,
  TError = unknown,
>(
  trackerId: string,
  budgetPlanId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindById>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBudgetPlanFindById<
  TData = Awaited<ReturnType<typeof budgetPlanFindById>>,
  TError = unknown,
>(
  trackerId: string,
  budgetPlanId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindById>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBudgetPlanFindByIdQueryOptions(trackerId, budgetPlanId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type budgetPlanDeactivateResponse200 = {
  data: void;
  status: 200;
};

export type budgetPlanDeactivateResponseSuccess = budgetPlanDeactivateResponse200 & {
  headers: Headers;
};
export type budgetPlanDeactivateResponse = budgetPlanDeactivateResponseSuccess;

export const getBudgetPlanDeactivateUrl = (trackerId: string, budgetPlanId: string) => {
  return `/api/budget-plan/${trackerId}/${budgetPlanId}`;
};

export const budgetPlanDeactivate = async (
  trackerId: string,
  budgetPlanId: string,
  options?: RequestInit,
): Promise<budgetPlanDeactivateResponse> => {
  const res = await fetch(getBudgetPlanDeactivateUrl(trackerId, budgetPlanId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: budgetPlanDeactivateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as budgetPlanDeactivateResponse;
};

export const getBudgetPlanDeactivateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof budgetPlanDeactivate>>,
    TError,
    { trackerId: string; budgetPlanId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof budgetPlanDeactivate>>,
  TError,
  { trackerId: string; budgetPlanId: string },
  TContext
> => {
  const mutationKey = ['budgetPlanDeactivate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof budgetPlanDeactivate>>,
    { trackerId: string; budgetPlanId: string }
  > = (props) => {
    const { trackerId, budgetPlanId } = props ?? {};

    return budgetPlanDeactivate(trackerId, budgetPlanId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BudgetPlanDeactivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof budgetPlanDeactivate>>
>;

export type BudgetPlanDeactivateMutationError = unknown;

export const useBudgetPlanDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof budgetPlanDeactivate>>,
      TError,
      { trackerId: string; budgetPlanId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof budgetPlanDeactivate>>,
  TError,
  { trackerId: string; budgetPlanId: string },
  TContext
> => {
  return useMutation(getBudgetPlanDeactivateMutationOptions(options), queryClient);
};
export type budgetPlanUpdateResponse200 = {
  data: Blob;
  status: 200;
};

export type budgetPlanUpdateResponseSuccess = budgetPlanUpdateResponse200 & {
  headers: Headers;
};
export type budgetPlanUpdateResponse = budgetPlanUpdateResponseSuccess;

export const getBudgetPlanUpdateUrl = (trackerId: string, budgetPlanId: string) => {
  return `/api/budget-plan/${trackerId}/${budgetPlanId}`;
};

export const budgetPlanUpdate = async (
  trackerId: string,
  budgetPlanId: string,
  updateBudgetPlanRequestDto: UpdateBudgetPlanRequestDto,
  options?: RequestInit,
): Promise<budgetPlanUpdateResponse> => {
  const res = await fetch(getBudgetPlanUpdateUrl(trackerId, budgetPlanId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateBudgetPlanRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: budgetPlanUpdateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as budgetPlanUpdateResponse;
};

export const getBudgetPlanUpdateMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof budgetPlanUpdate>>,
    TError,
    { trackerId: string; budgetPlanId: string; data: UpdateBudgetPlanRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof budgetPlanUpdate>>,
  TError,
  { trackerId: string; budgetPlanId: string; data: UpdateBudgetPlanRequestDto },
  TContext
> => {
  const mutationKey = ['budgetPlanUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof budgetPlanUpdate>>,
    { trackerId: string; budgetPlanId: string; data: UpdateBudgetPlanRequestDto }
  > = (props) => {
    const { trackerId, budgetPlanId, data } = props ?? {};

    return budgetPlanUpdate(trackerId, budgetPlanId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type BudgetPlanUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof budgetPlanUpdate>>
>;
export type BudgetPlanUpdateMutationBody = UpdateBudgetPlanRequestDto;
export type BudgetPlanUpdateMutationError = unknown;

export const useBudgetPlanUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof budgetPlanUpdate>>,
      TError,
      { trackerId: string; budgetPlanId: string; data: UpdateBudgetPlanRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof budgetPlanUpdate>>,
  TError,
  { trackerId: string; budgetPlanId: string; data: UpdateBudgetPlanRequestDto },
  TContext
> => {
  return useMutation(getBudgetPlanUpdateMutationOptions(options), queryClient);
};
export type budgetPlanFindAllActiveResponse200 = {
  data: Blob;
  status: 200;
};

export type budgetPlanFindAllActiveResponseSuccess = budgetPlanFindAllActiveResponse200 & {
  headers: Headers;
};
export type budgetPlanFindAllActiveResponse = budgetPlanFindAllActiveResponseSuccess;

export const getBudgetPlanFindAllActiveUrl = (
  trackerId: string,
  params?: BudgetPlanFindAllActiveParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/budget-plan/${trackerId}/active?${stringifiedParams}`
    : `/api/budget-plan/${trackerId}/active`;
};

export const budgetPlanFindAllActive = async (
  trackerId: string,
  params?: BudgetPlanFindAllActiveParams,
  options?: RequestInit,
): Promise<budgetPlanFindAllActiveResponse> => {
  const res = await fetch(getBudgetPlanFindAllActiveUrl(trackerId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: budgetPlanFindAllActiveResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as budgetPlanFindAllActiveResponse;
};

export const getBudgetPlanFindAllActiveQueryKey = (
  trackerId: string,
  params?: BudgetPlanFindAllActiveParams,
) => {
  return [`/api/budget-plan/${trackerId}/active`, ...(params ? [params] : [])] as const;
};

export const getBudgetPlanFindAllActiveQueryOptions = <
  TData = Awaited<ReturnType<typeof budgetPlanFindAllActive>>,
  TError = unknown,
>(
  trackerId: string,
  params?: BudgetPlanFindAllActiveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindAllActive>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBudgetPlanFindAllActiveQueryKey(trackerId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof budgetPlanFindAllActive>>> = ({
    signal,
  }) => budgetPlanFindAllActive(trackerId, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof budgetPlanFindAllActive>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type BudgetPlanFindAllActiveQueryResult = NonNullable<
  Awaited<ReturnType<typeof budgetPlanFindAllActive>>
>;
export type BudgetPlanFindAllActiveQueryError = unknown;

export function useBudgetPlanFindAllActive<
  TData = Awaited<ReturnType<typeof budgetPlanFindAllActive>>,
  TError = unknown,
>(
  trackerId: string,
  params: undefined | BudgetPlanFindAllActiveParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindAllActive>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof budgetPlanFindAllActive>>,
          TError,
          Awaited<ReturnType<typeof budgetPlanFindAllActive>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBudgetPlanFindAllActive<
  TData = Awaited<ReturnType<typeof budgetPlanFindAllActive>>,
  TError = unknown,
>(
  trackerId: string,
  params?: BudgetPlanFindAllActiveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindAllActive>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof budgetPlanFindAllActive>>,
          TError,
          Awaited<ReturnType<typeof budgetPlanFindAllActive>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBudgetPlanFindAllActive<
  TData = Awaited<ReturnType<typeof budgetPlanFindAllActive>>,
  TError = unknown,
>(
  trackerId: string,
  params?: BudgetPlanFindAllActiveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindAllActive>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBudgetPlanFindAllActive<
  TData = Awaited<ReturnType<typeof budgetPlanFindAllActive>>,
  TError = unknown,
>(
  trackerId: string,
  params?: BudgetPlanFindAllActiveParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof budgetPlanFindAllActive>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBudgetPlanFindAllActiveQueryOptions(trackerId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
