/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { AuthenticationRequestDto, RegistrationRequestDto } from '../model';

export type authRegisterResponse200 = {
  data: void;
  status: 200;
};

export type authRegisterResponseSuccess = authRegisterResponse200 & {
  headers: Headers;
};
export type authRegisterResponse = authRegisterResponseSuccess;

export const getAuthRegisterUrl = () => {
  return `/auth/register`;
};

export const authRegister = async (
  registrationRequestDto: RegistrationRequestDto,
  options?: RequestInit,
): Promise<authRegisterResponse> => {
  const res = await fetch(getAuthRegisterUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(registrationRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authRegisterResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as authRegisterResponse;
};

export const getAuthRegisterMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authRegister>>,
    TError,
    { data: RegistrationRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authRegister>>,
  TError,
  { data: RegistrationRequestDto },
  TContext
> => {
  const mutationKey = ['authRegister'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authRegister>>,
    { data: RegistrationRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return authRegister(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authRegister>>>;
export type AuthRegisterMutationBody = RegistrationRequestDto;
export type AuthRegisterMutationError = unknown;

export const useAuthRegister = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authRegister>>,
      TError,
      { data: RegistrationRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authRegister>>,
  TError,
  { data: RegistrationRequestDto },
  TContext
> => {
  return useMutation(getAuthRegisterMutationOptions(options), queryClient);
};
export type authLoginResponse200 = {
  data: Blob;
  status: 200;
};

export type authLoginResponseSuccess = authLoginResponse200 & {
  headers: Headers;
};
export type authLoginResponse = authLoginResponseSuccess;

export const getAuthLoginUrl = () => {
  return `/auth/login`;
};

export const authLogin = async (
  authenticationRequestDto: AuthenticationRequestDto,
  options?: RequestInit,
): Promise<authLoginResponse> => {
  const res = await fetch(getAuthLoginUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(authenticationRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: authLoginResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as authLoginResponse;
};

export const getAuthLoginMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authLogin>>,
    TError,
    { data: AuthenticationRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authLogin>>,
  TError,
  { data: AuthenticationRequestDto },
  TContext
> => {
  const mutationKey = ['authLogin'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authLogin>>,
    { data: AuthenticationRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return authLogin(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authLogin>>>;
export type AuthLoginMutationBody = AuthenticationRequestDto;
export type AuthLoginMutationError = unknown;

export const useAuthLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authLogin>>,
      TError,
      { data: AuthenticationRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authLogin>>,
  TError,
  { data: AuthenticationRequestDto },
  TContext
> => {
  return useMutation(getAuthLoginMutationOptions(options), queryClient);
};
