/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateInstitutionRequestDto,
  InstitutionDashboardParams,
  InstitutionFindAllParams,
  InstitutionUploadIconBody,
  InstitutionUploadIconParams,
  UpdateInstitutionRequestDto,
} from '../model';

export type institutionFindAllResponse200 = {
  data: Blob;
  status: 200;
};

export type institutionFindAllResponseSuccess = institutionFindAllResponse200 & {
  headers: Headers;
};
export type institutionFindAllResponse = institutionFindAllResponseSuccess;

export const getInstitutionFindAllUrl = (trackerId: string, params?: InstitutionFindAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/institution/${trackerId}?${stringifiedParams}`
    : `/api/institution/${trackerId}`;
};

export const institutionFindAll = async (
  trackerId: string,
  params?: InstitutionFindAllParams,
  options?: RequestInit,
): Promise<institutionFindAllResponse> => {
  const res = await fetch(getInstitutionFindAllUrl(trackerId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: institutionFindAllResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as institutionFindAllResponse;
};

export const getInstitutionFindAllQueryKey = (
  trackerId: string,
  params?: InstitutionFindAllParams,
) => {
  return [`/api/institution/${trackerId}`, ...(params ? [params] : [])] as const;
};

export const getInstitutionFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof institutionFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: InstitutionFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof institutionFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInstitutionFindAllQueryKey(trackerId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof institutionFindAll>>> = ({ signal }) =>
    institutionFindAll(trackerId, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof institutionFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InstitutionFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof institutionFindAll>>
>;
export type InstitutionFindAllQueryError = unknown;

export function useInstitutionFindAll<
  TData = Awaited<ReturnType<typeof institutionFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params: undefined | InstitutionFindAllParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof institutionFindAll>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof institutionFindAll>>,
          TError,
          Awaited<ReturnType<typeof institutionFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInstitutionFindAll<
  TData = Awaited<ReturnType<typeof institutionFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: InstitutionFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof institutionFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof institutionFindAll>>,
          TError,
          Awaited<ReturnType<typeof institutionFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInstitutionFindAll<
  TData = Awaited<ReturnType<typeof institutionFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: InstitutionFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof institutionFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useInstitutionFindAll<
  TData = Awaited<ReturnType<typeof institutionFindAll>>,
  TError = unknown,
>(
  trackerId: string,
  params?: InstitutionFindAllParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof institutionFindAll>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInstitutionFindAllQueryOptions(trackerId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type institutionCreateResponse200 = {
  data: Blob;
  status: 200;
};

export type institutionCreateResponseSuccess = institutionCreateResponse200 & {
  headers: Headers;
};
export type institutionCreateResponse = institutionCreateResponseSuccess;

export const getInstitutionCreateUrl = (trackerId: string) => {
  return `/api/institution/${trackerId}`;
};

export const institutionCreate = async (
  trackerId: string,
  createInstitutionRequestDto: CreateInstitutionRequestDto,
  options?: RequestInit,
): Promise<institutionCreateResponse> => {
  const res = await fetch(getInstitutionCreateUrl(trackerId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createInstitutionRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: institutionCreateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as institutionCreateResponse;
};

export const getInstitutionCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof institutionCreate>>,
    TError,
    { trackerId: string; data: CreateInstitutionRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof institutionCreate>>,
  TError,
  { trackerId: string; data: CreateInstitutionRequestDto },
  TContext
> => {
  const mutationKey = ['institutionCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof institutionCreate>>,
    { trackerId: string; data: CreateInstitutionRequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return institutionCreate(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InstitutionCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof institutionCreate>>
>;
export type InstitutionCreateMutationBody = CreateInstitutionRequestDto;
export type InstitutionCreateMutationError = unknown;

export const useInstitutionCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof institutionCreate>>,
      TError,
      { trackerId: string; data: CreateInstitutionRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof institutionCreate>>,
  TError,
  { trackerId: string; data: CreateInstitutionRequestDto },
  TContext
> => {
  return useMutation(getInstitutionCreateMutationOptions(options), queryClient);
};
export type institutionUploadIconResponse200 = {
  data: Blob;
  status: 200;
};

export type institutionUploadIconResponseSuccess = institutionUploadIconResponse200 & {
  headers: Headers;
};
export type institutionUploadIconResponse = institutionUploadIconResponseSuccess;

export const getInstitutionUploadIconUrl = (
  trackerId: string,
  institutionId: string,
  params?: InstitutionUploadIconParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/institution/${trackerId}/${institutionId}/icon?${stringifiedParams}`
    : `/api/institution/${trackerId}/${institutionId}/icon`;
};

export const institutionUploadIcon = async (
  trackerId: string,
  institutionId: string,
  institutionUploadIconBody: InstitutionUploadIconBody,
  params?: InstitutionUploadIconParams,
  options?: RequestInit,
): Promise<institutionUploadIconResponse> => {
  const res = await fetch(getInstitutionUploadIconUrl(trackerId, institutionId, params), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(institutionUploadIconBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: institutionUploadIconResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as institutionUploadIconResponse;
};

export const getInstitutionUploadIconMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof institutionUploadIcon>>,
    TError,
    {
      trackerId: string;
      institutionId: string;
      data: InstitutionUploadIconBody;
      params?: InstitutionUploadIconParams;
    },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof institutionUploadIcon>>,
  TError,
  {
    trackerId: string;
    institutionId: string;
    data: InstitutionUploadIconBody;
    params?: InstitutionUploadIconParams;
  },
  TContext
> => {
  const mutationKey = ['institutionUploadIcon'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof institutionUploadIcon>>,
    {
      trackerId: string;
      institutionId: string;
      data: InstitutionUploadIconBody;
      params?: InstitutionUploadIconParams;
    }
  > = (props) => {
    const { trackerId, institutionId, data, params } = props ?? {};

    return institutionUploadIcon(trackerId, institutionId, data, params, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InstitutionUploadIconMutationResult = NonNullable<
  Awaited<ReturnType<typeof institutionUploadIcon>>
>;
export type InstitutionUploadIconMutationBody = InstitutionUploadIconBody;
export type InstitutionUploadIconMutationError = unknown;

export const useInstitutionUploadIcon = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof institutionUploadIcon>>,
      TError,
      {
        trackerId: string;
        institutionId: string;
        data: InstitutionUploadIconBody;
        params?: InstitutionUploadIconParams;
      },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof institutionUploadIcon>>,
  TError,
  {
    trackerId: string;
    institutionId: string;
    data: InstitutionUploadIconBody;
    params?: InstitutionUploadIconParams;
  },
  TContext
> => {
  return useMutation(getInstitutionUploadIconMutationOptions(options), queryClient);
};
export type institutionDeleteIconResponse200 = {
  data: Blob;
  status: 200;
};

export type institutionDeleteIconResponseSuccess = institutionDeleteIconResponse200 & {
  headers: Headers;
};
export type institutionDeleteIconResponse = institutionDeleteIconResponseSuccess;

export const getInstitutionDeleteIconUrl = (trackerId: string, institutionId: string) => {
  return `/api/institution/${trackerId}/${institutionId}/icon`;
};

export const institutionDeleteIcon = async (
  trackerId: string,
  institutionId: string,
  options?: RequestInit,
): Promise<institutionDeleteIconResponse> => {
  const res = await fetch(getInstitutionDeleteIconUrl(trackerId, institutionId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: institutionDeleteIconResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as institutionDeleteIconResponse;
};

export const getInstitutionDeleteIconMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof institutionDeleteIcon>>,
    TError,
    { trackerId: string; institutionId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof institutionDeleteIcon>>,
  TError,
  { trackerId: string; institutionId: string },
  TContext
> => {
  const mutationKey = ['institutionDeleteIcon'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof institutionDeleteIcon>>,
    { trackerId: string; institutionId: string }
  > = (props) => {
    const { trackerId, institutionId } = props ?? {};

    return institutionDeleteIcon(trackerId, institutionId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InstitutionDeleteIconMutationResult = NonNullable<
  Awaited<ReturnType<typeof institutionDeleteIcon>>
>;

export type InstitutionDeleteIconMutationError = unknown;

export const useInstitutionDeleteIcon = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof institutionDeleteIcon>>,
      TError,
      { trackerId: string; institutionId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof institutionDeleteIcon>>,
  TError,
  { trackerId: string; institutionId: string },
  TContext
> => {
  return useMutation(getInstitutionDeleteIconMutationOptions(options), queryClient);
};
export type institutionFindByIdResponse200 = {
  data: Blob;
  status: 200;
};

export type institutionFindByIdResponseSuccess = institutionFindByIdResponse200 & {
  headers: Headers;
};
export type institutionFindByIdResponse = institutionFindByIdResponseSuccess;

export const getInstitutionFindByIdUrl = (trackerId: string, institutionId: string) => {
  return `/api/institution/${trackerId}/${institutionId}`;
};

export const institutionFindById = async (
  trackerId: string,
  institutionId: string,
  options?: RequestInit,
): Promise<institutionFindByIdResponse> => {
  const res = await fetch(getInstitutionFindByIdUrl(trackerId, institutionId), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: institutionFindByIdResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as institutionFindByIdResponse;
};

export const getInstitutionFindByIdQueryKey = (trackerId: string, institutionId: string) => {
  return [`/api/institution/${trackerId}/${institutionId}`] as const;
};

export const getInstitutionFindByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof institutionFindById>>,
  TError = unknown,
>(
  trackerId: string,
  institutionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof institutionFindById>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getInstitutionFindByIdQueryKey(trackerId, institutionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof institutionFindById>>> = ({ signal }) =>
    institutionFindById(trackerId, institutionId, { signal, ...fetchOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(trackerId && institutionId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof institutionFindById>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type InstitutionFindByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof institutionFindById>>
>;
export type InstitutionFindByIdQueryError = unknown;

export function useInstitutionFindById<
  TData = Awaited<ReturnType<typeof institutionFindById>>,
  TError = unknown,
>(
  trackerId: string,
  institutionId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof institutionFindById>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof institutionFindById>>,
          TError,
          Awaited<ReturnType<typeof institutionFindById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInstitutionFindById<
  TData = Awaited<ReturnType<typeof institutionFindById>>,
  TError = unknown,
>(
  trackerId: string,
  institutionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof institutionFindById>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof institutionFindById>>,
          TError,
          Awaited<ReturnType<typeof institutionFindById>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInstitutionFindById<
  TData = Awaited<ReturnType<typeof institutionFindById>>,
  TError = unknown,
>(
  trackerId: string,
  institutionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof institutionFindById>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useInstitutionFindById<
  TData = Awaited<ReturnType<typeof institutionFindById>>,
  TError = unknown,
>(
  trackerId: string,
  institutionId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof institutionFindById>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInstitutionFindByIdQueryOptions(trackerId, institutionId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type institutionDeactivateResponse200 = {
  data: void;
  status: 200;
};

export type institutionDeactivateResponseSuccess = institutionDeactivateResponse200 & {
  headers: Headers;
};
export type institutionDeactivateResponse = institutionDeactivateResponseSuccess;

export const getInstitutionDeactivateUrl = (trackerId: string, institutionId: string) => {
  return `/api/institution/${trackerId}/${institutionId}`;
};

export const institutionDeactivate = async (
  trackerId: string,
  institutionId: string,
  options?: RequestInit,
): Promise<institutionDeactivateResponse> => {
  const res = await fetch(getInstitutionDeactivateUrl(trackerId, institutionId), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: institutionDeactivateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as institutionDeactivateResponse;
};

export const getInstitutionDeactivateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof institutionDeactivate>>,
    TError,
    { trackerId: string; institutionId: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof institutionDeactivate>>,
  TError,
  { trackerId: string; institutionId: string },
  TContext
> => {
  const mutationKey = ['institutionDeactivate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof institutionDeactivate>>,
    { trackerId: string; institutionId: string }
  > = (props) => {
    const { trackerId, institutionId } = props ?? {};

    return institutionDeactivate(trackerId, institutionId, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InstitutionDeactivateMutationResult = NonNullable<
  Awaited<ReturnType<typeof institutionDeactivate>>
>;

export type InstitutionDeactivateMutationError = unknown;

export const useInstitutionDeactivate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof institutionDeactivate>>,
      TError,
      { trackerId: string; institutionId: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof institutionDeactivate>>,
  TError,
  { trackerId: string; institutionId: string },
  TContext
> => {
  return useMutation(getInstitutionDeactivateMutationOptions(options), queryClient);
};
export type institutionUpdateResponse200 = {
  data: Blob;
  status: 200;
};

export type institutionUpdateResponseSuccess = institutionUpdateResponse200 & {
  headers: Headers;
};
export type institutionUpdateResponse = institutionUpdateResponseSuccess;

export const getInstitutionUpdateUrl = (trackerId: string, institutionId: string) => {
  return `/api/institution/${trackerId}/${institutionId}`;
};

export const institutionUpdate = async (
  trackerId: string,
  institutionId: string,
  updateInstitutionRequestDto: UpdateInstitutionRequestDto,
  options?: RequestInit,
): Promise<institutionUpdateResponse> => {
  const res = await fetch(getInstitutionUpdateUrl(trackerId, institutionId), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateInstitutionRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: institutionUpdateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as institutionUpdateResponse;
};

export const getInstitutionUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof institutionUpdate>>,
    TError,
    { trackerId: string; institutionId: string; data: UpdateInstitutionRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof institutionUpdate>>,
  TError,
  { trackerId: string; institutionId: string; data: UpdateInstitutionRequestDto },
  TContext
> => {
  const mutationKey = ['institutionUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof institutionUpdate>>,
    { trackerId: string; institutionId: string; data: UpdateInstitutionRequestDto }
  > = (props) => {
    const { trackerId, institutionId, data } = props ?? {};

    return institutionUpdate(trackerId, institutionId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InstitutionUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof institutionUpdate>>
>;
export type InstitutionUpdateMutationBody = UpdateInstitutionRequestDto;
export type InstitutionUpdateMutationError = unknown;

export const useInstitutionUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof institutionUpdate>>,
      TError,
      { trackerId: string; institutionId: string; data: UpdateInstitutionRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof institutionUpdate>>,
  TError,
  { trackerId: string; institutionId: string; data: UpdateInstitutionRequestDto },
  TContext
> => {
  return useMutation(getInstitutionUpdateMutationOptions(options), queryClient);
};
export type institutionDashboardResponse200 = {
  data: Blob;
  status: 200;
};

export type institutionDashboardResponseSuccess = institutionDashboardResponse200 & {
  headers: Headers;
};
export type institutionDashboardResponse = institutionDashboardResponseSuccess;

export const getInstitutionDashboardUrl = (
  trackerId: string,
  params?: InstitutionDashboardParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/institution/${trackerId}/dashboard?${stringifiedParams}`
    : `/api/institution/${trackerId}/dashboard`;
};

export const institutionDashboard = async (
  trackerId: string,
  params?: InstitutionDashboardParams,
  options?: RequestInit,
): Promise<institutionDashboardResponse> => {
  const res = await fetch(getInstitutionDashboardUrl(trackerId, params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: institutionDashboardResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as institutionDashboardResponse;
};

export const getInstitutionDashboardQueryKey = (
  trackerId: string,
  params?: InstitutionDashboardParams,
) => {
  return [`/api/institution/${trackerId}/dashboard`, ...(params ? [params] : [])] as const;
};

export const getInstitutionDashboardQueryOptions = <
  TData = Awaited<ReturnType<typeof institutionDashboard>>,
  TError = unknown,
>(
  trackerId: string,
  params?: InstitutionDashboardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof institutionDashboard>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInstitutionDashboardQueryKey(trackerId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof institutionDashboard>>> = ({ signal }) =>
    institutionDashboard(trackerId, params, { signal, ...fetchOptions });

  return { queryKey, queryFn, enabled: !!trackerId, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof institutionDashboard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InstitutionDashboardQueryResult = NonNullable<
  Awaited<ReturnType<typeof institutionDashboard>>
>;
export type InstitutionDashboardQueryError = unknown;

export function useInstitutionDashboard<
  TData = Awaited<ReturnType<typeof institutionDashboard>>,
  TError = unknown,
>(
  trackerId: string,
  params: undefined | InstitutionDashboardParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof institutionDashboard>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof institutionDashboard>>,
          TError,
          Awaited<ReturnType<typeof institutionDashboard>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInstitutionDashboard<
  TData = Awaited<ReturnType<typeof institutionDashboard>>,
  TError = unknown,
>(
  trackerId: string,
  params?: InstitutionDashboardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof institutionDashboard>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof institutionDashboard>>,
          TError,
          Awaited<ReturnType<typeof institutionDashboard>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInstitutionDashboard<
  TData = Awaited<ReturnType<typeof institutionDashboard>>,
  TError = unknown,
>(
  trackerId: string,
  params?: InstitutionDashboardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof institutionDashboard>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useInstitutionDashboard<
  TData = Awaited<ReturnType<typeof institutionDashboard>>,
  TError = unknown,
>(
  trackerId: string,
  params?: InstitutionDashboardParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof institutionDashboard>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInstitutionDashboardQueryOptions(trackerId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
