/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  AssetExchangeRateQuoteRequestDto,
  CreateAssetExchangeV2RequestDto,
  CreateWalletTransferV2RequestDto,
} from '../model';

export type createWalletTransferResponse200 = {
  data: Blob;
  status: 200;
};

export type createWalletTransferResponseSuccess = createWalletTransferResponse200 & {
  headers: Headers;
};
export type createWalletTransferResponse = createWalletTransferResponseSuccess;

export const getCreateWalletTransferUrl = (trackerId: string) => {
  return `/api/transaction-v2/${trackerId}/wallet-transfer`;
};

export const createWalletTransfer = async (
  trackerId: string,
  createWalletTransferV2RequestDto: CreateWalletTransferV2RequestDto,
  options?: RequestInit,
): Promise<createWalletTransferResponse> => {
  const res = await fetch(getCreateWalletTransferUrl(trackerId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createWalletTransferV2RequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createWalletTransferResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as createWalletTransferResponse;
};

export const getCreateWalletTransferMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createWalletTransfer>>,
    TError,
    { trackerId: string; data: CreateWalletTransferV2RequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createWalletTransfer>>,
  TError,
  { trackerId: string; data: CreateWalletTransferV2RequestDto },
  TContext
> => {
  const mutationKey = ['createWalletTransfer'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createWalletTransfer>>,
    { trackerId: string; data: CreateWalletTransferV2RequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return createWalletTransfer(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateWalletTransferMutationResult = NonNullable<
  Awaited<ReturnType<typeof createWalletTransfer>>
>;
export type CreateWalletTransferMutationBody = CreateWalletTransferV2RequestDto;
export type CreateWalletTransferMutationError = unknown;

export const useCreateWalletTransfer = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createWalletTransfer>>,
      TError,
      { trackerId: string; data: CreateWalletTransferV2RequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createWalletTransfer>>,
  TError,
  { trackerId: string; data: CreateWalletTransferV2RequestDto },
  TContext
> => {
  return useMutation(getCreateWalletTransferMutationOptions(options), queryClient);
};
export type createAssetExchangeResponse200 = {
  data: Blob;
  status: 200;
};

export type createAssetExchangeResponseSuccess = createAssetExchangeResponse200 & {
  headers: Headers;
};
export type createAssetExchangeResponse = createAssetExchangeResponseSuccess;

export const getCreateAssetExchangeUrl = (trackerId: string) => {
  return `/api/transaction-v2/${trackerId}/asset-exchange`;
};

export const createAssetExchange = async (
  trackerId: string,
  createAssetExchangeV2RequestDto: CreateAssetExchangeV2RequestDto,
  options?: RequestInit,
): Promise<createAssetExchangeResponse> => {
  const res = await fetch(getCreateAssetExchangeUrl(trackerId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createAssetExchangeV2RequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createAssetExchangeResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as createAssetExchangeResponse;
};

export const getCreateAssetExchangeMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createAssetExchange>>,
    TError,
    { trackerId: string; data: CreateAssetExchangeV2RequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createAssetExchange>>,
  TError,
  { trackerId: string; data: CreateAssetExchangeV2RequestDto },
  TContext
> => {
  const mutationKey = ['createAssetExchange'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createAssetExchange>>,
    { trackerId: string; data: CreateAssetExchangeV2RequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return createAssetExchange(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateAssetExchangeMutationResult = NonNullable<
  Awaited<ReturnType<typeof createAssetExchange>>
>;
export type CreateAssetExchangeMutationBody = CreateAssetExchangeV2RequestDto;
export type CreateAssetExchangeMutationError = unknown;

export const useCreateAssetExchange = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createAssetExchange>>,
      TError,
      { trackerId: string; data: CreateAssetExchangeV2RequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createAssetExchange>>,
  TError,
  { trackerId: string; data: CreateAssetExchangeV2RequestDto },
  TContext
> => {
  return useMutation(getCreateAssetExchangeMutationOptions(options), queryClient);
};
export type assetExchangeRateQuoteResponse200 = {
  data: Blob;
  status: 200;
};

export type assetExchangeRateQuoteResponseSuccess = assetExchangeRateQuoteResponse200 & {
  headers: Headers;
};
export type assetExchangeRateQuoteResponse = assetExchangeRateQuoteResponseSuccess;

export const getAssetExchangeRateQuoteUrl = (trackerId: string) => {
  return `/api/transaction-v2/${trackerId}/asset-exchange/rate`;
};

export const assetExchangeRateQuote = async (
  trackerId: string,
  assetExchangeRateQuoteRequestDto: AssetExchangeRateQuoteRequestDto,
  options?: RequestInit,
): Promise<assetExchangeRateQuoteResponse> => {
  const res = await fetch(getAssetExchangeRateQuoteUrl(trackerId), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(assetExchangeRateQuoteRequestDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: assetExchangeRateQuoteResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as assetExchangeRateQuoteResponse;
};

export const getAssetExchangeRateQuoteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof assetExchangeRateQuote>>,
    TError,
    { trackerId: string; data: AssetExchangeRateQuoteRequestDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof assetExchangeRateQuote>>,
  TError,
  { trackerId: string; data: AssetExchangeRateQuoteRequestDto },
  TContext
> => {
  const mutationKey = ['assetExchangeRateQuote'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof assetExchangeRateQuote>>,
    { trackerId: string; data: AssetExchangeRateQuoteRequestDto }
  > = (props) => {
    const { trackerId, data } = props ?? {};

    return assetExchangeRateQuote(trackerId, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AssetExchangeRateQuoteMutationResult = NonNullable<
  Awaited<ReturnType<typeof assetExchangeRateQuote>>
>;
export type AssetExchangeRateQuoteMutationBody = AssetExchangeRateQuoteRequestDto;
export type AssetExchangeRateQuoteMutationError = unknown;

export const useAssetExchangeRateQuote = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof assetExchangeRateQuote>>,
      TError,
      { trackerId: string; data: AssetExchangeRateQuoteRequestDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof assetExchangeRateQuote>>,
  TError,
  { trackerId: string; data: AssetExchangeRateQuoteRequestDto },
  TContext
> => {
  return useMutation(getAssetExchangeRateQuoteMutationOptions(options), queryClient);
};
