/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { AccountSummaryResponseDtoAccountType } from './accountSummaryResponseDtoAccountType';
import type { HoldingSummaryResponseDto } from './holdingSummaryResponseDto';

export interface AccountSummaryResponseDto {
  accountId?: string;
  accountName?: string;
  accountType?: AccountSummaryResponseDtoAccountType;
  iconUrl?: string;
  iconColor?: string;
  holdings?: HoldingSummaryResponseDto[];
  totalBalance?: number;
  convertedTotalBalance?: number;
}
