/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { AssetResponseDtoAssetType } from './assetResponseDtoAssetType';
import type { AssetResponseDtoMarketDataSource } from './assetResponseDtoMarketDataSource';

export interface AssetResponseDto {
  id?: string;
  code?: string;
  name?: string;
  assetType?: AssetResponseDtoAssetType;
  scale?: number;
  marketDataSource?: AssetResponseDtoMarketDataSource;
  marketDataKey?: string;
  active?: boolean;
  createdDate?: string;
  lastModifiedDate?: string;
}
