/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export interface AssetExchangeRateQuoteResponseDto {
  sourceHoldingId?: string;
  sourceAssetCode?: string;
  targetHoldingId?: string;
  targetAssetCode?: string;
  rateDate?: string;
  exchangeRate?: number;
}
