/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type BudgetPlanResponseDtoPeriodType =
  (typeof BudgetPlanResponseDtoPeriodType)[keyof typeof BudgetPlanResponseDtoPeriodType];

export const BudgetPlanResponseDtoPeriodType = {
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  QUARTERLY: 'QUARTERLY',
  YEARLY: 'YEARLY',
} as const;
