/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { BudgetPlanResponseDtoPeriodType } from './budgetPlanResponseDtoPeriodType';

export interface BudgetPlanResponseDto {
  id?: string;
  name?: string;
  amount?: number;
  currencyCode?: string;
  periodType?: BudgetPlanResponseDtoPeriodType;
  categoryId?: string;
  categoryName?: string;
  validFrom?: string;
  validTo?: string;
  active?: boolean;
  alreadySpent?: number;
  createdDate?: string;
  lastModifiedDate?: string;
}
