/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { BulkBudgetExportIssueDto } from './bulkBudgetExportIssueDto';
import type { BulkBudgetExportItemDto } from './bulkBudgetExportItemDto';

export interface BulkBudgetExportResponseDto {
  totalItems?: number;
  itemCount?: number;
  issueCount?: number;
  items?: BulkBudgetExportItemDto[];
  issues?: BulkBudgetExportIssueDto[];
}
