/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type BulkCreateCategoryRequestDtoCategoryKind =
  (typeof BulkCreateCategoryRequestDtoCategoryKind)[keyof typeof BulkCreateCategoryRequestDtoCategoryKind];

export const BulkCreateCategoryRequestDtoCategoryKind = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;
