/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export interface BulkBudgetImportSuccessDto {
  budgetPlanName?: string;
  period?: string;
  amount?: number;
  currency?: string;
  categoryName?: string;
  categoryMatched?: boolean;
  recurringCreated?: boolean;
}
