/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { BulkBudgetImportByCategoryIdIssueDto } from './bulkBudgetImportByCategoryIdIssueDto';
import type { BulkBudgetImportByCategoryIdItemDto } from './bulkBudgetImportByCategoryIdItemDto';

export interface BulkBudgetImportByCategoryIdRequestDto {
  totalItems?: number;
  itemCount?: number;
  issueCount?: number;
  items: BulkBudgetImportByCategoryIdItemDto[];
  issues?: BulkBudgetImportByCategoryIdIssueDto[];
}
