/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type CategoryActiveRowResponseCategoryKind =
  (typeof CategoryActiveRowResponseCategoryKind)[keyof typeof CategoryActiveRowResponseCategoryKind];

export const CategoryActiveRowResponseCategoryKind = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;
