/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { CategoryActiveBudgetPlanEmbed } from './categoryActiveBudgetPlanEmbed';
import type { CategoryActiveRowResponseCategoryKind } from './categoryActiveRowResponseCategoryKind';

export interface CategoryActiveRowResponse {
  id?: string;
  name?: string;
  categoryKind?: CategoryActiveRowResponseCategoryKind;
  parentId?: string;
  sortOrder?: number;
  budgetPlansForPeriod?: CategoryActiveBudgetPlanEmbed[];
}
