/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { CategoryActiveBudgetPlanDtoPeriodType } from './categoryActiveBudgetPlanDtoPeriodType';

export interface CategoryActiveBudgetPlanDto {
  id?: string;
  name?: string;
  amount?: number;
  currencyCode?: string;
  periodType?: CategoryActiveBudgetPlanDtoPeriodType;
  validFrom?: string;
  validTo?: string;
  active?: boolean;
  alreadySpent?: number;
  createdDate?: string;
  lastModifiedDate?: string;
}
