/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type CategoryCreateBulk200ItemCategoryKind =
  (typeof CategoryCreateBulk200ItemCategoryKind)[keyof typeof CategoryCreateBulk200ItemCategoryKind];

export const CategoryCreateBulk200ItemCategoryKind = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;
