/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { CategoryMovementAssetTotalsDto } from './categoryMovementAssetTotalsDto';
import type { CategoryMovementConvertedTotalsDto } from './categoryMovementConvertedTotalsDto';

export interface CategoryMovementSummaryResponseDto {
  dateFrom?: string;
  dateTo?: string;
  nativeByAsset?: CategoryMovementAssetTotalsDto[];
  convertedTotals?: CategoryMovementConvertedTotalsDto;
}
