/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export interface CategoryMovementAssetTotalsDto {
  assetCode?: string;
  assetScale?: number;
  expectedExpenseAmount?: number;
  expectedIncomeAmount?: number;
  expectedSavingAmount?: number;
  actualExpenseAmount?: number;
  actualIncomeAmount?: number;
  actualSavingAmount?: number;
}
