/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { CategoryBulkExportResponseDtoCategoryKind } from './categoryBulkExportResponseDtoCategoryKind';

export interface CategoryBulkExportResponseDto {
  name?: string;
  categoryKind?: CategoryBulkExportResponseDtoCategoryKind;
  sortOrder?: number;
}
