/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type CreateWalletTransferV2ResponseDtoCalculationMode =
  (typeof CreateWalletTransferV2ResponseDtoCalculationMode)[keyof typeof CreateWalletTransferV2ResponseDtoCalculationMode];

export const CreateWalletTransferV2ResponseDtoCalculationMode = {
  AMOUNT_ONLY_DEFAULTED: 'AMOUNT_ONLY_DEFAULTED',
  SETTLED_ONLY_DEFAULTED: 'SETTLED_ONLY_DEFAULTED',
  AMOUNT_AND_FEE: 'AMOUNT_AND_FEE',
  SETTLED_AND_FEE: 'SETTLED_AND_FEE',
  AMOUNT_AND_SETTLED: 'AMOUNT_AND_SETTLED',
  ALL_FIELDS_RECONCILED: 'ALL_FIELDS_RECONCILED',
} as const;
