/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type CreateGoalPlanRequestDtoCarbStrategy =
  (typeof CreateGoalPlanRequestDtoCarbStrategy)[keyof typeof CreateGoalPlanRequestDtoCarbStrategy];

export const CreateGoalPlanRequestDtoCarbStrategy = {
  REMAINDER: 'REMAINDER',
  FIXED: 'FIXED',
  CUSTOM: 'CUSTOM',
} as const;
