/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type CreateAccountRequestDtoAccountType =
  (typeof CreateAccountRequestDtoAccountType)[keyof typeof CreateAccountRequestDtoAccountType];

export const CreateAccountRequestDtoAccountType = {
  CASH: 'CASH',
  BANK_ACCOUNT: 'BANK_ACCOUNT',
  CREDIT_CARD: 'CREDIT_CARD',
  SAVINGS: 'SAVINGS',
  INVESTMENT: 'INVESTMENT',
  EXCHANGE_SPOT: 'EXCHANGE_SPOT',
  OTHER: 'OTHER',
} as const;
