/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { CreateInstitutionRequestDtoInstitutionType } from './createInstitutionRequestDtoInstitutionType';

export interface CreateInstitutionRequestDto {
  /** @minLength 1 */
  name: string;
  institutionType: CreateInstitutionRequestDtoInstitutionType;
  description?: string;
}
