/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { CreateCategoryBulkRequestDtoCategoryKind } from './createCategoryBulkRequestDtoCategoryKind';

export interface CreateCategoryBulkRequestDto {
  /** @minLength 1 */
  name: string;
  categoryKind: CreateCategoryBulkRequestDtoCategoryKind;
  sortOrder?: number;
  children?: CreateCategoryBulkRequestDto[];
}
