/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { CreateRecurringTransactionRequestDtoPeriodType } from './createRecurringTransactionRequestDtoPeriodType';
import type { CreateRecurringTransactionRequestDtoTransactionType } from './createRecurringTransactionRequestDtoTransactionType';

export interface CreateRecurringTransactionRequestDto {
  transactionType: CreateRecurringTransactionRequestDtoTransactionType;
  walletId: string;
  categoryId?: string;
  amount: number;
  currencyCode: string;
  description?: string;
  note?: string;
  periodType: CreateRecurringTransactionRequestDtoPeriodType;
  intervalValue?: number;
  startDate: string;
  endDate?: string;
}
