/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { CreateRecurringBudgetRequestDtoPeriodType } from './createRecurringBudgetRequestDtoPeriodType';

export interface CreateRecurringBudgetRequestDto {
  /** @minLength 1 */
  name: string;
  amount: number;
  /** @minLength 1 */
  currencyCode: string;
  periodType: CreateRecurringBudgetRequestDtoPeriodType;
  intervalValue?: number;
  startDate: string;
  endDate?: string;
  categoryId?: string;
}
