/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { CreateAccountRequestDtoAccountType } from './createAccountRequestDtoAccountType';

export interface CreateAccountRequestDto {
  institutionId: string;
  /** @minLength 1 */
  name: string;
  accountType: CreateAccountRequestDtoAccountType;
  description?: string;
  externalRef?: string;
}
