/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { CreateTransactionRequestDtoTransactionType } from './createTransactionRequestDtoTransactionType';

export interface CreateTransactionRequestDto {
  transactionType: CreateTransactionRequestDtoTransactionType;
  holdingId?: string;
  sourceHoldingId?: string;
  targetHoldingId?: string;
  categoryId?: string;
  amount?: number;
  correctedBalance?: number;
  currencyCode?: string;
  exchangeRate?: number;
  feeAmount?: number;
  transactionDate: string;
  description?: string;
  note?: string;
  externalRef?: string;
}
