/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type CreateCategoryRequestDtoCategoryKind =
  (typeof CreateCategoryRequestDtoCategoryKind)[keyof typeof CreateCategoryRequestDtoCategoryKind];

export const CreateCategoryRequestDtoCategoryKind = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;
