/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type CreateGoalPlanRequestDtoStartBodyFatSource =
  (typeof CreateGoalPlanRequestDtoStartBodyFatSource)[keyof typeof CreateGoalPlanRequestDtoStartBodyFatSource];

export const CreateGoalPlanRequestDtoStartBodyFatSource = {
  MANUAL: 'MANUAL',
  CIRCUMFERENCE: 'CIRCUMFERENCE',
} as const;
