/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type CreateCategoryBulkRequestDtoCategoryKind =
  (typeof CreateCategoryBulkRequestDtoCategoryKind)[keyof typeof CreateCategoryBulkRequestDtoCategoryKind];

export const CreateCategoryBulkRequestDtoCategoryKind = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
} as const;
