/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type CreateGoalPlanRequestDtoFatStrategy =
  (typeof CreateGoalPlanRequestDtoFatStrategy)[keyof typeof CreateGoalPlanRequestDtoFatStrategy];

export const CreateGoalPlanRequestDtoFatStrategy = {
  STANDARD: 'STANDARD',
  HIGHER: 'HIGHER',
  CUSTOM: 'CUSTOM',
} as const;
