/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type CreateAssetExchangeV2ResponseDtoOperationType =
  (typeof CreateAssetExchangeV2ResponseDtoOperationType)[keyof typeof CreateAssetExchangeV2ResponseDtoOperationType];

export const CreateAssetExchangeV2ResponseDtoOperationType = {
  WALLET_TRANSFER: 'WALLET_TRANSFER',
  ASSET_EXCHANGE: 'ASSET_EXCHANGE',
} as const;
