/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type CreateGoalPlanRequestDtoProteinStrategy =
  (typeof CreateGoalPlanRequestDtoProteinStrategy)[keyof typeof CreateGoalPlanRequestDtoProteinStrategy];

export const CreateGoalPlanRequestDtoProteinStrategy = {
  STANDARD: 'STANDARD',
  HIGH: 'HIGH',
  CUSTOM: 'CUSTOM',
} as const;
