/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { CreateAssetRequestDtoAssetType } from './createAssetRequestDtoAssetType';
import type { CreateAssetRequestDtoMarketDataSource } from './createAssetRequestDtoMarketDataSource';

export interface CreateAssetRequestDto {
  /** @minLength 1 */
  code: string;
  /** @minLength 1 */
  name: string;
  assetType: CreateAssetRequestDtoAssetType;
  scale: number;
  marketDataSource: CreateAssetRequestDtoMarketDataSource;
  marketDataKey?: string;
}
