/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type DailyBodyMeasurementLogResponseDtoBodyFatSource =
  (typeof DailyBodyMeasurementLogResponseDtoBodyFatSource)[keyof typeof DailyBodyMeasurementLogResponseDtoBodyFatSource];

export const DailyBodyMeasurementLogResponseDtoBodyFatSource = {
  MANUAL: 'MANUAL',
  CIRCUMFERENCE: 'CIRCUMFERENCE',
} as const;
