/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { DailyBodyMeasurementLogResponseDtoBodyFatSource } from './dailyBodyMeasurementLogResponseDtoBodyFatSource';

export interface DailyBodyMeasurementLogResponseDto {
  id?: string;
  expenseTrackerId?: string;
  goalPlanId?: string;
  logDate?: string;
  waistCm?: number;
  neckCm?: number;
  hipCm?: number;
  calculatedBodyFatPercent?: number;
  bodyFatSource?: DailyBodyMeasurementLogResponseDtoBodyFatSource;
  createdDate?: string;
  lastModifiedDate?: string;
}
