/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { DailyBodyMeasurementLogResponseDto } from './dailyBodyMeasurementLogResponseDto';
import type { DailyNutritionLogResponseDto } from './dailyNutritionLogResponseDto';

export interface DailyCheckinResponseDto {
  nutritionLog?: DailyNutritionLogResponseDto;
  bodyMeasurementLog?: DailyBodyMeasurementLogResponseDto;
}
