/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { ExpenseTrackerAccessRequestResponseDtoStatus } from './expenseTrackerAccessRequestResponseDtoStatus';
import type { ExpenseTrackerAccessRequestResponseDtoType } from './expenseTrackerAccessRequestResponseDtoType';

export interface ExpenseTrackerAccessRequestResponseDto {
  id?: string;
  expenseTrackerId?: string;
  expenseTrackerName?: string;
  userId?: string;
  userFullName?: string;
  userEmail?: string;
  status?: ExpenseTrackerAccessRequestResponseDtoStatus;
  type?: ExpenseTrackerAccessRequestResponseDtoType;
  requestDate?: string;
  approvalDate?: string;
  approvedByFullName?: string;
  invitedByFullName?: string;
}
