/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type ExpenseTrackerAccessRequestResponseDtoType =
  (typeof ExpenseTrackerAccessRequestResponseDtoType)[keyof typeof ExpenseTrackerAccessRequestResponseDtoType];

export const ExpenseTrackerAccessRequestResponseDtoType = {
  REQUEST: 'REQUEST',
  INVITE: 'INVITE',
} as const;
