/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type ExpenseTrackerAccessRequestResponseDtoStatus =
  (typeof ExpenseTrackerAccessRequestResponseDtoStatus)[keyof typeof ExpenseTrackerAccessRequestResponseDtoStatus];

export const ExpenseTrackerAccessRequestResponseDtoStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const;
