/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { FinanceHeaderNativeBalanceRow } from './financeHeaderNativeBalanceRow';

export interface FinanceHeaderBalancesResponse {
  periodFrom?: string;
  periodTo?: string;
  displayAssetCode?: string;
  displayAssetScale?: number;
  grandTotalConverted?: number;
  nativeBalances?: FinanceHeaderNativeBalanceRow[];
}
