/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type GoalPlanResponseDtoCarbStrategy =
  (typeof GoalPlanResponseDtoCarbStrategy)[keyof typeof GoalPlanResponseDtoCarbStrategy];

export const GoalPlanResponseDtoCarbStrategy = {
  REMAINDER: 'REMAINDER',
  FIXED: 'FIXED',
  CUSTOM: 'CUSTOM',
} as const;
