/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type GoalPlanResponseDtoFatStrategy =
  (typeof GoalPlanResponseDtoFatStrategy)[keyof typeof GoalPlanResponseDtoFatStrategy];

export const GoalPlanResponseDtoFatStrategy = {
  STANDARD: 'STANDARD',
  HIGHER: 'HIGHER',
  CUSTOM: 'CUSTOM',
} as const;
