/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type GoalPlanResponseDtoProteinStrategy =
  (typeof GoalPlanResponseDtoProteinStrategy)[keyof typeof GoalPlanResponseDtoProteinStrategy];

export const GoalPlanResponseDtoProteinStrategy = {
  STANDARD: 'STANDARD',
  HIGH: 'HIGH',
  CUSTOM: 'CUSTOM',
} as const;
