/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type GoalPlanResponseDtoGoalType =
  (typeof GoalPlanResponseDtoGoalType)[keyof typeof GoalPlanResponseDtoGoalType];

export const GoalPlanResponseDtoGoalType = {
  FAT_LOSS: 'FAT_LOSS',
  MAINTENANCE: 'MAINTENANCE',
  MUSCLE_GAIN: 'MUSCLE_GAIN',
  CUSTOM: 'CUSTOM',
} as const;
