/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { GoalPlanResponseDtoCarbStrategy } from './goalPlanResponseDtoCarbStrategy';
import type { GoalPlanResponseDtoFatStrategy } from './goalPlanResponseDtoFatStrategy';
import type { GoalPlanResponseDtoGoalType } from './goalPlanResponseDtoGoalType';
import type { GoalPlanResponseDtoProteinStrategy } from './goalPlanResponseDtoProteinStrategy';
import type { GoalPlanResponseDtoStartBodyFatSource } from './goalPlanResponseDtoStartBodyFatSource';
import type { NutritionTargetResponseDto } from './nutritionTargetResponseDto';

export interface GoalPlanResponseDto {
  id?: string;
  expenseTrackerId?: string;
  nutritionProfileId?: string;
  name?: string;
  goalType?: GoalPlanResponseDtoGoalType;
  startDate?: string;
  endDate?: string;
  startWeightKg?: number;
  startBodyFatPercent?: number;
  startBodyFatSource?: GoalPlanResponseDtoStartBodyFatSource;
  targetWeeklyWeightChangeKg?: number;
  proteinStrategy?: GoalPlanResponseDtoProteinStrategy;
  fatStrategy?: GoalPlanResponseDtoFatStrategy;
  carbStrategy?: GoalPlanResponseDtoCarbStrategy;
  active?: boolean;
  notes?: string;
  createdDate?: string;
  lastModifiedDate?: string;
  initialNutritionTarget?: NutritionTargetResponseDto;
}
