/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { HabitAgendaItemDto } from './habitAgendaItemDto';
import type { HabitDayBlockOverviewDtoDayBlock } from './habitDayBlockOverviewDtoDayBlock';

export interface HabitDayBlockOverviewDto {
  dayBlock?: HabitDayBlockOverviewDtoDayBlock;
  items?: HabitAgendaItemDto[];
}
