/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { HabitResponseDtoHabitType } from './habitResponseDtoHabitType';
import type { HabitScheduleSlotResponseDto } from './habitScheduleSlotResponseDto';

export interface HabitResponseDto {
  id?: string;
  name?: string;
  description?: string;
  habitType?: HabitResponseDtoHabitType;
  expectedMinutes?: number;
  validFrom?: string;
  validTo?: string;
  active?: boolean;
  sortOrder?: number;
  satisfactionScore?: number;
  utilityScore?: number;
  estimatedPrice?: number;
  scheduleSlots?: HabitScheduleSlotResponseDto[];
  createdDate?: string;
  lastModifiedDate?: string;
}
