/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type HabitCompletionUpsertRequestDtoStatus =
  (typeof HabitCompletionUpsertRequestDtoStatus)[keyof typeof HabitCompletionUpsertRequestDtoStatus];

export const HabitCompletionUpsertRequestDtoStatus = {
  DONE: 'DONE',
  SKIPPED: 'SKIPPED',
  MISSED: 'MISSED',
  PARTIALLY_COMPLETED: 'PARTIALLY_COMPLETED',
} as const;
