/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type HabitAgendaItemDtoHabitType =
  (typeof HabitAgendaItemDtoHabitType)[keyof typeof HabitAgendaItemDtoHabitType];

export const HabitAgendaItemDtoHabitType = {
  PHYSICAL: 'PHYSICAL',
  MENTAL: 'MENTAL',
  EDUCATIONAL: 'EDUCATIONAL',
  SOCIAL: 'SOCIAL',
  HEALTH: 'HEALTH',
  SLEEP: 'SLEEP',
  DISCIPLINE: 'DISCIPLINE',
  HOUSEHOLD: 'HOUSEHOLD',
  OTHER: 'OTHER',
} as const;
