/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { HabitAgendaItemDtoDayBlocksItem } from './habitAgendaItemDtoDayBlocksItem';
import type { HabitAgendaItemDtoHabitType } from './habitAgendaItemDtoHabitType';
import type { HabitCompletionStateDto } from './habitCompletionStateDto';

export interface HabitAgendaItemDto {
  habitId?: string;
  name?: string;
  description?: string;
  habitType?: HabitAgendaItemDtoHabitType;
  expectedMinutes?: number;
  sortOrder?: number;
  satisfactionScore?: number;
  utilityScore?: number;
  estimatedPrice?: number;
  dayBlocks?: HabitAgendaItemDtoDayBlocksItem[];
  completion?: HabitCompletionStateDto;
}
