/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type HabitCompletionStateDtoStatus =
  (typeof HabitCompletionStateDtoStatus)[keyof typeof HabitCompletionStateDtoStatus];

export const HabitCompletionStateDtoStatus = {
  DONE: 'DONE',
  SKIPPED: 'SKIPPED',
  MISSED: 'MISSED',
  PARTIALLY_COMPLETED: 'PARTIALLY_COMPLETED',
} as const;
