/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type HabitScheduleSlotResponseDtoDayBlock =
  (typeof HabitScheduleSlotResponseDtoDayBlock)[keyof typeof HabitScheduleSlotResponseDtoDayBlock];

export const HabitScheduleSlotResponseDtoDayBlock = {
  RANO: 'RANO',
  DOPOLEDNE: 'DOPOLEDNE',
  ODPOLEDNE: 'ODPOLEDNE',
  VECER: 'VECER',
  PRED_SPANIM: 'PRED_SPANIM',
} as const;
