/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { HabitCompletionStateDtoStatus } from './habitCompletionStateDtoStatus';

export interface HabitCompletionStateDto {
  completionId?: string;
  date?: string;
  status?: HabitCompletionStateDtoStatus;
  note?: string;
  completedAt?: string;
}
