/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { HabitScheduleSlotResponseDtoDayBlock } from './habitScheduleSlotResponseDtoDayBlock';
import type { HabitScheduleSlotResponseDtoDayOfWeek } from './habitScheduleSlotResponseDtoDayOfWeek';

export interface HabitScheduleSlotResponseDto {
  id?: string;
  dayOfWeek?: HabitScheduleSlotResponseDtoDayOfWeek;
  dayBlock?: HabitScheduleSlotResponseDtoDayBlock;
  sortOrder?: number;
}
