/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { HabitScheduleSlotRequestDto } from './habitScheduleSlotRequestDto';
import type { HabitUpsertRequestDtoHabitType } from './habitUpsertRequestDtoHabitType';

export interface HabitUpsertRequestDto {
  name?: string;
  description?: string;
  habitType?: HabitUpsertRequestDtoHabitType;
  expectedMinutes?: number;
  validFrom?: string;
  validTo?: string;
  active?: boolean;
  sortOrder?: number;
  scheduleSlots?: HabitScheduleSlotRequestDto[];
}
