/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type HoldingResponseDtoAssetType =
  (typeof HoldingResponseDtoAssetType)[keyof typeof HoldingResponseDtoAssetType];

export const HoldingResponseDtoAssetType = {
  FIAT: 'FIAT',
  CRYPTO: 'CRYPTO',
  OTHER: 'OTHER',
} as const;
