/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { CategoryBreakdownDto } from './categoryBreakdownDto';

export interface HoldingSummaryResponseDto {
  holdingId?: string;
  accountName?: string;
  institutionName?: string;
  assetCode?: string;
  assetScale?: number;
  periodFrom?: string;
  periodTo?: string;
  startBalance?: number;
  endBalance?: number;
  totalIncome?: number;
  totalExpense?: number;
  totalTransferIn?: number;
  totalTransferOut?: number;
  difference?: number;
  incomeByCategory?: CategoryBreakdownDto[];
  expenseByCategory?: CategoryBreakdownDto[];
  convertedStartBalance?: number;
  convertedEndBalance?: number;
  exchangeRate?: number;
}
