/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { HoldingSummaryResponseDto } from './holdingSummaryResponseDto';
import type { WidgetItemResponseDto } from './widgetItemResponseDto';

export interface HoldingDashboardResponseDto {
  periodFrom?: string;
  periodTo?: string;
  widgetOrder?: WidgetItemResponseDto[];
  holdings?: HoldingSummaryResponseDto[];
}
