/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { HoldingResponseDtoAccountType } from './holdingResponseDtoAccountType';
import type { HoldingResponseDtoAssetType } from './holdingResponseDtoAssetType';
import type { HoldingResponseDtoInstitutionType } from './holdingResponseDtoInstitutionType';

export interface HoldingResponseDto {
  id?: string;
  accountId?: string;
  accountName?: string;
  accountType?: HoldingResponseDtoAccountType;
  institutionId?: string;
  institutionName?: string;
  institutionType?: HoldingResponseDtoInstitutionType;
  assetId?: string;
  assetCode?: string;
  assetName?: string;
  assetType?: HoldingResponseDtoAssetType;
  assetScale?: number;
  initialAmount?: number;
  currentAmount?: number;
  active?: boolean;
  createdDate?: string;
  lastModifiedDate?: string;
}
