/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { InstitutionResponseDtoInstitutionType } from './institutionResponseDtoInstitutionType';

export interface InstitutionResponseDto {
  id?: string;
  name?: string;
  institutionType?: InstitutionResponseDtoInstitutionType;
  description?: string;
  iconUrl?: string;
  iconColor?: string;
  active?: boolean;
  createdDate?: string;
  lastModifiedDate?: string;
}
