/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type InstitutionResponseDtoInstitutionType =
  (typeof InstitutionResponseDtoInstitutionType)[keyof typeof InstitutionResponseDtoInstitutionType];

export const InstitutionResponseDtoInstitutionType = {
  BANK: 'BANK',
  EXCHANGE: 'EXCHANGE',
  BROKER: 'BROKER',
  PERSONAL: 'PERSONAL',
  OTHER: 'OTHER',
} as const;
