/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export interface KanbanChecklistItemUpsertRequestDto {
  /**
   * @minLength 0
   * @maxLength 180
   */
  title: string;
  itemOrder?: number;
}
