/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export interface KanbanTagResponseDto {
  id?: string;
  name?: string;
  color?: string;
  active?: boolean;
  createdDate?: string;
  lastModifiedDate?: string;
}
