/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { KanbanCardResponseDto } from './kanbanCardResponseDto';

export interface KanbanStageCardsResponseDto {
  id?: string;
  name?: string;
  stageOrder?: number;
  color?: string;
  visibleOnBoard?: boolean;
  cards?: KanbanCardResponseDto[];
}
