/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export interface KanbanCardUpsertRequestDto {
  stageId?: string;
  /**
   * @minLength 0
   * @maxLength 180
   */
  title: string;
  /**
   * @minLength 0
   * @maxLength 1000
   */
  description?: string;
  /** @pattern ^(https?://res\.cloudinary\.com/.+)?$ */
  imageUrl?: string;
  /** @maximum 10 */
  priority?: number;
  dueDate?: string;
  completed?: boolean;
  cardOrder?: number;
  tagIds?: string[];
}
