/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export interface KanbanBoardUpsertRequestDto {
  /**
   * @minLength 0
   * @maxLength 120
   */
  name: string;
  /**
   * @minLength 0
   * @maxLength 500
   */
  description?: string;
  boardOrder?: number;
  active?: boolean;
}
