/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { KanbanCardReorderItemDto } from './kanbanCardReorderItemDto';

export interface KanbanCardReorderRequestDto {
  stageId: string;
  /** @minItems 1 */
  items: KanbanCardReorderItemDto[];
}
