/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export interface KanbanStageUpsertRequestDto {
  /**
   * @minLength 0
   * @maxLength 80
   */
  name: string;
  stageOrder?: number;
  /** @pattern ^#([A-Fa-f0-9]{6})$ */
  color?: string;
  visibleOnBoard?: boolean;
  active?: boolean;
}
