/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export interface KanbanTagUpsertRequestDto {
  /**
   * @minLength 0
   * @maxLength 80
   */
  name: string;
  /** @pattern ^#([A-Fa-f0-9]{6})$ */
  color?: string;
  active?: boolean;
}
