/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { KanbanStageCardsResponseDto } from './kanbanStageCardsResponseDto';

export interface KanbanBoardSnapshotResponseDto {
  boardId?: string;
  boardName?: string;
  stages?: KanbanStageCardsResponseDto[];
}
