/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export interface ManualNutritionTargetRequestDto {
  effectiveFrom?: string;
  baselineTdeeKcal?: number;
  calorieAdjustmentKcal?: number;
  targetCaloriesKcal?: number;
  targetProteinG?: number;
  targetFatG?: number;
  targetCarbsG?: number;
  reasonDetail?: string;
}
