/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export interface NutritionSummaryWeekDto {
  weekIndex?: number;
  weekStartDate?: string;
  weekEndDate?: string;
  avgWeightKg?: number;
  avgCaloriesKcal?: number;
  bodyFatPercent?: number;
  weightChangeFromStartKg?: number;
  weightChangeFromPreviousCheckinKg?: number;
  avgEstimatedTdeeKcal?: number;
}
