/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type NutritionSummaryResponseDtoGoalType =
  (typeof NutritionSummaryResponseDtoGoalType)[keyof typeof NutritionSummaryResponseDtoGoalType];

export const NutritionSummaryResponseDtoGoalType = {
  FAT_LOSS: 'FAT_LOSS',
  MAINTENANCE: 'MAINTENANCE',
  MUSCLE_GAIN: 'MUSCLE_GAIN',
  CUSTOM: 'CUSTOM',
} as const;
