/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { NutritionProfileResponseDtoBiologicalSex } from './nutritionProfileResponseDtoBiologicalSex';
import type { NutritionProfileResponseDtoPreferredUnitSystem } from './nutritionProfileResponseDtoPreferredUnitSystem';

export interface NutritionProfileResponseDto {
  id?: string;
  expenseTrackerId?: string;
  preferredUnitSystem?: NutritionProfileResponseDtoPreferredUnitSystem;
  biologicalSex?: NutritionProfileResponseDtoBiologicalSex;
  heightCm?: number;
  activityMultiplier?: number;
  bodyFatAutoCalculationEnabled?: boolean;
  createdDate?: string;
  lastModifiedDate?: string;
}
