/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { DailyNutritionLogResponseDto } from './dailyNutritionLogResponseDto';
import type { PageMetadata } from './pageMetadata';

export interface PagedModelDailyNutritionLogResponseDto {
  content?: DailyNutritionLogResponseDto[];
  page?: PageMetadata;
}
