/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { ExpenseTrackerAccessRequestResponseDto } from './expenseTrackerAccessRequestResponseDto';
import type { PageMetadata } from './pageMetadata';

export interface PagedModelExpenseTrackerAccessRequestResponseDto {
  content?: ExpenseTrackerAccessRequestResponseDto[];
  page?: PageMetadata;
}
