/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { RecurringTransactionResponseDtoPeriodType } from './recurringTransactionResponseDtoPeriodType';
import type { RecurringTransactionResponseDtoTransactionType } from './recurringTransactionResponseDtoTransactionType';

export interface RecurringTransactionResponseDto {
  id?: string;
  transactionType?: RecurringTransactionResponseDtoTransactionType;
  holdingId?: string;
  holdingName?: string;
  categoryId?: string;
  categoryName?: string;
  amount?: number;
  currencyCode?: string;
  description?: string;
  note?: string;
  periodType?: RecurringTransactionResponseDtoPeriodType;
  intervalValue?: number;
  startDate?: string;
  endDate?: string;
  nextRunDate?: string;
  active?: boolean;
  createdDate?: string;
  lastModifiedDate?: string;
}
