/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type RecurringTransactionResponseDtoTransactionType =
  (typeof RecurringTransactionResponseDtoTransactionType)[keyof typeof RecurringTransactionResponseDtoTransactionType];

export const RecurringTransactionResponseDtoTransactionType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
  TRANSFER: 'TRANSFER',
  BALANCE_ADJUSTMENT: 'BALANCE_ADJUSTMENT',
} as const;
