/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { RecurringBudgetResponseDtoPeriodType } from './recurringBudgetResponseDtoPeriodType';

export interface RecurringBudgetResponseDto {
  id?: string;
  name?: string;
  amount?: number;
  assetCode?: string;
  assetScale?: number;
  periodType?: RecurringBudgetResponseDtoPeriodType;
  intervalValue?: number;
  categoryId?: string;
  categoryName?: string;
  startDate?: string;
  endDate?: string;
  nextRunDate?: string;
  active?: boolean;
  createdDate?: string;
  lastModifiedDate?: string;
}
