/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { TodoUpsertRequestDtoPriority } from './todoUpsertRequestDtoPriority';
import type { TodoUpsertRequestDtoStatus } from './todoUpsertRequestDtoStatus';

export interface TodoUpsertRequestDto {
  parentTodoId?: string;
  /**
   * @minLength 0
   * @maxLength 180
   */
  title: string;
  /**
   * @minLength 0
   * @maxLength 1000
   */
  description?: string;
  /** @pattern ^(https?://res\.cloudinary\.com/.+)?$ */
  imageUrl?: string;
  status?: TodoUpsertRequestDtoStatus;
  priority?: TodoUpsertRequestDtoPriority;
  dueDate?: string;
  estimatedMinutes?: number;
  /**
   * @minLength 0
   * @maxLength 1000
   */
  note?: string;
  sortOrder?: number;
  active?: boolean;
  tagIds?: string[];
}
