/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type TodoFindTree200ItemPriority =
  (typeof TodoFindTree200ItemPriority)[keyof typeof TodoFindTree200ItemPriority];

export const TodoFindTree200ItemPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;
