/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type TodoUpsertRequestDtoPriority =
  (typeof TodoUpsertRequestDtoPriority)[keyof typeof TodoUpsertRequestDtoPriority];

export const TodoUpsertRequestDtoPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;
