/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type TransactionFindAllPageableRateMode =
  (typeof TransactionFindAllPageableRateMode)[keyof typeof TransactionFindAllPageableRateMode];

export const TransactionFindAllPageableRateMode = {
  NOW: 'NOW',
  TRANSACTION_DATE: 'TRANSACTION_DATE',
} as const;
