/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type TransactionFindAllPageableTransactionType =
  (typeof TransactionFindAllPageableTransactionType)[keyof typeof TransactionFindAllPageableTransactionType];

export const TransactionFindAllPageableTransactionType = {
  INCOME: 'INCOME',
  EXPENSE: 'EXPENSE',
  TRANSFER: 'TRANSFER',
  BALANCE_ADJUSTMENT: 'BALANCE_ADJUSTMENT',
  TEST: 'TEST',
} as const;
