/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { PageMetaDto } from './pageMetaDto';
import type { TransactionPageItemResponseDto } from './transactionPageItemResponseDto';
import type { TransactionTotalsDto } from './transactionTotalsDto';

export interface TransactionPageResponseDto {
  content?: TransactionPageItemResponseDto[];
  page?: PageMetaDto;
  totals?: TransactionTotalsDto;
}
