/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { TransactionFindAllPageableStatus } from './transactionFindAllPageableStatus';
import type { TransactionFindAllPageableTransactionType } from './transactionFindAllPageableTransactionType';

export type TransactionFindAllPageableParams = {
  search?: string;
  categoryId?: string;
  holdingId?: string;
  transactionType?: TransactionFindAllPageableTransactionType;
  status?: TransactionFindAllPageableStatus;
  dateFrom?: string;
  dateTo?: string;
  /**
   * Zero-based page index (0..N)
   * @minimum 0
   */
  page?: number;
  /**
   * The size of the page to be returned
   * @minimum 1
   */
  size?: number;
  /**
   * Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
   */
  sort?: string[];
};
