/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { TransactionAttachmentResponseDto } from './transactionAttachmentResponseDto';
import type { TransactionResponseDtoBalanceAdjustmentDirection } from './transactionResponseDtoBalanceAdjustmentDirection';
import type { TransactionResponseDtoStatus } from './transactionResponseDtoStatus';
import type { TransactionResponseDtoTransactionType } from './transactionResponseDtoTransactionType';

export interface TransactionResponseDto {
  id?: string;
  transactionType?: TransactionResponseDtoTransactionType;
  status?: TransactionResponseDtoStatus;
  holdingId?: string;
  holdingName?: string;
  sourceHoldingId?: string;
  sourceHoldingName?: string;
  targetHoldingId?: string;
  targetHoldingName?: string;
  categoryId?: string;
  categoryName?: string;
  rootCategoryId?: string;
  rootCategoryName?: string;
  amount?: number;
  assetCode?: string;
  assetScale?: number;
  exchangeRate?: number;
  feeAmount?: number;
  settledAmount?: number;
  balanceAdjustmentDirection?: TransactionResponseDtoBalanceAdjustmentDirection;
  transactionDate?: string;
  description?: string;
  note?: string;
  externalRef?: string;
  attachments?: TransactionAttachmentResponseDto[];
  createdDate?: string;
  lastModifiedDate?: string;
}
