/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { TransactionV2ResponseDtoCalculationMode } from './transactionV2ResponseDtoCalculationMode';
import type { TransactionV2ResponseDtoOperationType } from './transactionV2ResponseDtoOperationType';

export interface TransactionV2ResponseDto {
  transactionId?: string;
  operationType?: TransactionV2ResponseDtoOperationType;
  calculationMode?: TransactionV2ResponseDtoCalculationMode;
  amount?: number;
  settledAmount?: number;
  feeAmount?: number;
  sourceDeduction?: number;
  targetAddition?: number;
  feeOverridden?: boolean;
  sourceHoldingId?: string;
  targetHoldingId?: string;
  sourceAssetCode?: string;
  targetAssetCode?: string;
  currencyCode?: string;
  exchangeRate?: number;
  transactionDate?: string;
}
