/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type TransactionFindAllPageableStatus =
  (typeof TransactionFindAllPageableStatus)[keyof typeof TransactionFindAllPageableStatus];

export const TransactionFindAllPageableStatus = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;
