/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { TransactionAttachmentResponseDto } from './transactionAttachmentResponseDto';
import type { TransactionPageItemResponseDtoBalanceAdjustmentDirection } from './transactionPageItemResponseDtoBalanceAdjustmentDirection';
import type { TransactionPageItemResponseDtoStatus } from './transactionPageItemResponseDtoStatus';
import type { TransactionPageItemResponseDtoTransactionType } from './transactionPageItemResponseDtoTransactionType';

export interface TransactionPageItemResponseDto {
  id?: string;
  transactionType?: TransactionPageItemResponseDtoTransactionType;
  status?: TransactionPageItemResponseDtoStatus;
  holdingId?: string;
  holdingName?: string;
  sourceHoldingId?: string;
  sourceHoldingName?: string;
  sourceHoldingAssetCode?: string;
  sourceHoldingAssetScale?: number;
  targetHoldingId?: string;
  targetHoldingName?: string;
  targetHoldingAssetCode?: string;
  targetHoldingAssetScale?: number;
  categoryId?: string;
  categoryName?: string;
  rootCategoryId?: string;
  rootCategoryName?: string;
  amount?: number;
  assetCode?: string;
  assetScale?: number;
  exchangeRate?: number;
  feeAmount?: number;
  settledAmount?: number;
  balanceAdjustmentDirection?: TransactionPageItemResponseDtoBalanceAdjustmentDirection;
  transactionDate?: string;
  description?: string;
  note?: string;
  externalRef?: string;
  attachments?: TransactionAttachmentResponseDto[];
  createdDate?: string;
  lastModifiedDate?: string;
  convertedAmount?: number;
  convertedInto?: string;
  convertedAssetScale?: number;
}
