/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type UpdateAssetRequestDtoMarketDataSource =
  (typeof UpdateAssetRequestDtoMarketDataSource)[keyof typeof UpdateAssetRequestDtoMarketDataSource];

export const UpdateAssetRequestDtoMarketDataSource = {
  NONE: 'NONE',
  FRANKFURTER: 'FRANKFURTER',
  COINGECKO: 'COINGECKO',
  MANUAL: 'MANUAL',
} as const;
