/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { UpdateBudgetPlanRequestDtoPeriodType } from './updateBudgetPlanRequestDtoPeriodType';

export interface UpdateBudgetPlanRequestDto {
  name?: string;
  amount?: number;
  currencyCode?: string;
  periodType?: UpdateBudgetPlanRequestDtoPeriodType;
  validFrom?: string;
  validTo?: string;
  categoryId?: string;
}
