/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { UpdateRecurringBudgetRequestDtoPeriodType } from './updateRecurringBudgetRequestDtoPeriodType';

export interface UpdateRecurringBudgetRequestDto {
  name?: string;
  amount?: number;
  currencyCode?: string;
  periodType?: UpdateRecurringBudgetRequestDtoPeriodType;
  intervalValue?: number;
  startDate?: string;
  endDate?: string;
  categoryId?: string;
}
