/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export interface UpdateTransactionRequestDto {
  holdingId?: string;
  sourceHoldingId?: string;
  targetHoldingId?: string;
  amount?: number;
  currencyCode?: string;
  exchangeRate?: number;
  feeAmount?: number;
  settledAmount?: number;
  categoryId?: string;
  transactionDate?: string;
  description?: string;
  note?: string;
  externalRef?: string;
}
