/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { UpdateGoalPlanRequestDtoCarbStrategy } from './updateGoalPlanRequestDtoCarbStrategy';
import type { UpdateGoalPlanRequestDtoFatStrategy } from './updateGoalPlanRequestDtoFatStrategy';
import type { UpdateGoalPlanRequestDtoGoalType } from './updateGoalPlanRequestDtoGoalType';
import type { UpdateGoalPlanRequestDtoProteinStrategy } from './updateGoalPlanRequestDtoProteinStrategy';
import type { UpdateGoalPlanRequestDtoStartBodyFatSource } from './updateGoalPlanRequestDtoStartBodyFatSource';

export interface UpdateGoalPlanRequestDto {
  name?: string;
  goalType?: UpdateGoalPlanRequestDtoGoalType;
  startDate?: string;
  endDate?: string;
  startWeightKg?: number;
  startBodyFatPercent?: number;
  startBodyFatSource?: UpdateGoalPlanRequestDtoStartBodyFatSource;
  targetWeeklyWeightChangeKg?: number;
  proteinStrategy?: UpdateGoalPlanRequestDtoProteinStrategy;
  fatStrategy?: UpdateGoalPlanRequestDtoFatStrategy;
  carbStrategy?: UpdateGoalPlanRequestDtoCarbStrategy;
  active?: boolean;
  notes?: string;
}
