/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { UpdateRecurringTransactionRequestDtoPeriodType } from './updateRecurringTransactionRequestDtoPeriodType';

export interface UpdateRecurringTransactionRequestDto {
  walletId?: string;
  categoryId?: string;
  amount?: number;
  currencyCode?: string;
  description?: string;
  note?: string;
  periodType?: UpdateRecurringTransactionRequestDtoPeriodType;
  intervalValue?: number;
  startDate?: string;
  endDate?: string;
}
