/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { UpsertNutritionProfileRequestDtoBiologicalSex } from './upsertNutritionProfileRequestDtoBiologicalSex';
import type { UpsertNutritionProfileRequestDtoPreferredUnitSystem } from './upsertNutritionProfileRequestDtoPreferredUnitSystem';

export interface UpsertNutritionProfileRequestDto {
  preferredUnitSystem?: UpsertNutritionProfileRequestDtoPreferredUnitSystem;
  biologicalSex?: UpsertNutritionProfileRequestDtoBiologicalSex;
  heightCm?: number;
  activityMultiplier?: number;
  bodyFatAutoCalculationEnabled?: boolean;
}
