/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export type UpsertNutritionProfileRequestDtoPreferredUnitSystem =
  (typeof UpsertNutritionProfileRequestDtoPreferredUnitSystem)[keyof typeof UpsertNutritionProfileRequestDtoPreferredUnitSystem];

export const UpsertNutritionProfileRequestDtoPreferredUnitSystem = {
  METRIC: 'METRIC',
  IMPERIAL: 'IMPERIAL',
} as const;
