/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */

export interface UserResponseFullDto {
  id?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  roles?: string[];
  createdDate?: string;
  lastModifiedDate?: string;
}
