/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Expense Tracker API
 * Swagger dokumentace pro ExpenseTracker backend
 * OpenAPI spec version: 1.0
 */
import type { WalletResponseDtoWalletType } from './walletResponseDtoWalletType';

export interface WalletResponseDto {
  id?: string;
  name?: string;
  walletType?: WalletResponseDtoWalletType;
  currencyCode?: string;
  iconUrl?: string;
  iconColor?: string;
  initialBalance?: number;
  currentBalance?: number;
  active?: boolean;
  createdDate?: string;
  lastModifiedDate?: string;
}
